-- sdkwork:migration
-- id: 0005_foreign_keys
-- engine: sqlite
-- module: birdcoder
-- purpose: No-op rollback for SQLite FK enforcement enablement
-- reversible: true
-- transactional: true
-- lock: lightweight
-- contract_version: 1.0.0
--
-- SQLite FK enablement is connection-scoped and cannot be reversed by a migration.
-- No DDL operation is required or possible here (per P1-17 task note:
-- "无对应 SQLite 操作"). The PostgreSQL twin migration drops the named constraints.

-- intentionally empty
