-- sdkwork:migration
-- id: 0006_subject_id_not_null
-- engine: sqlite
-- module: birdcoder
-- purpose: Revert user_id backfill (no-op for SQLite, NOT NULL cannot be dropped)
-- reversible: true
-- transactional: true
-- lock: lightweight
-- contract_version: 1.0.0
--
-- SQLite does not support ALTER COLUMN DROP NOT NULL. This down migration is
-- a no-op because the NOT NULL constraint is only enforced on table recreation
-- (baseline DDL). Existing backfilled values remain 0.

-- No-op: SQLite cannot drop NOT NULL constraints without table recreation.
