name: sdkwork_birdcoder_flutter_mobile_host
description: SDKWork Birdcoder Flutter Mobile Host
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_links: ^6.4.0
  flutter_secure_storage: ^9.2.4
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1
