// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

export const BIRDCODER_APP_SDK_STANDARD_PROFILE = "sdkwork-v3" as const;
export const BIRDCODER_APP_SDK_API_PREFIX = "/app/v3/api" as const;
export const BIRDCODER_APP_SDK_PACKAGE_NAME = "@sdkwork/birdcoder-app-sdk" as const;

export type BirdcoderSdkQueryValue = boolean | number | string | null | undefined;

export interface BirdcoderSdkOperationDescriptor {
  dataScope: string;
  deployment: 'all' | 'local' | 'private' | 'saas';
  domain: string;
  key: string;
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  operationId: string;
  path: string;
  pathParamNames: readonly string[];
  permission?: string;
  public: boolean;
  resource: string;
  summary: string;
  tag: string;
  tenantScope: string;
}

export interface BirdCoderApiGatewaySummary {
  docsPath: string;
  liveOpenApiPath: string;
  openApiPath: string;
  routeCatalogPath: string;
  routeCount: number;
  routesBySurface: Record<string, unknown>;
  surfaces: Array<BirdCoderApiGatewaySurfaceSummary>;
}

export interface BirdCoderApiGatewaySurfaceSummary {
  authMode: "host" | "user" | "admin";
  basePath: string;
  description: string;
  name: "app" | "backend";
  routeCount: number;
}

export interface BirdCoderApiRouteCatalogEntry {
  authMode: "host" | "user" | "admin";
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  surface: "app" | "backend";
  summary: string;
  openApiPath: string;
  operationId: string;
}

export interface BirdCoderApiRouteCatalogEntryListEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface BirdCoderCodingServerDescriptor {
  apiVersion: string;
  gateway: BirdCoderApiGatewaySummary;
  hostMode: "web" | "desktop" | "server";
  moduleId: "coding-server";
  openApiPath: string;
  surfaces: Array<"app" | "backend">;
}

export interface BirdCoderCodingServerDescriptorEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface BirdCoderCommitProjectGitChangesRequest {
  runtimeLocationId: string;
  includeUnstaged?: boolean;
  message: string;
}

export interface BirdCoderCoreHealthSummary {
  status: string;
}

export interface BirdCoderCoreHealthSummaryEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface BirdCoderCoreRuntimeSummary {
  host: string;
  port: number;
  configFileName: string;
}

export interface BirdCoderCoreRuntimeSummaryEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface BirdCoderCreateProjectGitBranchRequest {
  runtimeLocationId: string;
  branchName: string;
}

export interface BirdCoderCreateProjectGitWorktreeRequest {
  runtimeLocationId: string;
  branchName: string;
}

export interface BirdCoderCreateProjectRequest {
  description?: string;
  name: string;
  workspaceId: string;
}

export interface BirdCoderCreateProjectRuntimeLocationRequest {
  runtimeTargetId: string;
  runtimeTargetKind: "desktop_device" | "server" | "runner" | "container" | "remote_workspace";
  locationKind: "desktop_checkout" | "server_workspace" | "runner_worktree" | "container_volume" | "remote_workspace";
  pathFlavor: "windows" | "posix";
  rootLocator: string;
  absolutePath: string;
  displayName?: string;
}

export interface BirdCoderCreateWorkspaceRequest {
  description?: string;
  name: string;
  tenantId?: string;
  organizationId?: string;
  dataScope?: "DEFAULT" | "PRIVATE" | "ORGANIZATION" | "TENANT" | "PUBLIC";
  code?: string;
  title?: string;
  ownerId?: string;
  leaderId?: string;
  createdByUserId?: string;
  icon?: string;
  color?: string;
  type?: string;
  startTime?: string;
  endTime?: string;
  maxMembers?: number;
  currentMembers?: number;
  memberCount?: number;
  maxStorage?: string;
  usedStorage?: string;
  settings?: Record<string, unknown>;
  isPublic?: boolean;
  isTemplate?: boolean;
}

export interface BirdCoderGitBranchSummary {
  isCurrent: boolean;
  isRemote: boolean;
  name: string;
}

export interface BirdCoderGitStatusCounts {
  staged: number;
  unstaged: number;
  untracked: number;
}

export interface BirdCoderGitWorktreeSummary {
  branch?: string;
  head?: string;
  isCurrent: boolean;
  prunableReason?: string;
  worktreeKey?: string;
}

export interface BirdCoderProjectGitDiff {
  patch: string;
  truncated: boolean;
}

export interface BirdCoderProjectGitDiffEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface BirdCoderProjectGitOverview {
  branches: Array<BirdCoderGitBranchSummary>;
  currentBranch?: string;
  currentRevision?: string;
  detachedHead: boolean;
  status: "ready" | "not_repository";
  statusCounts: BirdCoderGitStatusCounts;
  worktrees: Array<BirdCoderGitWorktreeSummary>;
}

export interface BirdCoderProjectGitOverviewEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface BirdCoderProjectRuntimeLocation {
  id: string;
  uuid?: string;
  projectId: string;
  runtimeTargetId: string;
  runtimeTargetKind: "desktop_device" | "server" | "runner" | "container" | "remote_workspace";
  locationKind: "desktop_checkout" | "server_workspace" | "runner_worktree" | "container_volume" | "remote_workspace";
  pathFlavor: "windows" | "posix";
  rootLocator: string;
  displayName: string;
  hasAbsolutePath: boolean;
  terminalAvailable: boolean;
  gitAvailable: boolean;
  buildAvailable: boolean;
  fileSystemAvailable: boolean;
  healthStatus: "pending_verification" | "local_observed" | "healthy" | "degraded" | "unavailable" | "revoked";
  lastVerifiedAt?: string;
  lastSeenAt?: string;
  gitRepositoryUrl?: string;
  gitRemoteName?: string;
  gitBranch?: string;
  gitCommit?: string;
  gitWorktreeKey?: string;
  version: string;
  createdAt: string;
  updatedAt: string;
}

export interface BirdCoderProjectRuntimeLocationCommandAccepted {
  accepted: boolean;
  resourceId: string;
  status: "pending_verification" | "local_observed" | "healthy" | "degraded" | "unavailable" | "revoked";
}

export interface BirdCoderProjectRuntimeLocationCommandEnvelope {
  code: 0;
  data: BirdCoderProjectRuntimeLocationCommandAccepted;
  traceId: string;
}

export interface BirdCoderProjectRuntimeLocationEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface BirdCoderProjectRuntimeLocationListEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface BirdCoderProjectRuntimeLocationPreference {
  id: string;
  projectId: string;
  subjectUserId: string;
  capability: "terminal" | "git" | "build" | "file_system";
  runtimeLocationId: string;
  version: string;
  createdAt: string;
  updatedAt: string;
}

export interface BirdCoderProjectRuntimeLocationPreferenceEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface BirdCoderProjectRuntimeLocationPreferenceListEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface BirdCoderProjectSummary {
  createdAt: string;
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  dataScope?: "DEFAULT" | "PRIVATE" | "ORGANIZATION" | "TENANT" | "PUBLIC";
  workspaceId: string;
  workspaceUuid?: string;
  userId?: string;
  parentId?: string;
  parentUuid?: string;
  parentMetadata?: Record<string, unknown>;
  code?: string;
  title?: string;
  name: string;
  description?: string;
  domainPrefix?: string;
  ownerId?: string;
  leaderId?: string;
  createdByUserId?: string;
  author?: string;
  fileId?: string;
  conversationId?: string;
  type?: string;
  startTime?: string;
  endTime?: string;
  budgetAmount?: string;
  coverImage?: Record<string, unknown>;
  isTemplate?: boolean;
  collaboratorCount?: number;
  status: "active" | "archived";
  updatedAt: string;
  viewerRole?: "owner" | "admin" | "member" | "viewer";
}

export interface BirdCoderProjectSummaryEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface BirdCoderProjectSummaryListEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface BirdCoderProjectWorkspaceBinding {
  id: string;
  projectId: string;
  sandboxId: string;
  rootEntryId: string;
  logicalPath: string;
  lifecycleStatus: "active";
  version: string;
  createdAt: string;
  updatedAt: string;
}

export interface BirdCoderProjectWorkspaceBindingEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface BirdCoderPruneProjectGitWorktreesRequest {
  runtimeLocationId: string;
}

export interface BirdCoderPushProjectGitBranchRequest {
  runtimeLocationId: string;
  branchName?: string;
  remoteName?: string;
}

export interface BirdCoderRebindProjectRuntimeLocationRequest {
  pathFlavor: "windows" | "posix";
  rootLocator: string;
  absolutePath: string;
  displayName?: string;
}

export interface BirdCoderRemoveProjectGitWorktreeRequest {
  runtimeLocationId: string;
  force?: boolean;
  worktreeKey: string;
}

export interface BirdCoderSetProjectRuntimeLocationPreferenceRequest {
  runtimeLocationId: string;
}

export interface BirdCoderSwitchProjectGitBranchRequest {
  runtimeLocationId: string;
  branchName: string;
}

export interface BirdCoderUpdateProjectRequest {
  description?: string;
  name?: string;
  status?: "active" | "archived";
}

export interface BirdCoderUpdateProjectRuntimeLocationRequest {
  displayName?: string;
}

export interface BirdCoderUpdateWorkspaceRequest {
  description?: string;
  dataScope?: "DEFAULT" | "PRIVATE" | "ORGANIZATION" | "TENANT" | "PUBLIC";
  code?: string;
  title?: string;
  name?: string;
  ownerId?: string;
  leaderId?: string;
  createdByUserId?: string;
  icon?: string;
  color?: string;
  type?: string;
  startTime?: string;
  endTime?: string;
  maxMembers?: number;
  currentMembers?: number;
  memberCount?: number;
  maxStorage?: string;
  usedStorage?: string;
  settings?: Record<string, unknown>;
  isPublic?: boolean;
  isTemplate?: boolean;
  status?: "active" | "archived";
}

export interface BirdCoderUpsertProjectWorkspaceBindingRequest {
  sandboxId: string;
  rootEntryId: string;
  logicalPath: string;
}

export interface BirdCoderWorkspaceSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  dataScope?: "DEFAULT" | "PRIVATE" | "ORGANIZATION" | "TENANT" | "PUBLIC";
  code?: string;
  title?: string;
  name: string;
  description?: string;
  icon?: string;
  color?: string;
  ownerId?: string;
  leaderId?: string;
  createdByUserId?: string;
  type?: string;
  startTime?: string;
  endTime?: string;
  maxMembers?: number;
  currentMembers?: number;
  memberCount?: number;
  maxStorage?: string;
  usedStorage?: string;
  settings?: Record<string, unknown>;
  isPublic?: boolean;
  isTemplate?: boolean;
  status: "active" | "archived";
  viewerRole?: "owner" | "admin" | "member" | "viewer";
}

export interface BirdCoderWorkspaceSummaryEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface BirdCoderWorkspaceSummaryListEnvelope {
  code: 0;
  data: Record<string, unknown>;
  traceId: string;
}

export interface PageInfo {
  mode: "offset" | "cursor";
  page?: number;
  pageSize?: number;
  totalItems?: string;
  totalPages?: number;
  nextCursor?: string;
  hasMore?: boolean;
}

export interface ProblemDetail {
  type: string;
  title: string;
  status: number;
  detail?: string;
  instance?: string;
  code: number;
  traceId: string;
}

export interface SdkWorkApiResponse {
  code: 0;
  data: unknown;
  traceId: string;
}

export interface PlatformProjectsDeletePathParams {
  projectId: string;
}

export interface PlatformProjectsGitBranchesCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsGitBranchSwitchCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsGitCommitsCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsGitDiffRetrievePathParams {
  projectId: string;
}

export interface PlatformProjectsGitDiffRetrieveQuery extends Record<string, BirdcoderSdkQueryValue> {
  runtime_location_id: string;
}

export interface PlatformProjectsGitOverviewRetrievePathParams {
  projectId: string;
}

export interface PlatformProjectsGitOverviewRetrieveQuery extends Record<string, BirdcoderSdkQueryValue> {
  runtime_location_id: string;
}

export interface PlatformProjectsGitPushesCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsGitWorktreePruneCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsGitWorktreeRemovalsCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsGitWorktreesCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsListQuery extends Record<string, BirdcoderSdkQueryValue> {
  userId?: string;
  workspaceId?: string;
  page?: number;
  page_size?: number;
}

export interface PlatformProjectsRetrievePathParams {
  projectId: string;
}

export interface PlatformProjectsRuntimeLocationsCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsRuntimeLocationsDeletePathParams {
  projectId: string;
  runtimeLocationId: string;
}

export interface PlatformProjectsRuntimeLocationsListPathParams {
  projectId: string;
}

export interface PlatformProjectsRuntimeLocationsListQuery extends Record<string, BirdcoderSdkQueryValue> {
  page?: number;
  page_size?: number;
}

export interface PlatformProjectsRuntimeLocationsPreferencesListPathParams {
  projectId: string;
}

export interface PlatformProjectsRuntimeLocationsPreferencesListQuery extends Record<string, BirdcoderSdkQueryValue> {
  page?: number;
  page_size?: number;
}

export interface PlatformProjectsRuntimeLocationsPreferencesUpdatePathParams {
  projectId: string;
  capability: string;
}

export interface PlatformProjectsRuntimeLocationsRebindPathParams {
  projectId: string;
  runtimeLocationId: string;
}

export interface PlatformProjectsRuntimeLocationsRequestVerificationPathParams {
  projectId: string;
  runtimeLocationId: string;
}

export interface PlatformProjectsRuntimeLocationsRetrievePathParams {
  projectId: string;
  runtimeLocationId: string;
}

export interface PlatformProjectsRuntimeLocationsUpdatePathParams {
  projectId: string;
  runtimeLocationId: string;
}

export interface PlatformProjectsUpdatePathParams {
  projectId: string;
}

export interface PlatformProjectsWorkspaceBindingDeletePathParams {
  projectId: string;
}

export interface PlatformProjectsWorkspaceBindingRetrievePathParams {
  projectId: string;
}

export interface PlatformProjectsWorkspaceBindingUpdatePathParams {
  projectId: string;
}

export interface PlatformWorkspacesDeletePathParams {
  workspaceId: string;
}

export interface PlatformWorkspacesListQuery extends Record<string, BirdcoderSdkQueryValue> {
  userId?: string;
  page?: number;
  page_size?: number;
}

export interface PlatformWorkspacesRetrievePathParams {
  workspaceId: string;
}

export interface PlatformWorkspacesUpdatePathParams {
  workspaceId: string;
}

export const BIRDCODER_APP_SDK_OPERATIONS = [
  {
    "key": "platform.projects.create",
    "method": "POST",
    "operationId": "projects.create",
    "path": "/app/v3/api/projects",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects.create",
    "public": false,
    "resource": "birdcoder.platform-projects",
    "summary": "Create project",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.delete",
    "method": "DELETE",
    "operationId": "projects.delete",
    "path": "/app/v3/api/projects/{projectId}",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects.delete",
    "public": false,
    "resource": "birdcoder.platform-projects",
    "summary": "Delete project",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.branches.create",
    "method": "POST",
    "operationId": "projects.git.branches.create",
    "path": "/app/v3/api/projects/{projectId}/git/branches",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-git-branches.create",
    "public": false,
    "resource": "birdcoder.platform-projects-git-branches",
    "summary": "Create project Git branch",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.branchSwitch.create",
    "method": "POST",
    "operationId": "projects.git.branchSwitch.create",
    "path": "/app/v3/api/projects/{projectId}/git/branch_switch",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-git-branch-switch.create",
    "public": false,
    "resource": "birdcoder.platform-projects-git-branch-switch",
    "summary": "Switch project Git branch",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.commits.create",
    "method": "POST",
    "operationId": "projects.git.commits.create",
    "path": "/app/v3/api/projects/{projectId}/git/commits",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-git-commits.create",
    "public": false,
    "resource": "birdcoder.platform-projects-git-commits",
    "summary": "Commit project Git changes",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.diff.retrieve",
    "method": "GET",
    "operationId": "projects.git.diff.retrieve",
    "path": "/app/v3/api/projects/{projectId}/git/diff",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-git-overview.read",
    "public": false,
    "resource": "birdcoder.platform-projects-git-overview",
    "summary": "Get project Git diff",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.overview.retrieve",
    "method": "GET",
    "operationId": "projects.git.overview.retrieve",
    "path": "/app/v3/api/projects/{projectId}/git/overview",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-git-overview.read",
    "public": false,
    "resource": "birdcoder.platform-projects-git-overview",
    "summary": "Get project Git overview",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.pushes.create",
    "method": "POST",
    "operationId": "projects.git.pushes.create",
    "path": "/app/v3/api/projects/{projectId}/git/pushes",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-git-pushes.create",
    "public": false,
    "resource": "birdcoder.platform-projects-git-pushes",
    "summary": "Push project Git branch",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.worktreePrune.create",
    "method": "POST",
    "operationId": "projects.git.worktreePrune.create",
    "path": "/app/v3/api/projects/{projectId}/git/worktree_prune",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-git-worktree-prune.create",
    "public": false,
    "resource": "birdcoder.platform-projects-git-worktree-prune",
    "summary": "Prune project Git worktrees",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.worktreeRemovals.create",
    "method": "POST",
    "operationId": "projects.git.worktreeRemovals.create",
    "path": "/app/v3/api/projects/{projectId}/git/worktree_removals",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-git-worktree-removals.create",
    "public": false,
    "resource": "birdcoder.platform-projects-git-worktree-removals",
    "summary": "Remove project Git worktree",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.worktrees.create",
    "method": "POST",
    "operationId": "projects.git.worktrees.create",
    "path": "/app/v3/api/projects/{projectId}/git/worktrees",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-git-worktrees.create",
    "public": false,
    "resource": "birdcoder.platform-projects-git-worktrees",
    "summary": "Create project Git worktree",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.list",
    "method": "GET",
    "operationId": "projects.list",
    "path": "/app/v3/api/projects",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects.read",
    "public": false,
    "resource": "birdcoder.platform-projects",
    "summary": "List projects",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.retrieve",
    "method": "GET",
    "operationId": "projects.retrieve",
    "path": "/app/v3/api/projects/{projectId}",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects.read",
    "public": false,
    "resource": "birdcoder.platform-projects",
    "summary": "Get project",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.runtimeLocations.create",
    "method": "POST",
    "operationId": "projects.runtimeLocations.create",
    "path": "/app/v3/api/projects/{projectId}/runtime_locations",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-runtime-locations.create",
    "public": false,
    "resource": "birdcoder.platform-projects-runtime-locations",
    "summary": "Register project runtime location",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.runtimeLocations.delete",
    "method": "DELETE",
    "operationId": "projects.runtimeLocations.delete",
    "path": "/app/v3/api/projects/{projectId}/runtime_locations/{runtimeLocationId}",
    "pathParamNames": [
      "projectId",
      "runtimeLocationId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-runtime-locations.delete",
    "public": false,
    "resource": "birdcoder.platform-projects-runtime-locations",
    "summary": "Delete project runtime location",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.runtimeLocations.list",
    "method": "GET",
    "operationId": "projects.runtimeLocations.list",
    "path": "/app/v3/api/projects/{projectId}/runtime_locations",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-runtime-locations.read",
    "public": false,
    "resource": "birdcoder.platform-projects-runtime-locations",
    "summary": "List project runtime locations",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.runtimeLocations.preferences.list",
    "method": "GET",
    "operationId": "projects.runtimeLocations.preferences.list",
    "path": "/app/v3/api/projects/{projectId}/runtime_location_preferences",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-runtime-locations-preferences.read",
    "public": false,
    "resource": "birdcoder.platform-projects-runtime-locations-preferences",
    "summary": "List project runtime-location preferences",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.runtimeLocations.preferences.update",
    "method": "PUT",
    "operationId": "projects.runtimeLocations.preferences.update",
    "path": "/app/v3/api/projects/{projectId}/runtime_location_preferences/{capability}",
    "pathParamNames": [
      "projectId",
      "capability"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-runtime-locations-preferences.update",
    "public": false,
    "resource": "birdcoder.platform-projects-runtime-locations-preferences",
    "summary": "Update project runtime-location preference",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.runtimeLocations.rebind",
    "method": "POST",
    "operationId": "projects.runtimeLocations.rebind",
    "path": "/app/v3/api/projects/{projectId}/runtime_locations/{runtimeLocationId}/rebind",
    "pathParamNames": [
      "projectId",
      "runtimeLocationId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-runtime-locations.create",
    "public": false,
    "resource": "birdcoder.platform-projects-runtime-locations",
    "summary": "Rebind project runtime location",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.runtimeLocations.requestVerification",
    "method": "POST",
    "operationId": "projects.runtimeLocations.requestVerification",
    "path": "/app/v3/api/projects/{projectId}/runtime_locations/{runtimeLocationId}/request_verification",
    "pathParamNames": [
      "projectId",
      "runtimeLocationId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-runtime-locations.create",
    "public": false,
    "resource": "birdcoder.platform-projects-runtime-locations",
    "summary": "Request project runtime-location verification",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.runtimeLocations.retrieve",
    "method": "GET",
    "operationId": "projects.runtimeLocations.retrieve",
    "path": "/app/v3/api/projects/{projectId}/runtime_locations/{runtimeLocationId}",
    "pathParamNames": [
      "projectId",
      "runtimeLocationId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-runtime-locations.read",
    "public": false,
    "resource": "birdcoder.platform-projects-runtime-locations",
    "summary": "Get project runtime location",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.runtimeLocations.update",
    "method": "PATCH",
    "operationId": "projects.runtimeLocations.update",
    "path": "/app/v3/api/projects/{projectId}/runtime_locations/{runtimeLocationId}",
    "pathParamNames": [
      "projectId",
      "runtimeLocationId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-runtime-locations.update",
    "public": false,
    "resource": "birdcoder.platform-projects-runtime-locations",
    "summary": "Update project runtime location",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.update",
    "method": "PATCH",
    "operationId": "projects.update",
    "path": "/app/v3/api/projects/{projectId}",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects.update",
    "public": false,
    "resource": "birdcoder.platform-projects",
    "summary": "Update project",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.workspaceBinding.delete",
    "method": "DELETE",
    "operationId": "projects.workspaceBinding.delete",
    "path": "/app/v3/api/projects/{projectId}/workspace_binding",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-workspace-binding.delete",
    "public": false,
    "resource": "birdcoder.platform-projects-workspace-binding",
    "summary": "Delete project workspace binding",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.workspaceBinding.retrieve",
    "method": "GET",
    "operationId": "projects.workspaceBinding.retrieve",
    "path": "/app/v3/api/projects/{projectId}/workspace_binding",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-workspace-binding.read",
    "public": false,
    "resource": "birdcoder.platform-projects-workspace-binding",
    "summary": "Get project workspace binding",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.workspaceBinding.update",
    "method": "PUT",
    "operationId": "projects.workspaceBinding.update",
    "path": "/app/v3/api/projects/{projectId}/workspace_binding",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-projects-workspace-binding.update",
    "public": false,
    "resource": "birdcoder.platform-projects-workspace-binding",
    "summary": "Create or update project workspace binding",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.workspaces.create",
    "method": "POST",
    "operationId": "workspaces.create",
    "path": "/app/v3/api/workspaces",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-workspaces.create",
    "public": false,
    "resource": "birdcoder.platform-workspaces",
    "summary": "Create workspace",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.workspaces.delete",
    "method": "DELETE",
    "operationId": "workspaces.delete",
    "path": "/app/v3/api/workspaces/{workspaceId}",
    "pathParamNames": [
      "workspaceId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-workspaces.delete",
    "public": false,
    "resource": "birdcoder.platform-workspaces",
    "summary": "Delete workspace",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.workspaces.list",
    "method": "GET",
    "operationId": "workspaces.list",
    "path": "/app/v3/api/workspaces",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-workspaces.read",
    "public": false,
    "resource": "birdcoder.platform-workspaces",
    "summary": "List workspaces",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.workspaces.retrieve",
    "method": "GET",
    "operationId": "workspaces.retrieve",
    "path": "/app/v3/api/workspaces/{workspaceId}",
    "pathParamNames": [
      "workspaceId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-workspaces.read",
    "public": false,
    "resource": "birdcoder.platform-workspaces",
    "summary": "Get workspace",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.workspaces.update",
    "method": "PATCH",
    "operationId": "workspaces.update",
    "path": "/app/v3/api/workspaces/{workspaceId}",
    "pathParamNames": [
      "workspaceId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "birdcoder.platform-workspaces.update",
    "public": false,
    "resource": "birdcoder.platform-workspaces",
    "summary": "Update workspace",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "system.descriptor.retrieve",
    "method": "GET",
    "operationId": "descriptor.retrieve",
    "path": "/app/v3/api/system/descriptor",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "system",
    "permission": "birdcoder.system-descriptor.read",
    "public": false,
    "resource": "birdcoder.system-descriptor",
    "summary": "Get coding-server descriptor",
    "tag": "system",
    "tenantScope": "tenant"
  },
  {
    "key": "system.health.retrieve",
    "method": "GET",
    "operationId": "health.retrieve",
    "path": "/app/v3/api/system/health",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "system",
    "permission": "birdcoder.system-health.read",
    "public": false,
    "resource": "birdcoder.system-health",
    "summary": "Get coding-server health",
    "tag": "system",
    "tenantScope": "tenant"
  },
  {
    "key": "system.routes.list",
    "method": "GET",
    "operationId": "routes.list",
    "path": "/app/v3/api/system/routes",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "system",
    "permission": "birdcoder.system-routes.read",
    "public": false,
    "resource": "birdcoder.system-routes",
    "summary": "List unified API routes",
    "tag": "system",
    "tenantScope": "tenant"
  },
  {
    "key": "system.runtime.retrieve",
    "method": "GET",
    "operationId": "runtime.retrieve",
    "path": "/app/v3/api/system/runtime",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "system",
    "permission": "birdcoder.system-runtime.read",
    "public": false,
    "resource": "birdcoder.system-runtime",
    "summary": "Get runtime metadata",
    "tag": "system",
    "tenantScope": "tenant"
  }
] as const;

export const BIRDCODER_APP_SDK_OPERATION_INDEX: Record<string, BirdcoderSdkOperationDescriptor> = Object.fromEntries(
  BIRDCODER_APP_SDK_OPERATIONS.map((operation) => [operation.key, operation]),
);
