export type {
  AgentSessionItemPresentation,
  AgentSessionCommandView,
  AgentSessionItemReasoningView,
  AgentSessionItemResourceView,
  AgentSessionItemView,
  AgentSessionItemViewKind,
  ChatMessageContentBlock,
  ChatMessageLayoutHints,
  ChatMessageReasoningBlock,
  ChatMessageResourcesBlock,
  ChatMessageTaskProgressDisplayState,
  ChatMessageToolCall,
  ChatTurnActivitySummary,
  ChatMessageViewSource,
  FileChange,
  ActivityFileChangeView,
  ComposeChatTranscriptActivityOptions,
  ResolveChatMessageViewOptions,
} from '@sdkwork/birdcoder-pc-contracts-commons';

export {
  buildChatMessageViewSynchronizationSignature,
  estimateChatMessageViewHeight,
  normalizeTaskProgressCounter,
  normalizeChatMessageReasoning,
  normalizeChatMessageCommand,
  parseFileUpdateSummaryContent,
  normalizeChatMessageToolCall,
  normalizeChatMessageToolCalls,
  composeChatTranscriptActivity,
  readTaskProgressCounter,
  resolveBirdCoderCodeEngineCommandInteractionState,
  resolveChatTurnActivitySummary,
  resolveChatMessageView,
  resolveChatMessageViews,
  resolveMessageCopyContent,
  resolveActivityFileChangeViews,
  resolveTaskProgressDisplayState,
  resolveVisibleAssistantMessageContent,
  resolveVisibleMarkdownBlockContent,
  shouldHideMessageContentAsFileUpdateSummary,
  stripFileUpdateSummaryContent,
} from '@sdkwork/birdcoder-pc-contracts-commons';
