const BIRDCODER_LONG_INTEGER_JSON_SCALAR_KEY_VALUES = [
  'accessCount', 'access_count', 'afterBalance', 'after_balance', 'agentBizType',
  'agent_biz_type', 'availablePoints', 'available_points', 'avgResponseTime',
  'avg_response_time', 'balance', 'beforeBalance', 'before_balance', 'bizType',
  'biz_type', 'blockedCount', 'blocked_count', 'budgetAmount', 'budget_amount',
  'changeAmount', 'change_amount', 'channelMsgSeq', 'channel_msg_seq', 'chunkSize',
  'chunk_size', 'commentCount', 'comment_count', 'configValue', 'config_value',
  'contextTokens', 'context_tokens', 'dailyLimit', 'dailyRequestQuota',
  'dailyTokenQuota', 'daily_limit', 'daily_request_quota', 'daily_token_quota',
  'diskSize', 'disk_size', 'duration', 'favoriteCount', 'favorite_count',
  'fileSize', 'file_size', 'followerCount', 'follower_count', 'followingCount',
  'following_count', 'frozenPoints', 'frozenToken', 'frozen_points', 'frozen_token',
  'increaseBonus', 'increase_bonus', 'initIncreaseBonus', 'init_increase_bonus',
  'installCount', 'install_count', 'lastUpdatedAt', 'last_updated_at', 'likeCount',
  'like_count', 'maxIncreaseBonus', 'maxInputTokens', 'maxOutputTokens',
  'maxStorage', 'max_increase_bonus', 'max_input_tokens', 'max_output_tokens',
  'max_storage', 'monthlyLimit', 'monthlyRequestQuota', 'monthlyTokenQuota',
  'monthly_limit', 'monthly_request_quota', 'monthly_token_quota', 'mutualCount',
  'mutual_count', 'pointAmount', 'pointBalance', 'pointCost', 'point_amount',
  'point_balance', 'point_cost', 'points', 'pointsAfter', 'pointsBefore',
  'pointsChange', 'points_after', 'points_before', 'points_change',
  'popularityScore', 'popularity_score', 'processingTime', 'processing_time',
  'ratingCount', 'rating_count', 'requestTimestamp', 'request_timestamp',
  'requiredPoints', 'required_points', 'rowCount', 'row_count', 'seed', 'sequence',
  'sequenceNo', 'sequence_no', 'shareCount', 'share_count', 'size', 'sizeBytes',
  'size_bytes', 'sortTimestamp', 'sort_timestamp', 'sourceSequence', 'specialCount',
  'special_count', 'timestampMs', 'timestamp_ms', 'tokenAfter', 'tokenBalance',
  'tokenBefore', 'tokenChange', 'token_after', 'token_balance', 'token_before',
  'token_change', 'totalInteractionCount', 'totalLimit', 'totalRechargedPoints',
  'totalSize', 'totalTokens', 'total_interaction_count', 'total_limit',
  'total_recharged_points', 'total_size', 'total_tokens', 'usageCount',
  'usage_count', 'useCount', 'use_count', 'usedCount', 'usedSize', 'usedStorage',
  'used_count', 'used_size', 'used_storage', 'v', 'version', 'viewCount',
  'view_count',
] as const;

export const BIRDCODER_LONG_INTEGER_JSON_SCALAR_KEYS: ReadonlySet<string> =
  new Set(BIRDCODER_LONG_INTEGER_JSON_SCALAR_KEY_VALUES);
