{{- if not .Values.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdkwork-birdcoder.fullname" . }}-auth
  labels:
    app.kubernetes.io/name: sdkwork-birdcoder
type: Opaque
stringData:
  manageUsername: {{ required "A valid .Values.auth.manageUsername is required" .Values.auth.manageUsername }}
  managePassword: {{ required "A valid .Values.auth.managePassword is required" .Values.auth.managePassword }}
{{- if .Values.redis.enabled }}
{{- if .Values.redis.username }}
  SDKWORK_BIRDCODER_REDIS_USERNAME: {{ .Values.redis.username | quote }}
{{- end }}
{{- if .Values.redis.password }}
  SDKWORK_BIRDCODER_REDIS_PASSWORD: {{ .Values.redis.password | quote }}
{{- end }}
{{- end }}
{{- end -}}
