export type {
  BirdCoderChatMessage,
  BirdCoderChatMessageView,
  BirdCoderChatMessageViewKind,
  BirdCoderCodeEngineKey,
  BirdCoderGitWorktreeSummary,
  BirdCoderSubmitApprovalDecisionRequest,
  BirdCoderSubmitUserQuestionAnswerRequest,
  ChatMessageContentBlock,
  ChatMessageLayoutHints,
  ChatMessageTaskProgressDisplayState,
  ChatMessageToolCall,
  ChatMessageViewSource,
  CommandExecution,
  FileChange,
  ProjectedActivityFileChange,
  ResolveChatMessageViewOptions,
} from '@sdkwork/birdcoder-pc-types';

export {
  BIRDCODER_CODE_ENGINE_KEYS,
  buildChatMessageViewSynchronizationSignature,
  estimateChatMessageViewHeight,
  normalizeTaskProgressCounter,
  parseFileUpdateSummaryContent,
  projectChatMessageToolCall,
  projectChatMessageToolCalls,
  readTaskProgressCounter,
  resolveBirdCoderCodeEngineCommandInteractionState,
  resolveChatMessageView,
  resolveChatMessageViews,
  resolveMessageCopyContent,
  resolveProjectedActivityFileChanges,
  resolveTaskProgressDisplayState,
  resolveVisibleAssistantMessageContent,
  resolveVisibleMarkdownBlockContent,
  shouldHideMessageContentAsFileUpdateSummary,
  stripFileUpdateSummaryContent,
} from '@sdkwork/birdcoder-pc-types';
