// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

pub const SDKWORK_STANDARD_PROFILE: &str = "sdkwork-v3";
pub const API_PREFIX: &str = "/app/v3/api";
pub const PACKAGE_NAME: &str = "@sdkwork/birdcoder-app-sdk";
pub const AUTHORIZATION_HEADER: &str = "Authorization";
pub const SDKWORK_ACCESS_TOKEN_HEADER: &str = "Access-Token";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SdkOperation {
    pub data_scope: &'static str,
    pub deployment: &'static str,
    pub domain: &'static str,
    pub key: &'static str,
    pub method: &'static str,
    pub operation_id: &'static str,
    pub path: &'static str,
    pub path_param_names: &'static [&'static str],
    pub permission: Option<&'static str>,
    pub public: bool,
    pub resource: &'static str,
    pub summary: &'static str,
    pub tag: &'static str,
    pub tenant_scope: &'static str,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct SdkAuthTokens {
    pub access_token: Option<String>,
    pub auth_token: Option<String>,
}

pub mod platform {
    pub mod projects {
        pub const CREATE: crate::SdkOperation = crate::SdkOperation {
            data_scope: "organization",
            deployment: "all",
            domain: "platform",
            key: "platform.projects.create",
            method: "POST",
            operation_id: "projects.create",
            path: "/app/v3/api/projects",
            path_param_names: &[],
            permission: Some("birdcoder.platform-projects.create"),
            public: false,
            resource: "birdcoder.platform-projects",
            summary: "Create project",
            tag: "platform",
            tenant_scope: "tenant",
        };

        pub const DELETE: crate::SdkOperation = crate::SdkOperation {
            data_scope: "organization",
            deployment: "all",
            domain: "platform",
            key: "platform.projects.delete",
            method: "DELETE",
            operation_id: "projects.delete",
            path: "/app/v3/api/projects/{projectId}",
            path_param_names: &["projectId"],
            permission: Some("birdcoder.platform-projects.delete"),
            public: false,
            resource: "birdcoder.platform-projects",
            summary: "Delete project",
            tag: "platform",
            tenant_scope: "tenant",
        };

        pub mod git {
            pub mod branches {
                pub const CREATE: crate::SdkOperation = crate::SdkOperation {
                    data_scope: "organization",
                    deployment: "all",
                    domain: "platform",
                    key: "platform.projects.git.branches.create",
                    method: "POST",
                    operation_id: "projects.git.branches.create",
                    path: "/app/v3/api/projects/{projectId}/git/branches",
                    path_param_names: &["projectId"],
                    permission: Some("birdcoder.platform-projects-git-branches.create"),
                    public: false,
                    resource: "birdcoder.platform-projects-git-branches",
                    summary: "Create project Git branch",
                    tag: "platform",
                    tenant_scope: "tenant",
                };
            }

            pub mod branch_switch {
                pub const CREATE: crate::SdkOperation = crate::SdkOperation {
                    data_scope: "organization",
                    deployment: "all",
                    domain: "platform",
                    key: "platform.projects.git.branchSwitch.create",
                    method: "POST",
                    operation_id: "projects.git.branchSwitch.create",
                    path: "/app/v3/api/projects/{projectId}/git/branch_switch",
                    path_param_names: &["projectId"],
                    permission: Some("birdcoder.platform-projects-git-branch-switch.create"),
                    public: false,
                    resource: "birdcoder.platform-projects-git-branch-switch",
                    summary: "Switch project Git branch",
                    tag: "platform",
                    tenant_scope: "tenant",
                };
            }

            pub mod commits {
                pub const CREATE: crate::SdkOperation = crate::SdkOperation {
                    data_scope: "organization",
                    deployment: "all",
                    domain: "platform",
                    key: "platform.projects.git.commits.create",
                    method: "POST",
                    operation_id: "projects.git.commits.create",
                    path: "/app/v3/api/projects/{projectId}/git/commits",
                    path_param_names: &["projectId"],
                    permission: Some("birdcoder.platform-projects-git-commits.create"),
                    public: false,
                    resource: "birdcoder.platform-projects-git-commits",
                    summary: "Commit project Git changes",
                    tag: "platform",
                    tenant_scope: "tenant",
                };
            }

            pub mod diff {
                pub const RETRIEVE: crate::SdkOperation = crate::SdkOperation {
                    data_scope: "organization",
                    deployment: "all",
                    domain: "platform",
                    key: "platform.projects.git.diff.retrieve",
                    method: "GET",
                    operation_id: "projects.git.diff.retrieve",
                    path: "/app/v3/api/projects/{projectId}/git/diff",
                    path_param_names: &["projectId"],
                    permission: Some("birdcoder.platform-projects-git-overview.read"),
                    public: false,
                    resource: "birdcoder.platform-projects-git-overview",
                    summary: "Get project Git diff",
                    tag: "platform",
                    tenant_scope: "tenant",
                };
            }

            pub mod overview {
                pub const RETRIEVE: crate::SdkOperation = crate::SdkOperation {
                    data_scope: "organization",
                    deployment: "all",
                    domain: "platform",
                    key: "platform.projects.git.overview.retrieve",
                    method: "GET",
                    operation_id: "projects.git.overview.retrieve",
                    path: "/app/v3/api/projects/{projectId}/git/overview",
                    path_param_names: &["projectId"],
                    permission: Some("birdcoder.platform-projects-git-overview.read"),
                    public: false,
                    resource: "birdcoder.platform-projects-git-overview",
                    summary: "Get project Git overview",
                    tag: "platform",
                    tenant_scope: "tenant",
                };
            }

            pub mod pushes {
                pub const CREATE: crate::SdkOperation = crate::SdkOperation {
                    data_scope: "organization",
                    deployment: "all",
                    domain: "platform",
                    key: "platform.projects.git.pushes.create",
                    method: "POST",
                    operation_id: "projects.git.pushes.create",
                    path: "/app/v3/api/projects/{projectId}/git/pushes",
                    path_param_names: &["projectId"],
                    permission: Some("birdcoder.platform-projects-git-pushes.create"),
                    public: false,
                    resource: "birdcoder.platform-projects-git-pushes",
                    summary: "Push project Git branch",
                    tag: "platform",
                    tenant_scope: "tenant",
                };
            }

            pub mod worktree_prune {
                pub const CREATE: crate::SdkOperation = crate::SdkOperation {
                    data_scope: "organization",
                    deployment: "all",
                    domain: "platform",
                    key: "platform.projects.git.worktreePrune.create",
                    method: "POST",
                    operation_id: "projects.git.worktreePrune.create",
                    path: "/app/v3/api/projects/{projectId}/git/worktree_prune",
                    path_param_names: &["projectId"],
                    permission: Some("birdcoder.platform-projects-git-worktree-prune.create"),
                    public: false,
                    resource: "birdcoder.platform-projects-git-worktree-prune",
                    summary: "Prune project Git worktrees",
                    tag: "platform",
                    tenant_scope: "tenant",
                };
            }

            pub mod worktree_removals {
                pub const CREATE: crate::SdkOperation = crate::SdkOperation {
                    data_scope: "organization",
                    deployment: "all",
                    domain: "platform",
                    key: "platform.projects.git.worktreeRemovals.create",
                    method: "POST",
                    operation_id: "projects.git.worktreeRemovals.create",
                    path: "/app/v3/api/projects/{projectId}/git/worktree_removals",
                    path_param_names: &["projectId"],
                    permission: Some("birdcoder.platform-projects-git-worktree-removals.create"),
                    public: false,
                    resource: "birdcoder.platform-projects-git-worktree-removals",
                    summary: "Remove project Git worktree",
                    tag: "platform",
                    tenant_scope: "tenant",
                };
            }

            pub mod worktrees {
                pub const CREATE: crate::SdkOperation = crate::SdkOperation {
                    data_scope: "organization",
                    deployment: "all",
                    domain: "platform",
                    key: "platform.projects.git.worktrees.create",
                    method: "POST",
                    operation_id: "projects.git.worktrees.create",
                    path: "/app/v3/api/projects/{projectId}/git/worktrees",
                    path_param_names: &["projectId"],
                    permission: Some("birdcoder.platform-projects-git-worktrees.create"),
                    public: false,
                    resource: "birdcoder.platform-projects-git-worktrees",
                    summary: "Create project Git worktree",
                    tag: "platform",
                    tenant_scope: "tenant",
                };
            }
        }

        pub const LIST: crate::SdkOperation = crate::SdkOperation {
            data_scope: "organization",
            deployment: "all",
            domain: "platform",
            key: "platform.projects.list",
            method: "GET",
            operation_id: "projects.list",
            path: "/app/v3/api/projects",
            path_param_names: &[],
            permission: Some("birdcoder.platform-projects.read"),
            public: false,
            resource: "birdcoder.platform-projects",
            summary: "List projects",
            tag: "platform",
            tenant_scope: "tenant",
        };

        pub const RETRIEVE: crate::SdkOperation = crate::SdkOperation {
            data_scope: "organization",
            deployment: "all",
            domain: "platform",
            key: "platform.projects.retrieve",
            method: "GET",
            operation_id: "projects.retrieve",
            path: "/app/v3/api/projects/{projectId}",
            path_param_names: &["projectId"],
            permission: Some("birdcoder.platform-projects.read"),
            public: false,
            resource: "birdcoder.platform-projects",
            summary: "Get project",
            tag: "platform",
            tenant_scope: "tenant",
        };

        pub mod runtime_locations {
            pub const CREATE: crate::SdkOperation = crate::SdkOperation {
                data_scope: "organization",
                deployment: "all",
                domain: "platform",
                key: "platform.projects.runtimeLocations.create",
                method: "POST",
                operation_id: "projects.runtimeLocations.create",
                path: "/app/v3/api/projects/{projectId}/runtime_locations",
                path_param_names: &["projectId"],
                permission: Some("birdcoder.platform-projects-runtime-locations.create"),
                public: false,
                resource: "birdcoder.platform-projects-runtime-locations",
                summary: "Register project runtime location",
                tag: "platform",
                tenant_scope: "tenant",
            };

            pub const DELETE: crate::SdkOperation = crate::SdkOperation {
                data_scope: "organization",
                deployment: "all",
                domain: "platform",
                key: "platform.projects.runtimeLocations.delete",
                method: "DELETE",
                operation_id: "projects.runtimeLocations.delete",
                path: "/app/v3/api/projects/{projectId}/runtime_locations/{runtimeLocationId}",
                path_param_names: &["projectId", "runtimeLocationId"],
                permission: Some("birdcoder.platform-projects-runtime-locations.delete"),
                public: false,
                resource: "birdcoder.platform-projects-runtime-locations",
                summary: "Delete project runtime location",
                tag: "platform",
                tenant_scope: "tenant",
            };

            pub const LIST: crate::SdkOperation = crate::SdkOperation {
                data_scope: "organization",
                deployment: "all",
                domain: "platform",
                key: "platform.projects.runtimeLocations.list",
                method: "GET",
                operation_id: "projects.runtimeLocations.list",
                path: "/app/v3/api/projects/{projectId}/runtime_locations",
                path_param_names: &["projectId"],
                permission: Some("birdcoder.platform-projects-runtime-locations.read"),
                public: false,
                resource: "birdcoder.platform-projects-runtime-locations",
                summary: "List project runtime locations",
                tag: "platform",
                tenant_scope: "tenant",
            };

            pub mod preferences {
                pub const LIST: crate::SdkOperation = crate::SdkOperation {
                    data_scope: "organization",
                    deployment: "all",
                    domain: "platform",
                    key: "platform.projects.runtimeLocations.preferences.list",
                    method: "GET",
                    operation_id: "projects.runtimeLocations.preferences.list",
                    path: "/app/v3/api/projects/{projectId}/runtime_location_preferences",
                    path_param_names: &["projectId"],
                    permission: Some("birdcoder.platform-projects-runtime-locations-preferences.read"),
                    public: false,
                    resource: "birdcoder.platform-projects-runtime-locations-preferences",
                    summary: "List project runtime-location preferences",
                    tag: "platform",
                    tenant_scope: "tenant",
                };

                pub const UPDATE: crate::SdkOperation = crate::SdkOperation {
                    data_scope: "organization",
                    deployment: "all",
                    domain: "platform",
                    key: "platform.projects.runtimeLocations.preferences.update",
                    method: "PUT",
                    operation_id: "projects.runtimeLocations.preferences.update",
                    path: "/app/v3/api/projects/{projectId}/runtime_location_preferences/{capability}",
                    path_param_names: &["projectId", "capability"],
                    permission: Some("birdcoder.platform-projects-runtime-locations-preferences.update"),
                    public: false,
                    resource: "birdcoder.platform-projects-runtime-locations-preferences",
                    summary: "Update project runtime-location preference",
                    tag: "platform",
                    tenant_scope: "tenant",
                };
            }

            pub const REBIND: crate::SdkOperation = crate::SdkOperation {
                data_scope: "organization",
                deployment: "all",
                domain: "platform",
                key: "platform.projects.runtimeLocations.rebind",
                method: "POST",
                operation_id: "projects.runtimeLocations.rebind",
                path: "/app/v3/api/projects/{projectId}/runtime_locations/{runtimeLocationId}/rebind",
                path_param_names: &["projectId", "runtimeLocationId"],
                permission: Some("birdcoder.platform-projects-runtime-locations.create"),
                public: false,
                resource: "birdcoder.platform-projects-runtime-locations",
                summary: "Rebind project runtime location",
                tag: "platform",
                tenant_scope: "tenant",
            };

            pub const REQUEST_VERIFICATION: crate::SdkOperation = crate::SdkOperation {
                data_scope: "organization",
                deployment: "all",
                domain: "platform",
                key: "platform.projects.runtimeLocations.requestVerification",
                method: "POST",
                operation_id: "projects.runtimeLocations.requestVerification",
                path: "/app/v3/api/projects/{projectId}/runtime_locations/{runtimeLocationId}/request_verification",
                path_param_names: &["projectId", "runtimeLocationId"],
                permission: Some("birdcoder.platform-projects-runtime-locations.create"),
                public: false,
                resource: "birdcoder.platform-projects-runtime-locations",
                summary: "Request project runtime-location verification",
                tag: "platform",
                tenant_scope: "tenant",
            };

            pub const RETRIEVE: crate::SdkOperation = crate::SdkOperation {
                data_scope: "organization",
                deployment: "all",
                domain: "platform",
                key: "platform.projects.runtimeLocations.retrieve",
                method: "GET",
                operation_id: "projects.runtimeLocations.retrieve",
                path: "/app/v3/api/projects/{projectId}/runtime_locations/{runtimeLocationId}",
                path_param_names: &["projectId", "runtimeLocationId"],
                permission: Some("birdcoder.platform-projects-runtime-locations.read"),
                public: false,
                resource: "birdcoder.platform-projects-runtime-locations",
                summary: "Get project runtime location",
                tag: "platform",
                tenant_scope: "tenant",
            };

            pub const UPDATE: crate::SdkOperation = crate::SdkOperation {
                data_scope: "organization",
                deployment: "all",
                domain: "platform",
                key: "platform.projects.runtimeLocations.update",
                method: "PATCH",
                operation_id: "projects.runtimeLocations.update",
                path: "/app/v3/api/projects/{projectId}/runtime_locations/{runtimeLocationId}",
                path_param_names: &["projectId", "runtimeLocationId"],
                permission: Some("birdcoder.platform-projects-runtime-locations.update"),
                public: false,
                resource: "birdcoder.platform-projects-runtime-locations",
                summary: "Update project runtime location",
                tag: "platform",
                tenant_scope: "tenant",
            };
        }

        pub const UPDATE: crate::SdkOperation = crate::SdkOperation {
            data_scope: "organization",
            deployment: "all",
            domain: "platform",
            key: "platform.projects.update",
            method: "PATCH",
            operation_id: "projects.update",
            path: "/app/v3/api/projects/{projectId}",
            path_param_names: &["projectId"],
            permission: Some("birdcoder.platform-projects.update"),
            public: false,
            resource: "birdcoder.platform-projects",
            summary: "Update project",
            tag: "platform",
            tenant_scope: "tenant",
        };

        pub mod workspace_binding {
            pub const DELETE: crate::SdkOperation = crate::SdkOperation {
                data_scope: "organization",
                deployment: "all",
                domain: "platform",
                key: "platform.projects.workspaceBinding.delete",
                method: "DELETE",
                operation_id: "projects.workspaceBinding.delete",
                path: "/app/v3/api/projects/{projectId}/workspace_binding",
                path_param_names: &["projectId"],
                permission: Some("birdcoder.platform-projects-workspace-binding.delete"),
                public: false,
                resource: "birdcoder.platform-projects-workspace-binding",
                summary: "Delete project workspace binding",
                tag: "platform",
                tenant_scope: "tenant",
            };

            pub const RETRIEVE: crate::SdkOperation = crate::SdkOperation {
                data_scope: "organization",
                deployment: "all",
                domain: "platform",
                key: "platform.projects.workspaceBinding.retrieve",
                method: "GET",
                operation_id: "projects.workspaceBinding.retrieve",
                path: "/app/v3/api/projects/{projectId}/workspace_binding",
                path_param_names: &["projectId"],
                permission: Some("birdcoder.platform-projects-workspace-binding.read"),
                public: false,
                resource: "birdcoder.platform-projects-workspace-binding",
                summary: "Get project workspace binding",
                tag: "platform",
                tenant_scope: "tenant",
            };

            pub const UPDATE: crate::SdkOperation = crate::SdkOperation {
                data_scope: "organization",
                deployment: "all",
                domain: "platform",
                key: "platform.projects.workspaceBinding.update",
                method: "PUT",
                operation_id: "projects.workspaceBinding.update",
                path: "/app/v3/api/projects/{projectId}/workspace_binding",
                path_param_names: &["projectId"],
                permission: Some("birdcoder.platform-projects-workspace-binding.update"),
                public: false,
                resource: "birdcoder.platform-projects-workspace-binding",
                summary: "Create or update project workspace binding",
                tag: "platform",
                tenant_scope: "tenant",
            };
        }
    }

    pub mod workspaces {
        pub const CREATE: crate::SdkOperation = crate::SdkOperation {
            data_scope: "organization",
            deployment: "all",
            domain: "platform",
            key: "platform.workspaces.create",
            method: "POST",
            operation_id: "workspaces.create",
            path: "/app/v3/api/workspaces",
            path_param_names: &[],
            permission: Some("birdcoder.platform-workspaces.create"),
            public: false,
            resource: "birdcoder.platform-workspaces",
            summary: "Create workspace",
            tag: "platform",
            tenant_scope: "tenant",
        };

        pub const DELETE: crate::SdkOperation = crate::SdkOperation {
            data_scope: "organization",
            deployment: "all",
            domain: "platform",
            key: "platform.workspaces.delete",
            method: "DELETE",
            operation_id: "workspaces.delete",
            path: "/app/v3/api/workspaces/{workspaceId}",
            path_param_names: &["workspaceId"],
            permission: Some("birdcoder.platform-workspaces.delete"),
            public: false,
            resource: "birdcoder.platform-workspaces",
            summary: "Delete workspace",
            tag: "platform",
            tenant_scope: "tenant",
        };

        pub const LIST: crate::SdkOperation = crate::SdkOperation {
            data_scope: "organization",
            deployment: "all",
            domain: "platform",
            key: "platform.workspaces.list",
            method: "GET",
            operation_id: "workspaces.list",
            path: "/app/v3/api/workspaces",
            path_param_names: &[],
            permission: Some("birdcoder.platform-workspaces.read"),
            public: false,
            resource: "birdcoder.platform-workspaces",
            summary: "List workspaces",
            tag: "platform",
            tenant_scope: "tenant",
        };

        pub const RETRIEVE: crate::SdkOperation = crate::SdkOperation {
            data_scope: "organization",
            deployment: "all",
            domain: "platform",
            key: "platform.workspaces.retrieve",
            method: "GET",
            operation_id: "workspaces.retrieve",
            path: "/app/v3/api/workspaces/{workspaceId}",
            path_param_names: &["workspaceId"],
            permission: Some("birdcoder.platform-workspaces.read"),
            public: false,
            resource: "birdcoder.platform-workspaces",
            summary: "Get workspace",
            tag: "platform",
            tenant_scope: "tenant",
        };

        pub const UPDATE: crate::SdkOperation = crate::SdkOperation {
            data_scope: "organization",
            deployment: "all",
            domain: "platform",
            key: "platform.workspaces.update",
            method: "PATCH",
            operation_id: "workspaces.update",
            path: "/app/v3/api/workspaces/{workspaceId}",
            path_param_names: &["workspaceId"],
            permission: Some("birdcoder.platform-workspaces.update"),
            public: false,
            resource: "birdcoder.platform-workspaces",
            summary: "Update workspace",
            tag: "platform",
            tenant_scope: "tenant",
        };
    }
}

pub mod system {
    pub mod descriptor {
        pub const RETRIEVE: crate::SdkOperation = crate::SdkOperation {
            data_scope: "platform",
            deployment: "all",
            domain: "system",
            key: "system.descriptor.retrieve",
            method: "GET",
            operation_id: "descriptor.retrieve",
            path: "/app/v3/api/system/descriptor",
            path_param_names: &[],
            permission: Some("birdcoder.system-descriptor.read"),
            public: false,
            resource: "birdcoder.system-descriptor",
            summary: "Get coding-server descriptor",
            tag: "system",
            tenant_scope: "tenant",
        };
    }

    pub mod health {
        pub const RETRIEVE: crate::SdkOperation = crate::SdkOperation {
            data_scope: "platform",
            deployment: "all",
            domain: "system",
            key: "system.health.retrieve",
            method: "GET",
            operation_id: "health.retrieve",
            path: "/app/v3/api/system/health",
            path_param_names: &[],
            permission: Some("birdcoder.system-health.read"),
            public: false,
            resource: "birdcoder.system-health",
            summary: "Get coding-server health",
            tag: "system",
            tenant_scope: "tenant",
        };
    }

    pub mod routes {
        pub const LIST: crate::SdkOperation = crate::SdkOperation {
            data_scope: "platform",
            deployment: "all",
            domain: "system",
            key: "system.routes.list",
            method: "GET",
            operation_id: "routes.list",
            path: "/app/v3/api/system/routes",
            path_param_names: &[],
            permission: Some("birdcoder.system-routes.read"),
            public: false,
            resource: "birdcoder.system-routes",
            summary: "List unified API routes",
            tag: "system",
            tenant_scope: "tenant",
        };
    }

    pub mod runtime {
        pub const RETRIEVE: crate::SdkOperation = crate::SdkOperation {
            data_scope: "platform",
            deployment: "all",
            domain: "system",
            key: "system.runtime.retrieve",
            method: "GET",
            operation_id: "runtime.retrieve",
            path: "/app/v3/api/system/runtime",
            path_param_names: &[],
            permission: Some("birdcoder.system-runtime.read"),
            public: false,
            resource: "birdcoder.system-runtime",
            summary: "Get runtime metadata",
            tag: "system",
            tenant_scope: "tenant",
        };
    }
}

pub const OPERATIONS: &[SdkOperation] = &[
    platform::projects::CREATE,
    platform::projects::DELETE,
    platform::projects::git::branches::CREATE,
    platform::projects::git::branch_switch::CREATE,
    platform::projects::git::commits::CREATE,
    platform::projects::git::diff::RETRIEVE,
    platform::projects::git::overview::RETRIEVE,
    platform::projects::git::pushes::CREATE,
    platform::projects::git::worktree_prune::CREATE,
    platform::projects::git::worktree_removals::CREATE,
    platform::projects::git::worktrees::CREATE,
    platform::projects::LIST,
    platform::projects::RETRIEVE,
    platform::projects::runtime_locations::CREATE,
    platform::projects::runtime_locations::DELETE,
    platform::projects::runtime_locations::LIST,
    platform::projects::runtime_locations::preferences::LIST,
    platform::projects::runtime_locations::preferences::UPDATE,
    platform::projects::runtime_locations::REBIND,
    platform::projects::runtime_locations::REQUEST_VERIFICATION,
    platform::projects::runtime_locations::RETRIEVE,
    platform::projects::runtime_locations::UPDATE,
    platform::projects::UPDATE,
    platform::projects::workspace_binding::DELETE,
    platform::projects::workspace_binding::RETRIEVE,
    platform::projects::workspace_binding::UPDATE,
    platform::workspaces::CREATE,
    platform::workspaces::DELETE,
    platform::workspaces::LIST,
    platform::workspaces::RETRIEVE,
    platform::workspaces::UPDATE,
    system::descriptor::RETRIEVE,
    system::health::RETRIEVE,
    system::routes::LIST,
    system::runtime::RETRIEVE,
];
