// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

export const BIRDCODER_APP_SDK_STANDARD_PROFILE = "sdkwork-v3" as const;
export const BIRDCODER_APP_SDK_API_PREFIX = "/app/v3/api" as const;
export const BIRDCODER_APP_SDK_PACKAGE_NAME = "@sdkwork/birdcoder-app-sdk" as const;

export type BirdcoderSdkQueryValue = boolean | number | string | null | undefined;

export interface BirdcoderSdkOperationDescriptor {
  dataScope: string;
  deployment: 'all' | 'local' | 'private' | 'saas';
  domain: string;
  key: string;
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  operationId: string;
  path: string;
  pathParamNames: readonly string[];
  permission?: string;
  public: boolean;
  resource: string;
  summary: string;
  tag: string;
  tenantScope: string;
}

export interface BirdCoderApiGatewaySummary {
  docsPath: string;
  liveOpenApiPath: string;
  openApiPath: string;
  routeCatalogPath: string;
  routeCount: number;
  routesBySurface: Record<string, unknown>;
  surfaces: Array<BirdCoderApiGatewaySurfaceSummary>;
}

export interface BirdCoderApiGatewaySurfaceSummary {
  authMode: "host" | "user" | "admin";
  basePath: string;
  description: string;
  name: "app" | "backend";
  routeCount: number;
}

export interface BirdCoderApiListMeta {
  page: number;
  pageSize: number;
  total: number;
  version: string;
}

export interface BirdCoderApiMeta {
  page?: number;
  pageSize?: number;
  total?: number;
  version: string;
}

export interface BirdCoderApiProblemDetails {
  code: string;
  message: string;
  detail?: string;
  retryable: boolean;
  fieldErrors?: Record<string, string>;
}

export interface BirdCoderApiRouteCatalogEntry {
  authMode: "host" | "user" | "admin";
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  surface: "app" | "backend";
  summary: string;
  openApiPath: string;
  operationId: string;
}

export interface BirdCoderApiRouteCatalogEntryListEnvelope {
  items: Array<BirdCoderApiRouteCatalogEntry>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderApprovalDecisionResult {
  approvalId: string;
  checkpointId: string;
  codingSessionId: string;
  decision: "approved" | "denied" | "blocked";
  decidedAt: string;
  operationId?: string;
  operationStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "rolled_back";
  reason?: string;
  runtimeId?: string;
  runtimeStatus: "initializing" | "ready" | "streaming" | "awaiting_tool" | "awaiting_approval" | "awaiting_user" | "completed" | "failed" | "terminated";
  turnId?: string;
}

export interface BirdCoderApprovalDecisionResultEnvelope {
  data: BirdCoderApprovalDecisionResult;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderAppTemplateSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  createdAt?: string;
  updatedAt: string;
  slug: string;
  name: string;
  description: string;
  icon?: string;
  author?: string;
  versionId: string;
  versionLabel: string;
  presetKey: string;
  category: string;
  tags: Array<string>;
  targetProfiles: Array<string>;
  downloads?: number;
  stars?: number;
  status: string;
}

export interface BirdCoderAppTemplateSummaryListEnvelope {
  items: Array<BirdCoderAppTemplateSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderAuthenticatedUserSummary {
  id: string;
  uuid: string;
  tenantId?: string;
  organizationId?: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  email: string;
  avatarUrl?: string;
}

export interface BirdCoderBooleanSuccessEnvelope {
  data: BirdCoderBooleanSuccessResult;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderBooleanSuccessResult {
  success: boolean;
}

export interface BirdCoderCodeEngineModelConfig {
  schemaVersion: number;
  source: string;
  version: string;
  updatedAt: string;
  engines: Record<string, BirdCoderCodeEngineModelConfigEngine>;
}

export interface BirdCoderCodeEngineModelConfigCustomModel {
  id: string;
  label: string;
}

export interface BirdCoderCodeEngineModelConfigEngine {
  engineId: "codex" | "claude-code" | "gemini" | "opencode";
  defaultModelId: string;
  selectedModelId: string;
  customModels: Array<BirdCoderCodeEngineModelConfigCustomModel>;
  models: Array<BirdCoderModelCatalogEntry>;
}

export interface BirdCoderCodeEngineModelConfigEnvelope {
  data: BirdCoderCodeEngineModelConfig;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderCodeEngineModelConfigSyncResult {
  action: "noop" | "overwrite-local" | "push-local";
  authoritativeSource: "equal" | "local" | "server";
  config: BirdCoderCodeEngineModelConfig;
  shouldWriteLocal: boolean;
  shouldWriteServer: boolean;
}

export interface BirdCoderCodeEngineModelConfigSyncResultEnvelope {
  data: BirdCoderCodeEngineModelConfigSyncResult;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderCodingServerDescriptor {
  apiVersion: string;
  gateway: BirdCoderApiGatewaySummary;
  hostMode: "web" | "desktop" | "server";
  moduleId: "coding-server";
  openApiPath: string;
  surfaces: Array<"app" | "backend">;
}

export interface BirdCoderCodingServerDescriptorEnvelope {
  data: BirdCoderCodingServerDescriptor;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderCodingSessionArtifact {
  id: string;
  codingSessionId: string;
  turnId?: string;
  kind: "diff" | "patch" | "file" | "command-log" | "todo-list" | "pty-transcript" | "structured-output" | "build-evidence" | "preview-evidence" | "simulator-evidence" | "test-evidence" | "release-evidence" | "diagnostic-bundle";
  status?: "draft" | "sealed" | "archived";
  title: string;
  blobRef?: string;
  metadata?: Record<string, unknown>;
  createdAt: string;
}

export interface BirdCoderCodingSessionArtifactListEnvelope {
  items: Array<BirdCoderCodingSessionArtifact>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderCodingSessionCheckpoint {
  id: string;
  codingSessionId: string;
  runtimeId?: string;
  checkpointKind: "resume" | "approval" | "handoff" | "snapshot";
  resumable: boolean;
  state: Record<string, unknown>;
  createdAt: string;
}

export interface BirdCoderCodingSessionCheckpointListEnvelope {
  items: Array<BirdCoderCodingSessionCheckpoint>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderCodingSessionEvent {
  id: string;
  codingSessionId: string;
  turnId?: string;
  runtimeId?: string;
  kind: "session.started" | "turn.started" | "message.delta" | "message.completed" | "message.deleted" | "message.edited" | "tool.call.requested" | "tool.call.progress" | "tool.call.completed" | "artifact.upserted" | "approval.required" | "operation.updated" | "turn.completed" | "turn.failed";
  sequence: string;
  payload: Record<string, unknown>;
  createdAt: string;
}

export interface BirdCoderCodingSessionEventListEnvelope {
  items: Array<BirdCoderCodingSessionEvent>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderCodingSessionSummary {
  id: string;
  workspaceId: string;
  projectId: string;
  title: string;
  status: "draft" | "active" | "paused" | "completed" | "archived";
  hostMode: "web" | "desktop" | "server";
  engineId: "codex" | "claude-code" | "gemini" | "opencode";
  modelId: string;
  nativeSessionId?: string;
  createdAt: string;
  updatedAt: string;
  lastTurnAt?: string;
  sortTimestamp?: string;
  transcriptUpdatedAt?: string | unknown;
}

export interface BirdCoderCodingSessionSummaryEnvelope {
  data: BirdCoderCodingSessionSummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderCodingSessionSummaryListEnvelope {
  items: Array<BirdCoderCodingSessionSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderCodingSessionTurn {
  id: string;
  codingSessionId: string;
  runtimeId?: string;
  requestKind: "chat" | "plan" | "tool" | "review" | "apply";
  status: "queued" | "running" | "completed" | "failed" | "cancelled";
  inputSummary: string;
  startedAt?: string;
  completedAt?: string;
}

export interface BirdCoderCodingSessionTurnCurrentFileContext {
  path: string;
  content?: string;
  language?: string;
}

export interface BirdCoderCodingSessionTurnEnvelope {
  data: BirdCoderCodingSessionTurn;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderCodingSessionTurnIdeContext {
  workspaceId?: string;
  projectId?: string;
  sessionId?: string;
  currentFile?: BirdCoderCodingSessionTurnCurrentFileContext;
}

export interface BirdCoderCodingSessionTurnOptions {
  temperature?: number;
  topP?: number;
  maxTokens?: number;
}

export interface BirdCoderCommerceMembershipBenefitSummary {
  id: string;
  name: string;
  benefitKey?: string;
  type?: string;
  description?: string;
  icon?: string;
  claimed: boolean;
  usageLimit?: string;
  usedCount?: string;
}

export interface BirdCoderCommerceMembershipCurrentEnvelope {
  data: BirdCoderCommerceMembershipCurrentSummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderCommerceMembershipCurrentSummary {
  tenantId?: string;
  organizationId?: string;
  ownerUserId: string;
  planId?: string | unknown;
  planName: string;
  status: string;
  startedAt?: string | unknown;
  expiresAt?: string | unknown;
  remainingDays?: string;
  totalDays?: string;
  totalSpent: string;
  points: string;
  growthValue: string;
  upgradeGrowthValue: string;
  benefits: Array<BirdCoderCommerceMembershipBenefitSummary>;
}

export interface BirdCoderCommerceMembershipPackageGroupSummary {
  id: string;
  name: string;
  description?: string;
  sortWeight: string;
  packages: Array<BirdCoderCommerceMembershipPackageSummary>;
}

export interface BirdCoderCommerceMembershipPackageGroupSummaryListEnvelope {
  items: Array<BirdCoderCommerceMembershipPackageGroupSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderCommerceMembershipPackageSummary {
  id: string;
  name: string;
  description?: string;
  price: string;
  originalPrice?: string;
  pointAmount: string;
  durationDays: string;
  planName?: string;
  sortWeight: string;
  recommended: boolean;
  tags: Array<string>;
}

export interface BirdCoderCommitProjectGitChangesRequest {
  message: string;
}

export interface BirdCoderCoreHealthSummary {
  status: string;
}

export interface BirdCoderCoreHealthSummaryEnvelope {
  data: BirdCoderCoreHealthSummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderCoreRuntimeSummary {
  host: string;
  port: number;
  configFileName: string;
}

export interface BirdCoderCoreRuntimeSummaryEnvelope {
  data: BirdCoderCoreRuntimeSummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderCreateCodingSessionRequest {
  workspaceId: string;
  projectId: string;
  title?: string;
  hostMode?: "web" | "desktop" | "server";
  engineId: "codex" | "claude-code" | "gemini" | "opencode";
  modelId: string;
}

export interface BirdCoderCreateCodingSessionTurnRequest {
  runtimeId?: string;
  engineId?: string;
  modelId?: string;
  requestKind: "chat" | "plan" | "tool" | "review" | "apply";
  inputSummary: string;
  stream?: boolean;
  ideContext?: BirdCoderCodingSessionTurnIdeContext;
  options?: BirdCoderCodingSessionTurnOptions;
}

export interface BirdCoderCreateProjectGitBranchRequest {
  branchName: string;
}

export interface BirdCoderCreateProjectGitWorktreeRequest {
  branchName: string;
  path: string;
}

export interface BirdCoderCreateProjectRequest {
  description?: string;
  name: string;
  workspaceUuid?: string;
  tenantId?: string;
  organizationId?: string;
  dataScope?: "DEFAULT" | "PRIVATE" | "ORGANIZATION" | "TENANT" | "PUBLIC";
  userId?: string;
  parentId?: string;
  parentUuid?: string;
  parentMetadata?: Record<string, unknown>;
  code?: string;
  title?: string;
  ownerId?: string;
  leaderId?: string;
  createdByUserId?: string;
  author?: string;
  type?: string;
  rootPath?: string;
  sitePath?: string;
  domainPrefix?: string;
  fileId?: string;
  conversationId?: string;
  startTime?: string;
  endTime?: string;
  budgetAmount?: string;
  coverImage?: Record<string, unknown>;
  isTemplate?: boolean;
  appTemplateVersionId?: string;
  templatePresetKey?: string;
  status?: "active" | "archived";
  workspaceId: string;
}

export interface BirdCoderCreateWorkspaceRequest {
  description?: string;
  name: string;
  tenantId?: string;
  organizationId?: string;
  dataScope?: "DEFAULT" | "PRIVATE" | "ORGANIZATION" | "TENANT" | "PUBLIC";
  code?: string;
  title?: string;
  ownerId?: string;
  leaderId?: string;
  createdByUserId?: string;
  icon?: string;
  color?: string;
  type?: string;
  startTime?: string;
  endTime?: string;
  maxMembers?: number;
  currentMembers?: number;
  memberCount?: number;
  maxStorage?: string;
  usedStorage?: string;
  settings?: Record<string, unknown>;
  isPublic?: boolean;
  isTemplate?: boolean;
}

export interface BirdCoderDeleteCodingSessionMessageResult {
  id: string;
  codingSessionId: string;
}

export interface BirdCoderDeleteCodingSessionMessageResultEnvelope {
  data: BirdCoderDeleteCodingSessionMessageResult;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderDeletedResourceEnvelope {
  data: BirdCoderDeletedResourceResult;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderDeletedResourceResult {
  id: string;
}

export interface BirdCoderDeploymentRecordSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  createdAt?: string;
  updatedAt?: string;
  projectId: string;
  targetId: string;
  releaseRecordId?: string;
  status: "planned" | "running" | "succeeded" | "failed" | "rolled_back";
  endpointUrl?: string;
  startedAt?: string;
  completedAt?: string;
}

export interface BirdCoderDeploymentRecordSummaryListEnvelope {
  items: Array<BirdCoderDeploymentRecordSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderDeploymentTargetSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  createdAt?: string;
  updatedAt?: string;
  projectId: string;
  name: string;
  environmentKey: string;
  runtime: string;
  status: "active" | "archived";
}

export interface BirdCoderEditCodingSessionMessageRequest {
  content: string;
}

export interface BirdCoderEditCodingSessionMessageResult {
  id: string;
  codingSessionId: string;
  content: string;
}

export interface BirdCoderEditCodingSessionMessageResultEnvelope {
  data: BirdCoderEditCodingSessionMessageResult;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderEngineAccessLane {
  laneId: string;
  label: string;
  strategyKind: "rust-native" | "grpc-bridge" | "cli-spawn" | "remote-control" | "openapi-proxy";
  runtimeOwner: "rust-server" | "typescript-bridge" | "external-service";
  bridgeProtocol: "direct" | "grpc" | "stdio" | "http";
  transportKind: "cli-jsonl" | "sdk-stream" | "remote-control-http" | "openapi-http";
  status: "ready" | "planned";
  enabledByDefault: boolean;
  hostModes: Array<"web" | "desktop" | "server">;
  description: string;
}

export interface BirdCoderEngineAccessPlan {
  primaryLaneId: string;
  fallbackLaneIds: Array<string>;
  lanes: Array<BirdCoderEngineAccessLane>;
}

export interface BirdCoderEngineCapabilityMatrix {
  chat: boolean;
  streaming: boolean;
  structuredOutput: boolean;
  toolCalls: boolean;
  planning: boolean;
  patchArtifacts: boolean;
  commandArtifacts: boolean;
  todoArtifacts: boolean;
  ptyArtifacts: boolean;
  previewArtifacts: boolean;
  testArtifacts: boolean;
  approvalCheckpoints: boolean;
  sessionResume: boolean;
  remoteBridge: boolean;
  mcp: boolean;
}

export interface BirdCoderEngineCapabilityMatrixEnvelope {
  data: BirdCoderEngineCapabilityMatrix;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderEngineDescriptor {
  id: string;
  uuid: string;
  tenantId?: string;
  organizationId?: string;
  createdAt: string;
  updatedAt: string;
  engineKey: "codex" | "claude-code" | "gemini" | "opencode";
  displayName: string;
  vendor: string;
  installationKind: "external-cli";
  defaultModelId: string;
  homepage?: string;
  supportedHostModes: Array<"web" | "desktop" | "server">;
  transportKinds: Array<"cli-jsonl" | "sdk-stream" | "remote-control-http" | "openapi-http">;
  capabilityMatrix: BirdCoderEngineCapabilityMatrix;
  status: "active" | "preview" | "deprecated" | "disabled";
  accessPlan?: BirdCoderEngineAccessPlan;
  officialIntegration?: BirdCoderEngineOfficialIntegration;
}

export interface BirdCoderEngineDescriptorListEnvelope {
  items: Array<BirdCoderEngineDescriptor>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderEngineOfficialEntry {
  packageName: string;
  packageVersion?: string;
  sdkPath?: string | unknown;
  cliPackageName?: string | unknown;
  sourceMirrorPath?: string | unknown;
  supplementalLanes?: Array<string>;
}

export interface BirdCoderEngineOfficialIntegration {
  integrationClass: "official-sdk" | "official-protocol" | "source-derived";
  runtimeMode: "sdk" | "headless" | "remote-control" | "protocol-fallback";
  officialEntry: BirdCoderEngineOfficialEntry;
  notes?: string;
}

export interface BirdCoderForkCodingSessionRequest {
  title?: string;
}

export interface BirdCoderGitBranchSummary {
  ahead: number;
  behind: number;
  isCurrent: boolean;
  kind: string;
  name: string;
  upstreamName?: string;
}

export interface BirdCoderGitStatusCounts {
  conflicted: number;
  deleted: number;
  modified: number;
  staged: number;
  untracked: number;
}

export interface BirdCoderGitWorktreeSummary {
  branch?: string;
  head?: string;
  id: string;
  isCurrent: boolean;
  isDetached: boolean;
  isLocked: boolean;
  isPrunable: boolean;
  label: string;
  lockedReason?: string;
  path: string;
  prunableReason?: string;
}

export interface BirdCoderIamCreateSessionRequest {
  account?: string;
  appVersion?: string;
  code?: string;
  deviceId?: string;
  deviceName?: string;
  deviceType?: "android" | "desktop" | "ios" | "web";
  email?: string;
  grantType?: "password" | "email_code" | "phone_code" | "session_bridge";
  loginMethod?: "emailCode" | "password" | "phoneCode" | "sessionBridge";
  password?: string;
  phone?: string;
  username?: string;
}

export interface BirdCoderIamOAuthAuthorizationEnvelope {
  data: BirdCoderIamOAuthAuthorizationSummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderIamOAuthAuthorizationSummary {
  authUrl: string;
}

export interface BirdCoderIamOAuthSessionCreateRequest {
  code: string;
  deviceId?: string;
  deviceType?: "android" | "desktop" | "ios" | "web";
  provider: string;
  state?: string;
}

export interface BirdCoderIamPasswordResetCreateRequest {
  account: string;
  code: string;
  confirmPassword?: string;
  newPassword: string;
}

export interface BirdCoderIamPasswordResetRequestCreateRequest {
  account: string;
  channel: "EMAIL" | "SMS";
}

export interface BirdCoderIamQrAuthSessionCreateRequest {
  purpose: "login" | "register";
  redirectUri?: string;
}

export interface BirdCoderIamQrAuthSessionEnvelope {
  data: BirdCoderIamQrAuthSessionSummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderIamQrAuthSessionPasswordRequest {
  password: string;
  username: string;
}

export interface BirdCoderIamQrAuthSessionScanRequest {
  scanSource?: string;
}

export interface BirdCoderIamQrAuthSessionSummary {
  expiresAt?: string;
  qrContent?: string;
  qrUrl?: string;
  sessionKey: string;
  status: "pending" | "scanned" | "confirmed" | "expired";
}

export interface BirdCoderIamRefreshSessionRequest {
  refreshToken: string;
}

export interface BirdCoderIamRegistrationCreateRequest {
  channel?: "EMAIL" | "PHONE";
  confirmPassword?: string;
  email?: string;
  name?: string;
  password?: string;
  phone?: string;
  username?: string;
  verificationCode?: string;
}

export interface BirdCoderIamRuntimeSettingsEnvelope {
  data: BirdCoderIamRuntimeSettingsSummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderIamRuntimeSettingsSummary {
  leftRailMode: "auto" | "highlights-only" | "qr-only";
  loginMethods: Array<"emailCode" | "password" | "phoneCode" | "sessionBridge">;
  oauthLoginEnabled: boolean;
  oauthProviders: Array<string>;
  qrLoginEnabled: boolean;
  qrLoginType: "web" | "official" | "mini";
  recoveryMethods: Array<"email" | "phone">;
  registerMethods: Array<"email" | "phone">;
  verificationPolicy: BirdCoderIamVerificationPolicySummary;
}

export interface BirdCoderIamSessionEnvelope {
  data: BirdCoderIamSessionSummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderIamSessionSummary {
  accessToken: string;
  authToken: string;
  context?: Record<string, unknown>;
  expiresAt?: string;
  refreshToken?: string;
  sessionId?: string;
  user?: BirdCoderAuthenticatedUserSummary;
}

export interface BirdCoderIamUpdateCurrentSessionRequest {
  deviceId?: string;
  deviceName?: string;
  trusted?: boolean;
}

export interface BirdCoderIamUserProfileEnvelope {
  data: BirdCoderIamUserProfileSummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderIamUserProfileSummary {
  uuid: string;
  tenantId?: string;
  organizationId?: string;
  createdAt: string;
  updatedAt: string;
  avatarUrl?: string;
  bio: string;
  company: string;
  displayName: string;
  email: string;
  userId: string;
  location: string;
  website: string;
}

export interface BirdCoderIamVerificationCodeCreateRequest {
  scene: "LOGIN" | "REGISTER" | "RESET_PASSWORD";
  target: string;
  verifyType: "EMAIL" | "PHONE";
}

export interface BirdCoderIamVerificationCodeVerifyRequest {
  code: string;
  scene: "LOGIN" | "REGISTER" | "RESET_PASSWORD";
  target: string;
  verifyType: "EMAIL" | "PHONE";
}

export interface BirdCoderIamVerificationPolicyEnvelope {
  data: BirdCoderIamVerificationPolicySummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderIamVerificationPolicySummary {
  emailCodeLoginEnabled: boolean;
  emailRegistrationVerificationRequired: boolean;
  phoneCodeLoginEnabled: boolean;
  phoneRegistrationVerificationRequired: boolean;
}

export interface BirdCoderInstallSkillPackageRequest {
  scopeId: string;
  scopeType: "workspace" | "project";
}

export interface BirdCoderModelCatalogEntry {
  id: string;
  uuid: string;
  tenantId?: string;
  organizationId?: string;
  createdAt: string;
  updatedAt: string;
  engineKey: "codex" | "claude-code" | "gemini" | "opencode";
  modelId: string;
  displayName: string;
  providerId?: string;
  status: "active" | "preview" | "deprecated" | "disabled";
  defaultForEngine: boolean;
  transportKinds: Array<"cli-jsonl" | "sdk-stream" | "remote-control-http" | "openapi-http">;
  capabilityMatrix: Record<string, unknown>;
}

export interface BirdCoderModelCatalogEntryListEnvelope {
  items: Array<BirdCoderModelCatalogEntry>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderNativeSessionCommand {
  command: string;
  status: "running" | "success" | "error";
  output?: string;
  kind?: "approval" | "command" | "file_change" | "task" | "tool" | "user_question";
  toolName?: string;
  toolCallId?: string;
  runtimeStatus?: "initializing" | "ready" | "streaming" | "awaiting_tool" | "awaiting_approval" | "awaiting_user" | "completed" | "failed" | "terminated";
  requiresApproval?: boolean;
  requiresReply?: boolean;
}

export interface BirdCoderNativeSessionDetail {
  summary: BirdCoderNativeSessionSummary;
  messages: Array<BirdCoderNativeSessionMessage>;
}

export interface BirdCoderNativeSessionDetailEnvelope {
  data: BirdCoderNativeSessionDetail;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderNativeSessionMessage {
  id: string;
  codingSessionId: string;
  turnId?: string;
  role: "user" | "assistant" | "system" | "tool" | "reviewer" | "planner";
  content: string;
  commands?: Array<BirdCoderNativeSessionCommand>;
  tool_calls?: Array<Record<string, unknown>>;
  tool_call_id?: string;
  fileChanges?: Array<Record<string, unknown>>;
  taskProgress?: Record<string, unknown>;
  metadata?: Record<string, string>;
  createdAt: string;
}

export interface BirdCoderNativeSessionProviderSummary {
  engineId: "codex" | "claude-code" | "gemini" | "opencode";
  displayName: string;
  nativeSessionIdPrefix: string;
  transportKinds: Array<"cli-jsonl" | "sdk-stream" | "remote-control-http" | "openapi-http">;
  discoveryMode: "explicit-only" | "passive-global";
}

export interface BirdCoderNativeSessionProviderSummaryListEnvelope {
  items: Array<BirdCoderNativeSessionProviderSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderNativeSessionSummary {
  id: string;
  workspaceId: string;
  projectId: string;
  title: string;
  status: "draft" | "active" | "paused" | "completed" | "archived";
  hostMode: "web" | "desktop" | "server";
  engineId: "codex" | "claude-code" | "gemini" | "opencode";
  modelId?: string;
  nativeSessionId?: string;
  createdAt: string;
  updatedAt: string;
  lastTurnAt?: string;
  sortTimestamp: string;
  transcriptUpdatedAt?: string | unknown;
  kind: "coding";
  nativeCwd?: string | unknown;
}

export interface BirdCoderNativeSessionSummaryListEnvelope {
  items: Array<BirdCoderNativeSessionSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderOperationDescriptor {
  operationId: string;
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "rolled_back";
  artifactRefs: Array<string>;
  streamUrl?: string;
  streamKind?: "sse" | "websocket";
}

export interface BirdCoderOperationDescriptorEnvelope {
  data: BirdCoderOperationDescriptor;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderProblemEnvelope {
  data: BirdCoderApiProblemDetails;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderProjectCollaboratorSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  projectId: string;
  workspaceId: string;
  userId: string;
  userEmail?: string;
  userDisplayName?: string;
  userAvatarUrl?: string;
  teamId?: string;
  role: "owner" | "admin" | "member" | "viewer";
  status: "invited" | "active" | "suspended" | "removed";
  createdByUserId?: string;
  grantedByUserId?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface BirdCoderProjectCollaboratorSummaryEnvelope {
  data: BirdCoderProjectCollaboratorSummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderProjectCollaboratorSummaryListEnvelope {
  items: Array<BirdCoderProjectCollaboratorSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderProjectDocumentSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  createdAt?: string;
  updatedAt?: string;
  projectId: string;
  documentKind: "prd" | "architecture" | "step" | "release" | "test-plan" | "custom";
  title: string;
  slug: string;
  bodyRef?: string;
  status: "draft" | "active" | "archived";
}

export interface BirdCoderProjectDocumentSummaryListEnvelope {
  items: Array<BirdCoderProjectDocumentSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderProjectGitOverview {
  branches: Array<BirdCoderGitBranchSummary>;
  currentBranch?: string;
  currentRevision?: string;
  currentWorktreePath?: string;
  detachedHead: boolean;
  repositoryRootPath?: string;
  status: "ready" | "not_repository";
  statusCounts: BirdCoderGitStatusCounts;
  worktrees: Array<BirdCoderGitWorktreeSummary>;
}

export interface BirdCoderProjectGitOverviewEnvelope {
  data: BirdCoderProjectGitOverview;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderProjectPublishResult {
  deployment: BirdCoderDeploymentRecordSummary;
  release: BirdCoderReleaseSummary;
  target: BirdCoderDeploymentTargetSummary;
}

export interface BirdCoderProjectPublishResultEnvelope {
  data: BirdCoderProjectPublishResult;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderProjectSummary {
  createdAt: string;
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  dataScope?: "DEFAULT" | "PRIVATE" | "ORGANIZATION" | "TENANT" | "PUBLIC";
  workspaceId: string;
  workspaceUuid?: string;
  userId?: string;
  parentId?: string;
  parentUuid?: string;
  parentMetadata?: Record<string, unknown>;
  code?: string;
  title?: string;
  name: string;
  description?: string;
  rootPath?: string;
  sitePath?: string;
  domainPrefix?: string;
  ownerId?: string;
  leaderId?: string;
  createdByUserId?: string;
  author?: string;
  fileId?: string;
  conversationId?: string;
  type?: string;
  startTime?: string;
  endTime?: string;
  budgetAmount?: string;
  coverImage?: Record<string, unknown>;
  isTemplate?: boolean;
  collaboratorCount?: number;
  status: "active" | "archived";
  updatedAt: string;
  viewerRole?: "owner" | "admin" | "member" | "viewer";
}

export interface BirdCoderProjectSummaryEnvelope {
  data: BirdCoderProjectSummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderProjectSummaryListEnvelope {
  items: Array<BirdCoderProjectSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderPublishProjectRequest {
  endpointUrl?: string;
  environmentKey?: string;
  releaseKind?: string;
  releaseVersion?: string;
  rolloutStage?: string;
  runtime?: string;
  targetId?: string;
  targetName?: string;
}

export interface BirdCoderPushProjectGitBranchRequest {
  branchName?: string;
  remoteName?: string;
}

export interface BirdCoderReleaseSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  createdAt?: string;
  updatedAt?: string;
  releaseVersion: string;
  releaseKind: string;
  rolloutStage: string;
  manifest?: Record<string, unknown>;
  status: string;
}

export interface BirdCoderRemoveProjectGitWorktreeRequest {
  force?: boolean;
  path: string;
}

export interface BirdCoderSkillCatalogEntrySummary {
  id: string;
  packageId: string;
  slug: string;
  name: string;
  description: string;
  icon?: string;
  author?: string;
  versionId: string;
  versionLabel: string;
  installCount?: string;
  longDescription?: string;
  tags: Array<string>;
  license?: string;
  repositoryUrl?: string;
  lastUpdated?: string;
  readme?: string;
  capabilityKeys: Array<string>;
  installed: boolean;
}

export interface BirdCoderSkillInstallationSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  createdAt?: string;
  updatedAt?: string;
  packageId: string;
  scopeId: string;
  scopeType: "workspace" | "project";
  status: string;
  versionId: string;
  installedAt: string;
}

export interface BirdCoderSkillInstallationSummaryEnvelope {
  data: BirdCoderSkillInstallationSummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderSkillPackageSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  createdAt?: string;
  updatedAt?: string;
  slug: string;
  name: string;
  description: string;
  icon?: string;
  author?: string;
  versionId: string;
  versionLabel: string;
  installCount?: string;
  longDescription?: string;
  sourceUri?: string;
  installed: boolean;
  skills: Array<BirdCoderSkillCatalogEntrySummary>;
}

export interface BirdCoderSkillPackageSummaryListEnvelope {
  items: Array<BirdCoderSkillPackageSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderSubmitApprovalDecisionRequest {
  decision: "approved" | "denied" | "blocked";
  reason?: string;
}

export interface BirdCoderSubmitUserQuestionAnswerRequest {
  answer?: string;
  optionId?: string;
  optionLabel?: string;
  rejected?: boolean;
}

export interface BirdCoderSwitchProjectGitBranchRequest {
  branchName: string;
}

export interface BirdCoderSyncCodeEngineModelConfigRequest {
  localConfig: BirdCoderCodeEngineModelConfig;
}

export interface BirdCoderTeamSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  createdAt?: string;
  updatedAt?: string;
  workspaceId: string;
  code?: string;
  title?: string;
  name: string;
  description?: string;
  ownerId?: string;
  leaderId?: string;
  createdByUserId?: string;
  metadata?: Record<string, unknown>;
  status: "active" | "archived";
}

export interface BirdCoderTeamSummaryListEnvelope {
  items: Array<BirdCoderTeamSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderUpdateCodingSessionRequest {
  title?: string;
  status?: "draft" | "active" | "paused" | "completed" | "archived";
  hostMode?: "web" | "desktop" | "server";
}

export interface BirdCoderUpdateCurrentUserProfileRequest {
  avatarUrl?: string;
  bio?: string;
  company?: string;
  displayName?: string;
  location?: string;
  website?: string;
}

export interface BirdCoderUpdateProjectRequest {
  description?: string;
  dataScope?: "DEFAULT" | "PRIVATE" | "ORGANIZATION" | "TENANT" | "PUBLIC";
  userId?: string;
  parentId?: string;
  parentUuid?: string;
  parentMetadata?: Record<string, unknown>;
  code?: string;
  title?: string;
  name?: string;
  ownerId?: string;
  leaderId?: string;
  createdByUserId?: string;
  author?: string;
  type?: string;
  rootPath?: string;
  sitePath?: string;
  domainPrefix?: string;
  fileId?: string;
  conversationId?: string;
  startTime?: string;
  endTime?: string;
  budgetAmount?: string;
  coverImage?: Record<string, unknown>;
  isTemplate?: boolean;
  status?: "active" | "archived";
}

export interface BirdCoderUpdateWorkspaceRequest {
  description?: string;
  dataScope?: "DEFAULT" | "PRIVATE" | "ORGANIZATION" | "TENANT" | "PUBLIC";
  code?: string;
  title?: string;
  name?: string;
  ownerId?: string;
  leaderId?: string;
  createdByUserId?: string;
  icon?: string;
  color?: string;
  type?: string;
  startTime?: string;
  endTime?: string;
  maxMembers?: number;
  currentMembers?: number;
  memberCount?: number;
  maxStorage?: string;
  usedStorage?: string;
  settings?: Record<string, unknown>;
  isPublic?: boolean;
  isTemplate?: boolean;
  status?: "active" | "archived";
}

export interface BirdCoderUpsertProjectCollaboratorRequest {
  userId?: string;
  email?: string;
  teamId?: string;
  role?: "owner" | "admin" | "member" | "viewer";
  status?: "invited" | "active" | "suspended" | "removed";
  createdByUserId?: string;
  grantedByUserId?: string;
}

export interface BirdCoderUpsertWorkspaceMemberRequest {
  userId?: string;
  email?: string;
  teamId?: string;
  role?: "owner" | "admin" | "member" | "viewer";
  status?: "invited" | "active" | "suspended" | "removed";
  createdByUserId?: string;
  grantedByUserId?: string;
}

export interface BirdCoderUserQuestionAnswerResult {
  questionId: string;
  codingSessionId: string;
  answer?: string;
  answeredAt: string;
  optionId?: string;
  optionLabel?: string;
  rejected: boolean;
  runtimeId?: string;
  runtimeStatus: "initializing" | "ready" | "streaming" | "awaiting_tool" | "awaiting_approval" | "awaiting_user" | "completed" | "failed" | "terminated";
  turnId?: string;
}

export interface BirdCoderUserQuestionAnswerResultEnvelope {
  data: BirdCoderUserQuestionAnswerResult;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderWorkspaceMemberSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  workspaceId: string;
  userId: string;
  userEmail?: string;
  userDisplayName?: string;
  userAvatarUrl?: string;
  teamId?: string;
  role: "owner" | "admin" | "member" | "viewer";
  status: "invited" | "active" | "suspended" | "removed";
  createdByUserId?: string;
  grantedByUserId?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface BirdCoderWorkspaceMemberSummaryEnvelope {
  data: BirdCoderWorkspaceMemberSummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderWorkspaceMemberSummaryListEnvelope {
  items: Array<BirdCoderWorkspaceMemberSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderWorkspaceSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  dataScope?: "DEFAULT" | "PRIVATE" | "ORGANIZATION" | "TENANT" | "PUBLIC";
  code?: string;
  title?: string;
  name: string;
  description?: string;
  icon?: string;
  color?: string;
  ownerId?: string;
  leaderId?: string;
  createdByUserId?: string;
  type?: string;
  startTime?: string;
  endTime?: string;
  maxMembers?: number;
  currentMembers?: number;
  memberCount?: number;
  maxStorage?: string;
  usedStorage?: string;
  settings?: Record<string, unknown>;
  isPublic?: boolean;
  isTemplate?: boolean;
  status: "active" | "archived";
  viewerRole?: "owner" | "admin" | "member" | "viewer";
}

export interface BirdCoderWorkspaceSummaryEnvelope {
  data: BirdCoderWorkspaceSummary;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderWorkspaceSummaryListEnvelope {
  items: Array<BirdCoderWorkspaceSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface AuthOauthAuthorizationUrlsRetrieveQuery extends Record<string, BirdcoderSdkQueryValue> {
  provider: string;
  redirectUri: string;
  scope?: string;
  state?: string;
}

export interface CollaborationWorkspaceTeamsListQuery extends Record<string, BirdcoderSdkQueryValue> {
  userId?: string;
  workspaceId?: string;
}

export interface IamWorkspacesMembersListPathParams {
  workspaceId: string;
}

export interface IamWorkspacesMembersUpsertPathParams {
  workspaceId: string;
}

export interface IntelligenceApprovalsDecisionsCreatePathParams {
  approvalId: string;
}

export interface IntelligenceCodingSessionsArtifactsListPathParams {
  id: string;
}

export interface IntelligenceCodingSessionsCheckpointsListPathParams {
  id: string;
}

export interface IntelligenceCodingSessionsDeletePathParams {
  id: string;
}

export interface IntelligenceCodingSessionsEventsListPathParams {
  id: string;
}

export interface IntelligenceCodingSessionsForksCreatePathParams {
  id: string;
}

export interface IntelligenceCodingSessionsListQuery extends Record<string, BirdcoderSdkQueryValue> {
  workspaceId?: string;
  projectId?: string;
  engineId?: "codex" | "claude-code" | "gemini" | "opencode";
  limit?: number;
  offset?: number;
}

export interface IntelligenceCodingSessionsMessagesDeletePathParams {
  id: string;
  messageId: string;
}

export interface IntelligenceCodingSessionsMessagesUpdatePathParams {
  id: string;
  messageId: string;
}

export interface IntelligenceCodingSessionsRetrievePathParams {
  id: string;
}

export interface IntelligenceCodingSessionsTurnsCreatePathParams {
  id: string;
}

export interface IntelligenceCodingSessionsUpdatePathParams {
  id: string;
}

export interface IntelligenceQuestionsAnswersCreatePathParams {
  questionId: string;
}

export interface OpenPlatformQrAuthSessionsPasswordsCreatePathParams {
  sessionKey: string;
}

export interface OpenPlatformQrAuthSessionsRetrievePathParams {
  sessionKey: string;
}

export interface OpenPlatformQrAuthSessionsScansCreatePathParams {
  sessionKey: string;
}

export interface PlatformProjectsCollaboratorsListPathParams {
  projectId: string;
}

export interface PlatformProjectsCollaboratorsUpsertPathParams {
  projectId: string;
}

export interface PlatformProjectsDeletePathParams {
  projectId: string;
}

export interface PlatformProjectsGitBranchesCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsGitBranchSwitchCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsGitCommitsCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsGitOverviewRetrievePathParams {
  projectId: string;
}

export interface PlatformProjectsGitPushesCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsGitWorktreePruneCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsGitWorktreeRemovalsCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsGitWorktreesCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsListQuery extends Record<string, BirdcoderSdkQueryValue> {
  userId?: string;
  workspaceId?: string;
  rootPath?: string;
}

export interface PlatformProjectsPublishCreatePathParams {
  projectId: string;
}

export interface PlatformProjectsRetrievePathParams {
  projectId: string;
}

export interface PlatformProjectsUpdatePathParams {
  projectId: string;
}

export interface PlatformWorkspacesDeletePathParams {
  workspaceId: string;
}

export interface PlatformWorkspacesListQuery extends Record<string, BirdcoderSdkQueryValue> {
  userId?: string;
}

export interface PlatformWorkspacesRealtimeSubscribePathParams {
  workspaceId: string;
}

export interface PlatformWorkspacesRealtimeSubscribeQuery extends Record<string, BirdcoderSdkQueryValue> {
  sessionId?: string;
}

export interface PlatformWorkspacesUpdatePathParams {
  workspaceId: string;
}

export interface RuntimeEnginesCapabilitiesRetrievePathParams {
  engineKey: string;
}

export interface RuntimeNativeSessionsListQuery extends Record<string, BirdcoderSdkQueryValue> {
  workspaceId?: string;
  projectId?: string;
  engineId?: "codex" | "claude-code" | "gemini" | "opencode";
  limit?: number;
  offset?: number;
}

export interface RuntimeNativeSessionsRetrievePathParams {
  id: string;
}

export interface RuntimeNativeSessionsRetrieveQuery extends Record<string, BirdcoderSdkQueryValue> {
  workspaceId?: string;
  projectId?: string;
  engineId?: "codex" | "claude-code" | "gemini" | "opencode";
}

export interface SkillsSkillPackagesInstallationsCreatePathParams {
  packageId: string;
}

export interface SkillsSkillPackagesListQuery extends Record<string, BirdcoderSdkQueryValue> {
  userId?: string;
  workspaceId?: string;
}

export interface SystemOperationsRetrievePathParams {
  operationId: string;
}

export const BIRDCODER_APP_SDK_OPERATIONS = [
  {
    "key": "auth.oauthAuthorizationUrls.retrieve",
    "method": "GET",
    "operationId": "oauthAuthorizationUrls.retrieve",
    "path": "/app/v3/api/auth/oauth_authorization_urls",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.oauthAuthorizationUrls",
    "summary": "Resolve OAuth authorization URL for SDKWork IAM sign-in",
    "tag": "auth",
    "tenantScope": "platform"
  },
  {
    "key": "auth.oauthSessions.create",
    "method": "POST",
    "operationId": "oauthSessions.create",
    "path": "/app/v3/api/auth/oauth_sessions",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.oauthSessions",
    "summary": "Create SDKWork IAM session with OAuth authorization code",
    "tag": "auth",
    "tenantScope": "platform"
  },
  {
    "key": "auth.passwordResetRequests.create",
    "method": "POST",
    "operationId": "passwordResetRequests.create",
    "path": "/app/v3/api/auth/password_reset_requests",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.passwordResetRequests",
    "summary": "Create SDKWork IAM password reset request",
    "tag": "auth",
    "tenantScope": "platform"
  },
  {
    "key": "auth.passwordResets.create",
    "method": "POST",
    "operationId": "passwordResets.create",
    "path": "/app/v3/api/auth/password_resets",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.passwordResets",
    "summary": "Reset SDKWork IAM password",
    "tag": "auth",
    "tenantScope": "platform"
  },
  {
    "key": "auth.registrations.create",
    "method": "POST",
    "operationId": "registrations.create",
    "path": "/app/v3/api/auth/registrations",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.registrations",
    "summary": "Register SDKWork IAM user",
    "tag": "auth",
    "tenantScope": "platform"
  },
  {
    "key": "auth.sessions.create",
    "method": "POST",
    "operationId": "sessions.create",
    "path": "/app/v3/api/auth/sessions",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.sessions",
    "summary": "Create SDKWork IAM session",
    "tag": "auth",
    "tenantScope": "platform"
  },
  {
    "key": "auth.sessions.current.delete",
    "method": "DELETE",
    "operationId": "sessions.current.delete",
    "path": "/app/v3/api/auth/sessions/current",
    "pathParamNames": [],
    "dataScope": "user",
    "deployment": "all",
    "domain": "iam",
    "permission": "iam.sessions.current.delete",
    "public": false,
    "resource": "iam.sessions.current",
    "summary": "Delete current SDKWork IAM session",
    "tag": "auth",
    "tenantScope": "tenant"
  },
  {
    "key": "auth.sessions.current.retrieve",
    "method": "GET",
    "operationId": "sessions.current.retrieve",
    "path": "/app/v3/api/auth/sessions/current",
    "pathParamNames": [],
    "dataScope": "user",
    "deployment": "all",
    "domain": "iam",
    "permission": "iam.sessions.current.read",
    "public": false,
    "resource": "iam.sessions.current",
    "summary": "Get current SDKWork IAM session",
    "tag": "auth",
    "tenantScope": "tenant"
  },
  {
    "key": "auth.sessions.current.update",
    "method": "PATCH",
    "operationId": "sessions.current.update",
    "path": "/app/v3/api/auth/sessions/current",
    "pathParamNames": [],
    "dataScope": "user",
    "deployment": "all",
    "domain": "iam",
    "permission": "iam.sessions.current.update",
    "public": false,
    "resource": "iam.sessions.current",
    "summary": "Update current SDKWork IAM session",
    "tag": "auth",
    "tenantScope": "tenant"
  },
  {
    "key": "auth.sessions.refresh",
    "method": "POST",
    "operationId": "sessions.refresh",
    "path": "/app/v3/api/auth/sessions/refresh",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.sessions",
    "summary": "Refresh SDKWork IAM session",
    "tag": "auth",
    "tenantScope": "platform"
  },
  {
    "key": "auth.verificationCodes.create",
    "method": "POST",
    "operationId": "verificationCodes.create",
    "path": "/app/v3/api/auth/verification_codes",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.verificationCodes",
    "summary": "Create SDKWork IAM verification code",
    "tag": "auth",
    "tenantScope": "platform"
  },
  {
    "key": "auth.verificationCodes.verify",
    "method": "POST",
    "operationId": "verificationCodes.verify",
    "path": "/app/v3/api/auth/verification_codes/verify",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.verificationCodes",
    "summary": "Verify SDKWork IAM verification code",
    "tag": "auth",
    "tenantScope": "platform"
  },
  {
    "key": "collaboration.workspaceTeams.list",
    "method": "GET",
    "operationId": "workspaceTeams.list",
    "path": "/app/v3/api/teams",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "collaboration",
    "permission": "collaboration.workspaceTeams.read",
    "public": false,
    "resource": "collaboration.workspaceTeams",
    "summary": "List workspace teams",
    "tag": "collaboration",
    "tenantScope": "tenant"
  },
  {
    "key": "commerce.memberships.current.retrieve",
    "method": "GET",
    "operationId": "memberships.current.retrieve",
    "path": "/app/v3/api/memberships/current",
    "pathParamNames": [],
    "dataScope": "user",
    "deployment": "all",
    "domain": "commerce",
    "permission": "commerce.memberships.current.read",
    "public": false,
    "resource": "commerce.memberships.current",
    "summary": "Get current SDKWork commerce membership",
    "tag": "commerce",
    "tenantScope": "tenant"
  },
  {
    "key": "commerce.memberships.packageGroups.list",
    "method": "GET",
    "operationId": "memberships.packageGroups.list",
    "path": "/app/v3/api/memberships/package_groups",
    "pathParamNames": [],
    "dataScope": "user",
    "deployment": "all",
    "domain": "commerce",
    "permission": "commerce.memberships.packageGroups.read",
    "public": false,
    "resource": "commerce.memberships.packageGroups",
    "summary": "List SDKWork commerce membership package groups",
    "tag": "commerce",
    "tenantScope": "tenant"
  },
  {
    "key": "content.documents.list",
    "method": "GET",
    "operationId": "documents.list",
    "path": "/app/v3/api/documents",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "content",
    "permission": "content.documents.read",
    "public": false,
    "resource": "content.documents",
    "summary": "List project documents",
    "tag": "content",
    "tenantScope": "tenant"
  },
  {
    "key": "iam.users.current.retrieve",
    "method": "GET",
    "operationId": "users.current.retrieve",
    "path": "/app/v3/api/iam/users/current",
    "pathParamNames": [],
    "dataScope": "user",
    "deployment": "all",
    "domain": "iam",
    "permission": "iam.users.current.read",
    "public": false,
    "resource": "iam.users.current",
    "summary": "Get current SDKWork IAM user",
    "tag": "iam",
    "tenantScope": "tenant"
  },
  {
    "key": "iam.users.current.update",
    "method": "PATCH",
    "operationId": "users.current.update",
    "path": "/app/v3/api/iam/users/current",
    "pathParamNames": [],
    "dataScope": "user",
    "deployment": "all",
    "domain": "iam",
    "permission": "iam.users.current.update",
    "public": false,
    "resource": "iam.users.current",
    "summary": "Update current SDKWork IAM user profile",
    "tag": "iam",
    "tenantScope": "tenant"
  },
  {
    "key": "iam.workspaces.members.list",
    "method": "GET",
    "operationId": "workspaces.members.list",
    "path": "/app/v3/api/workspaces/{workspaceId}/members",
    "pathParamNames": [
      "workspaceId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "iam",
    "permission": "iam.workspaces.members.read",
    "public": false,
    "resource": "iam.workspaces.members",
    "summary": "List workspace members",
    "tag": "iam",
    "tenantScope": "tenant"
  },
  {
    "key": "iam.workspaces.members.upsert",
    "method": "POST",
    "operationId": "workspaces.members.upsert",
    "path": "/app/v3/api/workspaces/{workspaceId}/members",
    "pathParamNames": [
      "workspaceId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "iam",
    "permission": "iam.workspaces.members.create",
    "public": false,
    "resource": "iam.workspaces.members",
    "summary": "Upsert workspace member",
    "tag": "iam",
    "tenantScope": "tenant"
  },
  {
    "key": "intelligence.approvals.decisions.create",
    "method": "POST",
    "operationId": "approvals.decisions.create",
    "path": "/app/v3/api/approvals/{approvalId}/decision",
    "pathParamNames": [
      "approvalId"
    ],
    "dataScope": "user",
    "deployment": "all",
    "domain": "intelligence",
    "permission": "intelligence.approvals.decisions.create",
    "public": false,
    "resource": "intelligence.approvals.decisions",
    "summary": "Submit approval decision",
    "tag": "intelligence",
    "tenantScope": "tenant"
  },
  {
    "key": "intelligence.codingSessions.artifacts.list",
    "method": "GET",
    "operationId": "codingSessions.artifacts.list",
    "path": "/app/v3/api/coding_sessions/{id}/artifacts",
    "pathParamNames": [
      "id"
    ],
    "dataScope": "user",
    "deployment": "all",
    "domain": "intelligence",
    "permission": "intelligence.codingSessions.artifacts.read",
    "public": false,
    "resource": "intelligence.codingSessions.artifacts",
    "summary": "List coding session artifacts",
    "tag": "intelligence",
    "tenantScope": "tenant"
  },
  {
    "key": "intelligence.codingSessions.checkpoints.list",
    "method": "GET",
    "operationId": "codingSessions.checkpoints.list",
    "path": "/app/v3/api/coding_sessions/{id}/checkpoints",
    "pathParamNames": [
      "id"
    ],
    "dataScope": "user",
    "deployment": "all",
    "domain": "intelligence",
    "permission": "intelligence.codingSessions.checkpoints.read",
    "public": false,
    "resource": "intelligence.codingSessions.checkpoints",
    "summary": "List coding session checkpoints",
    "tag": "intelligence",
    "tenantScope": "tenant"
  },
  {
    "key": "intelligence.codingSessions.create",
    "method": "POST",
    "operationId": "codingSessions.create",
    "path": "/app/v3/api/coding_sessions",
    "pathParamNames": [],
    "dataScope": "user",
    "deployment": "all",
    "domain": "intelligence",
    "permission": "intelligence.codingSessions.create",
    "public": false,
    "resource": "intelligence.codingSessions",
    "summary": "Create coding session",
    "tag": "intelligence",
    "tenantScope": "tenant"
  },
  {
    "key": "intelligence.codingSessions.delete",
    "method": "DELETE",
    "operationId": "codingSessions.delete",
    "path": "/app/v3/api/coding_sessions/{id}",
    "pathParamNames": [
      "id"
    ],
    "dataScope": "user",
    "deployment": "all",
    "domain": "intelligence",
    "permission": "intelligence.codingSessions.delete",
    "public": false,
    "resource": "intelligence.codingSessions",
    "summary": "Delete coding session",
    "tag": "intelligence",
    "tenantScope": "tenant"
  },
  {
    "key": "intelligence.codingSessions.events.list",
    "method": "GET",
    "operationId": "codingSessions.events.list",
    "path": "/app/v3/api/coding_sessions/{id}/events",
    "pathParamNames": [
      "id"
    ],
    "dataScope": "user",
    "deployment": "all",
    "domain": "intelligence",
    "permission": "intelligence.codingSessions.events.read",
    "public": false,
    "resource": "intelligence.codingSessions.events",
    "summary": "Replay or subscribe to coding session events",
    "tag": "intelligence",
    "tenantScope": "tenant"
  },
  {
    "key": "intelligence.codingSessions.forks.create",
    "method": "POST",
    "operationId": "codingSessions.forks.create",
    "path": "/app/v3/api/coding_sessions/{id}/fork",
    "pathParamNames": [
      "id"
    ],
    "dataScope": "user",
    "deployment": "all",
    "domain": "intelligence",
    "permission": "intelligence.codingSessions.forks.create",
    "public": false,
    "resource": "intelligence.codingSessions.forks",
    "summary": "Fork coding session",
    "tag": "intelligence",
    "tenantScope": "tenant"
  },
  {
    "key": "intelligence.codingSessions.list",
    "method": "GET",
    "operationId": "codingSessions.list",
    "path": "/app/v3/api/coding_sessions",
    "pathParamNames": [],
    "dataScope": "user",
    "deployment": "all",
    "domain": "intelligence",
    "permission": "intelligence.codingSessions.read",
    "public": false,
    "resource": "intelligence.codingSessions",
    "summary": "List coding sessions",
    "tag": "intelligence",
    "tenantScope": "tenant"
  },
  {
    "key": "intelligence.codingSessions.messages.delete",
    "method": "DELETE",
    "operationId": "codingSessions.messages.delete",
    "path": "/app/v3/api/coding_sessions/{id}/messages/{messageId}",
    "pathParamNames": [
      "id",
      "messageId"
    ],
    "dataScope": "user",
    "deployment": "all",
    "domain": "intelligence",
    "permission": "intelligence.codingSessions.messages.delete",
    "public": false,
    "resource": "intelligence.codingSessions.messages",
    "summary": "Delete coding session message",
    "tag": "intelligence",
    "tenantScope": "tenant"
  },
  {
    "key": "intelligence.codingSessions.messages.update",
    "method": "PATCH",
    "operationId": "codingSessions.messages.update",
    "path": "/app/v3/api/coding_sessions/{id}/messages/{messageId}",
    "pathParamNames": [
      "id",
      "messageId"
    ],
    "dataScope": "user",
    "deployment": "all",
    "domain": "intelligence",
    "permission": "intelligence.codingSessions.messages.update",
    "public": false,
    "resource": "intelligence.codingSessions.messages",
    "summary": "Edit coding session message",
    "tag": "intelligence",
    "tenantScope": "tenant"
  },
  {
    "key": "intelligence.codingSessions.retrieve",
    "method": "GET",
    "operationId": "codingSessions.retrieve",
    "path": "/app/v3/api/coding_sessions/{id}",
    "pathParamNames": [
      "id"
    ],
    "dataScope": "user",
    "deployment": "all",
    "domain": "intelligence",
    "permission": "intelligence.codingSessions.read",
    "public": false,
    "resource": "intelligence.codingSessions",
    "summary": "Get coding session",
    "tag": "intelligence",
    "tenantScope": "tenant"
  },
  {
    "key": "intelligence.codingSessions.turns.create",
    "method": "POST",
    "operationId": "codingSessions.turns.create",
    "path": "/app/v3/api/coding_sessions/{id}/turns",
    "pathParamNames": [
      "id"
    ],
    "dataScope": "user",
    "deployment": "all",
    "domain": "intelligence",
    "permission": "intelligence.codingSessions.turns.create",
    "public": false,
    "resource": "intelligence.codingSessions.turns",
    "summary": "Create coding session turn",
    "tag": "intelligence",
    "tenantScope": "tenant"
  },
  {
    "key": "intelligence.codingSessions.update",
    "method": "PATCH",
    "operationId": "codingSessions.update",
    "path": "/app/v3/api/coding_sessions/{id}",
    "pathParamNames": [
      "id"
    ],
    "dataScope": "user",
    "deployment": "all",
    "domain": "intelligence",
    "permission": "intelligence.codingSessions.update",
    "public": false,
    "resource": "intelligence.codingSessions",
    "summary": "Update coding session",
    "tag": "intelligence",
    "tenantScope": "tenant"
  },
  {
    "key": "intelligence.questions.answers.create",
    "method": "POST",
    "operationId": "questions.answers.create",
    "path": "/app/v3/api/questions/{questionId}/answer",
    "pathParamNames": [
      "questionId"
    ],
    "dataScope": "user",
    "deployment": "all",
    "domain": "intelligence",
    "permission": "intelligence.questions.answers.create",
    "public": false,
    "resource": "intelligence.questions.answers",
    "summary": "Submit user-question answer",
    "tag": "intelligence",
    "tenantScope": "tenant"
  },
  {
    "key": "openPlatform.qrAuth.sessions.create",
    "method": "POST",
    "operationId": "qrAuth.sessions.create",
    "path": "/app/v3/api/open_platform/qr_auth/sessions",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.qrAuth.sessions",
    "summary": "Create SDKWork IAM QR auth session",
    "tag": "openPlatform",
    "tenantScope": "platform"
  },
  {
    "key": "openPlatform.qrAuth.sessions.passwords.create",
    "method": "POST",
    "operationId": "qrAuth.sessions.passwords.create",
    "path": "/app/v3/api/open_platform/qr_auth/sessions/{sessionKey}/passwords",
    "pathParamNames": [
      "sessionKey"
    ],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.qrAuth.sessions.passwords",
    "summary": "Complete SDKWork IAM QR auth session with password",
    "tag": "openPlatform",
    "tenantScope": "platform"
  },
  {
    "key": "openPlatform.qrAuth.sessions.retrieve",
    "method": "GET",
    "operationId": "qrAuth.sessions.retrieve",
    "path": "/app/v3/api/open_platform/qr_auth/sessions/{sessionKey}",
    "pathParamNames": [
      "sessionKey"
    ],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.qrAuth.sessions",
    "summary": "Get SDKWork IAM QR auth session",
    "tag": "openPlatform",
    "tenantScope": "platform"
  },
  {
    "key": "openPlatform.qrAuth.sessions.scans.create",
    "method": "POST",
    "operationId": "qrAuth.sessions.scans.create",
    "path": "/app/v3/api/open_platform/qr_auth/sessions/{sessionKey}/scans",
    "pathParamNames": [
      "sessionKey"
    ],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.qrAuth.sessions.scans",
    "summary": "Create SDKWork IAM QR auth scan",
    "tag": "openPlatform",
    "tenantScope": "platform"
  },
  {
    "key": "platform.deployments.list",
    "method": "GET",
    "operationId": "deployments.list",
    "path": "/app/v3/api/deployments",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.deployments.read",
    "public": false,
    "resource": "platform.deployments",
    "summary": "List deployments",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.collaborators.list",
    "method": "GET",
    "operationId": "projects.collaborators.list",
    "path": "/app/v3/api/projects/{projectId}/collaborators",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.collaborators.read",
    "public": false,
    "resource": "platform.projects.collaborators",
    "summary": "List project collaborators",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.collaborators.upsert",
    "method": "POST",
    "operationId": "projects.collaborators.upsert",
    "path": "/app/v3/api/projects/{projectId}/collaborators",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.collaborators.create",
    "public": false,
    "resource": "platform.projects.collaborators",
    "summary": "Upsert project collaborator",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.create",
    "method": "POST",
    "operationId": "projects.create",
    "path": "/app/v3/api/projects",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.create",
    "public": false,
    "resource": "platform.projects",
    "summary": "Create project",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.delete",
    "method": "DELETE",
    "operationId": "projects.delete",
    "path": "/app/v3/api/projects/{projectId}",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.delete",
    "public": false,
    "resource": "platform.projects",
    "summary": "Delete project",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.branches.create",
    "method": "POST",
    "operationId": "projects.git.branches.create",
    "path": "/app/v3/api/projects/{projectId}/git/branches",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.git.branches.create",
    "public": false,
    "resource": "platform.projects.git.branches",
    "summary": "Create project Git branch",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.branchSwitch.create",
    "method": "POST",
    "operationId": "projects.git.branchSwitch.create",
    "path": "/app/v3/api/projects/{projectId}/git/branch_switch",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.git.branchSwitch.create",
    "public": false,
    "resource": "platform.projects.git.branchSwitch",
    "summary": "Switch project Git branch",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.commits.create",
    "method": "POST",
    "operationId": "projects.git.commits.create",
    "path": "/app/v3/api/projects/{projectId}/git/commits",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.git.commits.create",
    "public": false,
    "resource": "platform.projects.git.commits",
    "summary": "Commit project Git changes",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.overview.retrieve",
    "method": "GET",
    "operationId": "projects.git.overview.retrieve",
    "path": "/app/v3/api/projects/{projectId}/git/overview",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.git.overview.read",
    "public": false,
    "resource": "platform.projects.git.overview",
    "summary": "Get project Git overview",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.pushes.create",
    "method": "POST",
    "operationId": "projects.git.pushes.create",
    "path": "/app/v3/api/projects/{projectId}/git/pushes",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.git.pushes.create",
    "public": false,
    "resource": "platform.projects.git.pushes",
    "summary": "Push project Git branch",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.worktreePrune.create",
    "method": "POST",
    "operationId": "projects.git.worktreePrune.create",
    "path": "/app/v3/api/projects/{projectId}/git/worktree_prune",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.git.worktreePrune.create",
    "public": false,
    "resource": "platform.projects.git.worktreePrune",
    "summary": "Prune project Git worktrees",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.worktreeRemovals.create",
    "method": "POST",
    "operationId": "projects.git.worktreeRemovals.create",
    "path": "/app/v3/api/projects/{projectId}/git/worktree_removals",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.git.worktreeRemovals.create",
    "public": false,
    "resource": "platform.projects.git.worktreeRemovals",
    "summary": "Remove project Git worktree",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.git.worktrees.create",
    "method": "POST",
    "operationId": "projects.git.worktrees.create",
    "path": "/app/v3/api/projects/{projectId}/git/worktrees",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.git.worktrees.create",
    "public": false,
    "resource": "platform.projects.git.worktrees",
    "summary": "Create project Git worktree",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.list",
    "method": "GET",
    "operationId": "projects.list",
    "path": "/app/v3/api/projects",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.read",
    "public": false,
    "resource": "platform.projects",
    "summary": "List projects",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.publish.create",
    "method": "POST",
    "operationId": "projects.publish.create",
    "path": "/app/v3/api/projects/{projectId}/publish",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.publish.create",
    "public": false,
    "resource": "platform.projects.publish",
    "summary": "Publish project release flow",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.retrieve",
    "method": "GET",
    "operationId": "projects.retrieve",
    "path": "/app/v3/api/projects/{projectId}",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.read",
    "public": false,
    "resource": "platform.projects",
    "summary": "Get project",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.update",
    "method": "PATCH",
    "operationId": "projects.update",
    "path": "/app/v3/api/projects/{projectId}",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.update",
    "public": false,
    "resource": "platform.projects",
    "summary": "Update project",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.workspaces.create",
    "method": "POST",
    "operationId": "workspaces.create",
    "path": "/app/v3/api/workspaces",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.workspaces.create",
    "public": false,
    "resource": "platform.workspaces",
    "summary": "Create workspace",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.workspaces.delete",
    "method": "DELETE",
    "operationId": "workspaces.delete",
    "path": "/app/v3/api/workspaces/{workspaceId}",
    "pathParamNames": [
      "workspaceId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.workspaces.delete",
    "public": false,
    "resource": "platform.workspaces",
    "summary": "Delete workspace",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.workspaces.list",
    "method": "GET",
    "operationId": "workspaces.list",
    "path": "/app/v3/api/workspaces",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.workspaces.read",
    "public": false,
    "resource": "platform.workspaces",
    "summary": "List workspaces",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.workspaces.realtime.subscribe",
    "method": "GET",
    "operationId": "workspaces.realtime.subscribe",
    "path": "/app/v3/api/workspaces/{workspaceId}/realtime",
    "pathParamNames": [
      "workspaceId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.workspaces.realtime.subscribe",
    "public": false,
    "resource": "platform.workspaces.realtime",
    "summary": "Subscribe to workspace realtime invalidation events",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.workspaces.update",
    "method": "PATCH",
    "operationId": "workspaces.update",
    "path": "/app/v3/api/workspaces/{workspaceId}",
    "pathParamNames": [
      "workspaceId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.workspaces.update",
    "public": false,
    "resource": "platform.workspaces",
    "summary": "Update workspace",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "runtime.engines.capabilities.retrieve",
    "method": "GET",
    "operationId": "engines.capabilities.retrieve",
    "path": "/app/v3/api/engines/{engineKey}/capabilities",
    "pathParamNames": [
      "engineKey"
    ],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "runtime",
    "permission": "runtime.engines.capabilities.read",
    "public": false,
    "resource": "runtime.engines.capabilities",
    "summary": "Get runtime capabilities for one engine",
    "tag": "runtime",
    "tenantScope": "tenant"
  },
  {
    "key": "runtime.engines.list",
    "method": "GET",
    "operationId": "engines.list",
    "path": "/app/v3/api/engines",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "runtime",
    "permission": "runtime.engines.read",
    "public": false,
    "resource": "runtime.engines",
    "summary": "List available engines",
    "tag": "runtime",
    "tenantScope": "tenant"
  },
  {
    "key": "runtime.modelConfig.retrieve",
    "method": "GET",
    "operationId": "modelConfig.retrieve",
    "path": "/app/v3/api/model_config",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "runtime",
    "permission": "runtime.modelConfig.read",
    "public": false,
    "resource": "runtime.modelConfig",
    "summary": "Get code engine model configuration",
    "tag": "runtime",
    "tenantScope": "tenant"
  },
  {
    "key": "runtime.modelConfig.sync",
    "method": "PUT",
    "operationId": "modelConfig.sync",
    "path": "/app/v3/api/model_config",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "runtime",
    "permission": "runtime.modelConfig.update",
    "public": false,
    "resource": "runtime.modelConfig",
    "summary": "Sync code engine model configuration",
    "tag": "runtime",
    "tenantScope": "tenant"
  },
  {
    "key": "runtime.models.list",
    "method": "GET",
    "operationId": "models.list",
    "path": "/app/v3/api/models",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "runtime",
    "permission": "runtime.models.read",
    "public": false,
    "resource": "runtime.models",
    "summary": "List model catalog",
    "tag": "runtime",
    "tenantScope": "tenant"
  },
  {
    "key": "runtime.nativeSessionProviders.list",
    "method": "GET",
    "operationId": "nativeSessionProviders.list",
    "path": "/app/v3/api/native_session_providers",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "runtime",
    "permission": "runtime.nativeSessionProviders.read",
    "public": false,
    "resource": "runtime.nativeSessionProviders",
    "summary": "List registered native engine session providers",
    "tag": "runtime",
    "tenantScope": "tenant"
  },
  {
    "key": "runtime.nativeSessions.list",
    "method": "GET",
    "operationId": "nativeSessions.list",
    "path": "/app/v3/api/native_sessions",
    "pathParamNames": [],
    "dataScope": "user",
    "deployment": "all",
    "domain": "runtime",
    "permission": "runtime.nativeSessions.read",
    "public": false,
    "resource": "runtime.nativeSessions",
    "summary": "List discovered native engine sessions",
    "tag": "runtime",
    "tenantScope": "tenant"
  },
  {
    "key": "runtime.nativeSessions.retrieve",
    "method": "GET",
    "operationId": "nativeSessions.retrieve",
    "path": "/app/v3/api/native_sessions/{id}",
    "pathParamNames": [
      "id"
    ],
    "dataScope": "user",
    "deployment": "all",
    "domain": "runtime",
    "permission": "runtime.nativeSessions.read",
    "public": false,
    "resource": "runtime.nativeSessions",
    "summary": "Get discovered native engine session detail",
    "tag": "runtime",
    "tenantScope": "tenant"
  },
  {
    "key": "skills.skillPackages.installations.create",
    "method": "POST",
    "operationId": "skillPackages.installations.create",
    "path": "/app/v3/api/skill_packages/{packageId}/installations",
    "pathParamNames": [
      "packageId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "ecosystem",
    "permission": "ecosystem.skillPackages.installations.create",
    "public": false,
    "resource": "ecosystem.skillPackages.installations",
    "summary": "Install skill package for a scope",
    "tag": "skills",
    "tenantScope": "tenant"
  },
  {
    "key": "skills.skillPackages.list",
    "method": "GET",
    "operationId": "skillPackages.list",
    "path": "/app/v3/api/skill_packages",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "ecosystem",
    "permission": "ecosystem.skillPackages.read",
    "public": false,
    "resource": "ecosystem.skillPackages",
    "summary": "List skill packages",
    "tag": "skills",
    "tenantScope": "tenant"
  },
  {
    "key": "system.descriptor.retrieve",
    "method": "GET",
    "operationId": "descriptor.retrieve",
    "path": "/app/v3/api/system/descriptor",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "system",
    "permission": "system.descriptor.read",
    "public": false,
    "resource": "system.descriptor",
    "summary": "Get coding-server descriptor",
    "tag": "system",
    "tenantScope": "tenant"
  },
  {
    "key": "system.health.retrieve",
    "method": "GET",
    "operationId": "health.retrieve",
    "path": "/app/v3/api/system/health",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "system",
    "permission": "system.health.read",
    "public": false,
    "resource": "system.health",
    "summary": "Get coding-server health",
    "tag": "system",
    "tenantScope": "tenant"
  },
  {
    "key": "system.iam.runtime.retrieve",
    "method": "GET",
    "operationId": "iam.runtime.retrieve",
    "path": "/app/v3/api/system/iam/runtime",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.runtime",
    "summary": "Get SDKWork IAM runtime metadata",
    "tag": "system",
    "tenantScope": "platform"
  },
  {
    "key": "system.iam.verificationPolicy.retrieve",
    "method": "GET",
    "operationId": "iam.verificationPolicy.retrieve",
    "path": "/app/v3/api/system/iam/verification_policy",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "iam",
    "public": true,
    "resource": "iam.verificationPolicy",
    "summary": "Get SDKWork IAM verification policy",
    "tag": "system",
    "tenantScope": "platform"
  },
  {
    "key": "system.operations.retrieve",
    "method": "GET",
    "operationId": "operations.retrieve",
    "path": "/app/v3/api/operations/{operationId}",
    "pathParamNames": [
      "operationId"
    ],
    "dataScope": "user",
    "deployment": "all",
    "domain": "system",
    "permission": "system.operations.read",
    "public": false,
    "resource": "system.operations",
    "summary": "Get operation status",
    "tag": "system",
    "tenantScope": "tenant"
  },
  {
    "key": "system.routes.list",
    "method": "GET",
    "operationId": "routes.list",
    "path": "/app/v3/api/system/routes",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "system",
    "permission": "system.routes.read",
    "public": false,
    "resource": "system.routes",
    "summary": "List unified API routes",
    "tag": "system",
    "tenantScope": "tenant"
  },
  {
    "key": "system.runtime.retrieve",
    "method": "GET",
    "operationId": "runtime.retrieve",
    "path": "/app/v3/api/system/runtime",
    "pathParamNames": [],
    "dataScope": "platform",
    "deployment": "all",
    "domain": "system",
    "permission": "system.runtime.read",
    "public": false,
    "resource": "system.runtime",
    "summary": "Get runtime metadata",
    "tag": "system",
    "tenantScope": "tenant"
  },
  {
    "key": "templates.appTemplates.list",
    "method": "GET",
    "operationId": "appTemplates.list",
    "path": "/app/v3/api/app_templates",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "ecosystem",
    "permission": "ecosystem.appTemplates.read",
    "public": false,
    "resource": "ecosystem.appTemplates",
    "summary": "List app templates",
    "tag": "templates",
    "tenantScope": "tenant"
  }
] as const;

export const BIRDCODER_APP_SDK_OPERATION_INDEX: Record<string, BirdcoderSdkOperationDescriptor> = Object.fromEntries(
  BIRDCODER_APP_SDK_OPERATIONS.map((operation) => [operation.key, operation]),
);
