use sdkwork_web_contract::{HttpMethod, HttpRoute};
use sdkwork_web_core::HttpRouteManifest;

use crate::paths;

pub const CODING_SESSIONS_APP_API_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::SESSIONS,
        "intelligence",
        "listCodingSessions",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::SESSIONS,
        "intelligence",
        "createCodingSession",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::SESSION,
        "intelligence",
        "getCodingSession",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        paths::SESSION,
        "intelligence",
        "updateCodingSession",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::SESSION,
        "intelligence",
        "deleteCodingSession",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::SESSION_FORK,
        "intelligence",
        "forkCodingSession",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::SESSION_TURNS,
        "intelligence",
        "createCodingSessionTurn",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        paths::SESSION_MESSAGE,
        "intelligence",
        "editCodingSessionMessage",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::SESSION_MESSAGE,
        "intelligence",
        "deleteCodingSessionMessage",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::SESSION_EVENTS,
        "intelligence",
        "listCodingSessionEvents",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::SESSION_ARTIFACTS,
        "intelligence",
        "listCodingSessionArtifacts",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::SESSION_CHECKPOINTS,
        "intelligence",
        "listCodingSessionCheckpoints",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::APPROVAL_DECISION,
        "intelligence",
        "submitApprovalDecision",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::USER_QUESTION_ANSWER,
        "intelligence",
        "submitUserQuestionAnswer",
    ),
];

pub fn coding_sessions_app_api_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(CODING_SESSIONS_APP_API_ROUTES)
}
