// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-backend-v3.openapi.json. Do not edit by hand.

export const BIRDCODER_BACKEND_SDK_STANDARD_PROFILE = "sdkwork-v3" as const;
export const BIRDCODER_BACKEND_SDK_API_PREFIX = "/backend/v3/api" as const;
export const BIRDCODER_BACKEND_SDK_PACKAGE_NAME = "@sdkwork/birdcoder-backend-sdk" as const;

export type BirdcoderSdkQueryValue = boolean | number | string | null | undefined;

export interface BirdcoderSdkOperationDescriptor {
  dataScope: string;
  deployment: 'all' | 'local' | 'private' | 'saas';
  domain: string;
  key: string;
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  operationId: string;
  path: string;
  pathParamNames: readonly string[];
  permission?: string;
  public: boolean;
  resource: string;
  summary: string;
  tag: string;
  tenantScope: string;
}

export interface BirdCoderAdminAuditEventSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  createdAt?: string;
  updatedAt?: string;
  scopeType: string;
  scopeId: string;
  eventType: string;
  payload: Record<string, unknown>;
}

export interface BirdCoderAdminAuditEventSummaryListEnvelope {
  items: Array<BirdCoderAdminAuditEventSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderAdminPolicySummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  createdAt?: string;
  updatedAt: string;
  scopeType: string;
  scopeId: string;
  policyCategory: string;
  targetType: string;
  targetId: string;
  approvalPolicy: "AutoAllow" | "OnRequest" | "Restricted" | "ReleaseOnly";
  rationale?: string;
  status: string;
}

export interface BirdCoderAdminPolicySummaryListEnvelope {
  items: Array<BirdCoderAdminPolicySummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderApiListMeta {
  page: number;
  pageSize: number;
  total: number;
  version: string;
}

export interface BirdCoderApiMeta {
  page?: number;
  pageSize?: number;
  total?: number;
  version: string;
}

export interface BirdCoderApiProblemDetails {
  code: string;
  message: string;
  detail?: string;
  retryable: boolean;
  fieldErrors?: Record<string, string>;
}

export interface BirdCoderDeploymentRecordSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  createdAt?: string;
  updatedAt?: string;
  projectId: string;
  targetId: string;
  releaseRecordId?: string;
  status: "planned" | "running" | "succeeded" | "failed" | "rolled_back";
  endpointUrl?: string;
  startedAt?: string;
  completedAt?: string;
}

export interface BirdCoderDeploymentRecordSummaryListEnvelope {
  items: Array<BirdCoderDeploymentRecordSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderDeploymentTargetSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  createdAt?: string;
  updatedAt?: string;
  projectId: string;
  name: string;
  environmentKey: string;
  runtime: string;
  status: "active" | "archived";
}

export interface BirdCoderDeploymentTargetSummaryListEnvelope {
  items: Array<BirdCoderDeploymentTargetSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderProblemEnvelope {
  data: BirdCoderApiProblemDetails;
  meta: BirdCoderApiMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderReleaseSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  createdAt?: string;
  updatedAt?: string;
  releaseVersion: string;
  releaseKind: string;
  rolloutStage: string;
  manifest?: Record<string, unknown>;
  status: string;
}

export interface BirdCoderReleaseSummaryListEnvelope {
  items: Array<BirdCoderReleaseSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderTeamMemberSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  teamId: string;
  userId: string;
  role: "owner" | "admin" | "member" | "viewer";
  status: "invited" | "active" | "suspended" | "removed";
  createdByUserId?: string;
  grantedByUserId?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface BirdCoderTeamMemberSummaryListEnvelope {
  items: Array<BirdCoderTeamMemberSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface BirdCoderTeamSummary {
  id: string;
  uuid?: string;
  tenantId?: string;
  organizationId?: string;
  createdAt?: string;
  updatedAt?: string;
  workspaceId: string;
  code?: string;
  title?: string;
  name: string;
  description?: string;
  ownerId?: string;
  leaderId?: string;
  createdByUserId?: string;
  metadata?: Record<string, unknown>;
  status: "active" | "archived";
}

export interface BirdCoderTeamSummaryListEnvelope {
  items: Array<BirdCoderTeamSummary>;
  meta: BirdCoderApiListMeta;
  requestId: string;
  timestamp: string;
}

export interface IamTeamGovernanceListQuery extends Record<string, BirdcoderSdkQueryValue> {
  userId?: string;
  workspaceId?: string;
}

export interface IamTeamGovernanceMembersListPathParams {
  teamId: string;
}

export interface PlatformProjectsDeploymentTargetsListPathParams {
  projectId: string;
}

export const BIRDCODER_BACKEND_SDK_OPERATIONS = [
  {
    "key": "iam.auditEvents.list",
    "method": "GET",
    "operationId": "auditEvents.list",
    "path": "/backend/v3/api/iam/audit_events",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "iam",
    "permission": "iam.auditEvents.read",
    "public": false,
    "resource": "iam.auditEvents",
    "summary": "List audit events",
    "tag": "iam",
    "tenantScope": "tenant"
  },
  {
    "key": "iam.policies.list",
    "method": "GET",
    "operationId": "policies.list",
    "path": "/backend/v3/api/iam/policies",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "iam",
    "permission": "iam.policies.read",
    "public": false,
    "resource": "iam.policies",
    "summary": "List governance policies",
    "tag": "iam",
    "tenantScope": "tenant"
  },
  {
    "key": "iam.teamGovernance.list",
    "method": "GET",
    "operationId": "teamGovernance.list",
    "path": "/backend/v3/api/iam/teams",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "iam",
    "permission": "iam.teamGovernance.read",
    "public": false,
    "resource": "iam.teamGovernance",
    "summary": "List teams",
    "tag": "iam",
    "tenantScope": "tenant"
  },
  {
    "key": "iam.teamGovernance.members.list",
    "method": "GET",
    "operationId": "teamGovernance.members.list",
    "path": "/backend/v3/api/iam/teams/{teamId}/members",
    "pathParamNames": [
      "teamId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "iam",
    "permission": "iam.teamGovernance.members.read",
    "public": false,
    "resource": "iam.teamGovernance.members",
    "summary": "List team members",
    "tag": "iam",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.deploymentGovernance.list",
    "method": "GET",
    "operationId": "deploymentGovernance.list",
    "path": "/backend/v3/api/deployments",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.deploymentGovernance.read",
    "public": false,
    "resource": "platform.deploymentGovernance",
    "summary": "List governed deployments",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.projects.deploymentTargets.list",
    "method": "GET",
    "operationId": "projects.deploymentTargets.list",
    "path": "/backend/v3/api/projects/{projectId}/deployment_targets",
    "pathParamNames": [
      "projectId"
    ],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.projects.deploymentTargets.read",
    "public": false,
    "resource": "platform.projects.deploymentTargets",
    "summary": "List deployment targets",
    "tag": "platform",
    "tenantScope": "tenant"
  },
  {
    "key": "platform.releases.list",
    "method": "GET",
    "operationId": "releases.list",
    "path": "/backend/v3/api/releases",
    "pathParamNames": [],
    "dataScope": "organization",
    "deployment": "all",
    "domain": "platform",
    "permission": "platform.releases.read",
    "public": false,
    "resource": "platform.releases",
    "summary": "List releases",
    "tag": "platform",
    "tenantScope": "tenant"
  }
] as const;

export const BIRDCODER_BACKEND_SDK_OPERATION_INDEX: Record<string, BirdcoderSdkOperationDescriptor> = Object.fromEntries(
  BIRDCODER_BACKEND_SDK_OPERATIONS.map((operation) => [operation.key, operation]),
);
