name: sdkwork_birdcoder_flutter_mobile_console_shell
description: SDKWork Birdcoder Flutter Mobile Console Shell
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sdkwork_birdcoder_flutter_mobile_console_core:
    path: ../sdkwork_birdcoder_flutter_mobile_console_core
