/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_SDKWORK_BIRDCODER_APPLICATION_PUBLIC_HTTP_URL?: string;
  readonly VITE_SDKWORK_BIRDCODER_PLATFORM_API_GATEWAY_HTTP_URL?: string;
  readonly VITE_BIRDCODER_AUTH_DEV_DEFAULT_ACCOUNT?: string;
  readonly VITE_BIRDCODER_AUTH_DEV_DEFAULT_EMAIL?: string;
  readonly VITE_BIRDCODER_AUTH_DEV_DEFAULT_LOGIN_METHOD?: string;
  readonly VITE_BIRDCODER_AUTH_DEV_DEFAULT_PASSWORD?: string;
  readonly VITE_BIRDCODER_AUTH_DEV_DEFAULT_PHONE?: string;
  readonly VITE_BIRDCODER_AUTH_DEV_PREFILL_ENABLED?: string;
  readonly VITE_SDKWORK_BIRDCODER_DEPLOYMENT_PROFILE?: string;
  readonly VITE_SDKWORK_BIRDCODER_RUNTIME_TARGET?: string;
}
