// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import {
  createBirdcoderSdkOperationRequester,
  type BirdcoderSdkAuthTokens,
  type BirdcoderSdkTransport,
} from './http';
import { BIRDCODER_APP_SDK_OPERATION_INDEX } from './types';
import { createAuthApi, type AuthApi } from './api/auth';
import { createBillingApi, type BillingApi } from './api/billing';
import { createContentApi, type ContentApi } from './api/content';
import { createIamApi, type IamApi } from './api/iam';
import { createIntelligenceApi, type IntelligenceApi } from './api/intelligence';
import { createPlatformApi, type PlatformApi } from './api/platform';
import { createRuntimeApi, type RuntimeApi } from './api/runtime';
import { createSkillsApi, type SkillsApi } from './api/skills';
import { createSystemApi, type SystemApi } from './api/system';
import { createTemplatesApi, type TemplatesApi } from './api/templates';

export interface CreateBirdcoderAppSdkClientOptions {
  accessToken?: string;
  authToken?: string;
  transport: BirdcoderSdkTransport;
}

export interface BirdcoderAppSdkClient {
  clearSdkworkAuthTokens(): void;
  setSdkworkAuthTokens(tokens: BirdcoderSdkAuthTokens): void;
  auth: AuthApi;
  billing: BillingApi;
  content: ContentApi;
  iam: IamApi;
  intelligence: IntelligenceApi;
  platform: PlatformApi;
  runtime: RuntimeApi;
  skills: SkillsApi;
  system: SystemApi;
  templates: TemplatesApi;
}

export function createBirdcoderAppSdkClient(
  options: CreateBirdcoderAppSdkClientOptions,
): BirdcoderAppSdkClient {
  const requester = createBirdcoderSdkOperationRequester({
    accessToken: options.accessToken,
    authToken: options.authToken,
    operationIndex: BIRDCODER_APP_SDK_OPERATION_INDEX,
    surface: "app",
    transport: options.transport,
  });

  return {
    clearSdkworkAuthTokens: requester.clearSdkworkAuthTokens,
    setSdkworkAuthTokens: requester.setSdkworkAuthTokens,
    auth: createAuthApi(requester.requestOperation),
    billing: createBillingApi(requester.requestOperation),
    content: createContentApi(requester.requestOperation),
    iam: createIamApi(requester.requestOperation),
    intelligence: createIntelligenceApi(requester.requestOperation),
    platform: createPlatformApi(requester.requestOperation),
    runtime: createRuntimeApi(requester.requestOperation),
    skills: createSkillsApi(requester.requestOperation),
    system: createSystemApi(requester.requestOperation),
    templates: createTemplatesApi(requester.requestOperation),
  };
}
