name: sdkwork_birdcoder_flutter_mobile_core
description: SDKWork Birdcoder Flutter Mobile Core
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.7
  sdkwork_agents_app_sdk:
    path: ../../../../../sdkwork-agents/sdks/sdkwork-agents-app-sdk/sdkwork-agents-app-sdk-flutter/generated/server-openapi
  sdkwork_iam_app_sdk:
    path: ../../../../../sdkwork-iam/sdks/sdkwork-iam-app-sdk/sdkwork-iam-app-sdk-flutter/generated/server-openapi
  sdkwork_birdcoder_flutter_mobile_app_sdk_consumer:
    path: ../../sdks/sdkwork_birdcoder_flutter_mobile_app_sdk_consumer
  sdkwork_birdcoder_flutter_mobile_host:
    path: ../sdkwork_birdcoder_flutter_mobile_host
  uuid: ^4.5.3
