name: sdkwork_birdcoder_flutter_mobile_core
description: SDKWork Birdcoder Flutter Mobile Core
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sdkwork_birdcoder_flutter_mobile_app_sdk_consumer:
    path: ../../sdks/sdkwork_birdcoder_flutter_mobile_app_sdk_consumer
  sdkwork_birdcoder_flutter_mobile_host:
    path: ../sdkwork_birdcoder_flutter_mobile_host
