use sdkwork_web_contract::{HttpMethod, HttpRoute};
use sdkwork_web_core::HttpRouteManifest;

use crate::paths;

pub const WORKSPACE_APP_API_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::WORKSPACES_PATH,
        "intelligence",
        "workspaces.list",
    )
    .with_required_permission("birdcoder.intelligence-workspaces.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::WORKSPACES_PATH,
        "intelligence",
        "workspaces.create",
    )
    .with_required_permission("birdcoder.intelligence-workspaces.create"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::WORKSPACE_DETAIL_PATH,
        "intelligence",
        "workspaces.retrieve",
    )
    .with_required_permission("birdcoder.intelligence-workspaces.read"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        paths::WORKSPACE_DETAIL_PATH,
        "intelligence",
        "workspaces.update",
    )
    .with_required_permission("birdcoder.intelligence-workspaces.update"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::WORKSPACE_DETAIL_PATH,
        "intelligence",
        "workspaces.delete",
    )
    .with_required_permission("birdcoder.intelligence-workspaces.delete"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECTS_PATH,
        "intelligence",
        "projects.list",
    )
    .with_required_permission("birdcoder.intelligence-projects.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECTS_PATH,
        "intelligence",
        "projects.create",
    )
    .with_required_permission("birdcoder.intelligence-projects.create"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_DETAIL_PATH,
        "intelligence",
        "projects.retrieve",
    )
    .with_required_permission("birdcoder.intelligence-projects.read"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        paths::PROJECT_DETAIL_PATH,
        "intelligence",
        "projects.update",
    )
    .with_required_permission("birdcoder.intelligence-projects.update"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::PROJECT_DETAIL_PATH,
        "intelligence",
        "projects.delete",
    )
    .with_required_permission("birdcoder.intelligence-projects.delete"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_DOCUMENT_BINDINGS_PATH,
        "intelligence",
        "projects.documentBindings.list",
    )
    .with_required_permission("birdcoder.intelligence-projects-document-bindings.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_DOCUMENT_BINDINGS_PATH,
        "intelligence",
        "projects.documentBindings.create",
    )
    .with_required_permission("birdcoder.intelligence-projects-document-bindings.create"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_DOCUMENT_BINDING_DETAIL_PATH,
        "intelligence",
        "projects.documentBindings.retrieve",
    )
    .with_required_permission("birdcoder.intelligence-projects-document-bindings.read"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::PROJECT_DOCUMENT_BINDING_DETAIL_PATH,
        "intelligence",
        "projects.documentBindings.delete",
    )
    .with_required_permission("birdcoder.intelligence-projects-document-bindings.delete"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_SANDBOX_BINDING_PATH,
        "intelligence",
        "projects.sandboxBinding.retrieve",
    )
    .with_required_permission("birdcoder.intelligence-projects-sandbox-binding.read"),
    HttpRoute::dual_token(
        HttpMethod::Put,
        paths::PROJECT_SANDBOX_BINDING_PATH,
        "intelligence",
        "projects.sandboxBinding.update",
    )
    .with_idempotent(true)
    .with_required_permission("birdcoder.intelligence-projects-sandbox-binding.update"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::PROJECT_SANDBOX_BINDING_PATH,
        "intelligence",
        "projects.sandboxBinding.delete",
    )
    .with_required_permission("birdcoder.intelligence-projects-sandbox-binding.delete"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_RUNTIME_LOCATIONS_PATH,
        "intelligence",
        "projects.runtimeLocations.list",
    )
    .with_required_permission("birdcoder.intelligence-projects-runtime-locations.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_RUNTIME_LOCATIONS_PATH,
        "intelligence",
        "projects.runtimeLocations.create",
    )
    .with_idempotent(true)
    .with_required_permission("birdcoder.intelligence-projects-runtime-locations.create"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_RUNTIME_LOCATION_DETAIL_PATH,
        "intelligence",
        "projects.runtimeLocations.retrieve",
    )
    .with_required_permission("birdcoder.intelligence-projects-runtime-locations.read"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        paths::PROJECT_RUNTIME_LOCATION_DETAIL_PATH,
        "intelligence",
        "projects.runtimeLocations.update",
    )
    .with_idempotent(true)
    .with_required_permission("birdcoder.intelligence-projects-runtime-locations.update"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::PROJECT_RUNTIME_LOCATION_DETAIL_PATH,
        "intelligence",
        "projects.runtimeLocations.delete",
    )
    .with_required_permission("birdcoder.intelligence-projects-runtime-locations.delete"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_RUNTIME_LOCATION_REBIND_PATH,
        "intelligence",
        "projects.runtimeLocations.rebind",
    )
    .with_idempotent(true)
    .with_required_permission("birdcoder.intelligence-projects-runtime-locations.update"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_RUNTIME_LOCATION_VERIFICATION_REQUEST_PATH,
        "intelligence",
        "projects.runtimeLocations.requestVerification",
    )
    .with_idempotent(true)
    .with_required_permission("birdcoder.intelligence-projects-runtime-locations.update"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_RUNTIME_LOCATION_PREFERENCES_PATH,
        "intelligence",
        "projects.runtimeLocations.preferences.list",
    )
    .with_required_permission("birdcoder.intelligence-projects-runtime-locations-preferences.read"),
    HttpRoute::dual_token(
        HttpMethod::Put,
        paths::PROJECT_RUNTIME_LOCATION_PREFERENCE_PATH,
        "intelligence",
        "projects.runtimeLocations.preferences.update",
    )
    .with_idempotent(true)
    .with_required_permission("birdcoder.intelligence-projects-runtime-locations-preferences.update"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_GIT_OVERVIEW_PATH,
        "intelligence",
        "projects.git.overview.retrieve",
    )
    .with_required_permission("birdcoder.intelligence-projects-git-overview.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_GIT_DIFF_PATH,
        "intelligence",
        "projects.git.diff.retrieve",
    )
    .with_required_permission("birdcoder.intelligence-projects-git-diff.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_BRANCHES_PATH,
        "intelligence",
        "projects.git.branches.create",
    )
    .with_required_permission("birdcoder.intelligence-projects-git-branches.create"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_BRANCH_SWITCH_PATH,
        "intelligence",
        "projects.git.switchBranch",
    )
    .with_required_permission("birdcoder.intelligence-projects-git-branches.update"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_COMMITS_PATH,
        "intelligence",
        "projects.git.commits.create",
    )
    .with_required_permission("birdcoder.intelligence-projects-git-commits.create"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_PUSHES_PATH,
        "intelligence",
        "projects.git.push",
    )
    .with_required_permission("birdcoder.intelligence-projects-git-pushes.create"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_WORKTREES_PATH,
        "intelligence",
        "projects.git.worktrees.create",
    )
    .with_required_permission("birdcoder.intelligence-projects-git-worktrees.create"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_WORKTREE_REMOVALS_PATH,
        "intelligence",
        "projects.git.removeWorktree",
    )
    .with_required_permission("birdcoder.intelligence-projects-git-worktree-removals.create"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_WORKTREE_PRUNE_PATH,
        "intelligence",
        "projects.git.pruneWorktrees",
    )
    .with_required_permission("birdcoder.intelligence-projects-git-worktree-prune.create"),
];

pub fn workspace_app_api_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(WORKSPACE_APP_API_ROUTES)
}
