use sdkwork_web_contract::{HttpMethod, HttpRoute};
use sdkwork_web_core::HttpRouteManifest;

use crate::paths;

pub const WORKSPACE_APP_API_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::WORKSPACES_PATH,
        "workspaces",
        "workspaces.list",
    )
    .with_required_permission("birdcoder.platform-workspaces.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::WORKSPACES_PATH,
        "workspaces",
        "workspaces.create",
    )
    .with_required_permission("birdcoder.platform-workspaces.create"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::WORKSPACE_DETAIL_PATH,
        "workspaces",
        "workspaces.retrieve",
    )
    .with_required_permission("birdcoder.platform-workspaces.read"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        paths::WORKSPACE_DETAIL_PATH,
        "workspaces",
        "workspaces.update",
    )
    .with_required_permission("birdcoder.platform-workspaces.update"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::WORKSPACE_DETAIL_PATH,
        "workspaces",
        "workspaces.delete",
    )
    .with_required_permission("birdcoder.platform-workspaces.delete"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::WORKSPACE_REALTIME_PATH,
        "workspaces",
        "workspaces.realtime.subscribe",
    )
    .with_required_permission("birdcoder.platform-workspaces-realtime.subscribe"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::WORKSPACE_MEMBERS_PATH,
        "workspaces",
        "workspaces.members.list",
    )
    .with_required_permission("birdcoder.iam-workspaces-members.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::WORKSPACE_MEMBERS_PATH,
        "workspaces",
        "workspaces.members.create",
    )
    .with_required_permission("birdcoder.iam-workspaces-members.create"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECTS_PATH,
        "projects",
        "projects.list",
    )
    .with_required_permission("birdcoder.platform-projects.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECTS_PATH,
        "projects",
        "projects.create",
    )
    .with_required_permission("birdcoder.platform-projects.create"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_DETAIL_PATH,
        "projects",
        "projects.retrieve",
    )
    .with_required_permission("birdcoder.platform-projects.read"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        paths::PROJECT_DETAIL_PATH,
        "projects",
        "projects.update",
    )
    .with_required_permission("birdcoder.platform-projects.update"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::PROJECT_DETAIL_PATH,
        "projects",
        "projects.delete",
    )
    .with_required_permission("birdcoder.platform-projects.delete"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_WORKSPACE_BINDING_PATH,
        "projects",
        "projects.workspaceBinding.retrieve",
    )
    .with_required_permission("birdcoder.platform-projects-workspace-binding.read"),
    HttpRoute::dual_token(
        HttpMethod::Put,
        paths::PROJECT_WORKSPACE_BINDING_PATH,
        "projects",
        "projects.workspaceBinding.update",
    )
    .with_idempotent(true)
    .with_required_permission("birdcoder.platform-projects-workspace-binding.update"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::PROJECT_WORKSPACE_BINDING_PATH,
        "projects",
        "projects.workspaceBinding.delete",
    )
    .with_required_permission("birdcoder.platform-projects-workspace-binding.delete"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_RUNTIME_LOCATIONS_PATH,
        "projects",
        "projects.runtimeLocations.list",
    )
    .with_required_permission("birdcoder.platform-projects-runtime-locations.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_RUNTIME_LOCATIONS_PATH,
        "projects",
        "projects.runtimeLocations.create",
    )
    .with_idempotent(true)
    .with_required_permission("birdcoder.platform-projects-runtime-locations.create"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_RUNTIME_LOCATION_DETAIL_PATH,
        "projects",
        "projects.runtimeLocations.retrieve",
    )
    .with_required_permission("birdcoder.platform-projects-runtime-locations.read"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        paths::PROJECT_RUNTIME_LOCATION_DETAIL_PATH,
        "projects",
        "projects.runtimeLocations.update",
    )
    .with_idempotent(true)
    .with_required_permission("birdcoder.platform-projects-runtime-locations.update"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::PROJECT_RUNTIME_LOCATION_DETAIL_PATH,
        "projects",
        "projects.runtimeLocations.delete",
    )
    .with_required_permission("birdcoder.platform-projects-runtime-locations.delete"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_RUNTIME_LOCATION_REBIND_PATH,
        "projects",
        "projects.runtimeLocations.rebind",
    )
    .with_idempotent(true)
    .with_required_permission("birdcoder.platform-projects-runtime-locations.create"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_RUNTIME_LOCATION_VERIFICATION_REQUEST_PATH,
        "projects",
        "projects.runtimeLocations.requestVerification",
    )
    .with_idempotent(true)
    .with_required_permission("birdcoder.platform-projects-runtime-locations.create"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_RUNTIME_LOCATION_PREFERENCES_PATH,
        "projects",
        "projects.runtimeLocations.preferences.list",
    )
    .with_required_permission("birdcoder.platform-projects-runtime-locations-preferences.read"),
    HttpRoute::dual_token(
        HttpMethod::Put,
        paths::PROJECT_RUNTIME_LOCATION_PREFERENCE_PATH,
        "projects",
        "projects.runtimeLocations.preferences.update",
    )
    .with_idempotent(true)
    .with_required_permission("birdcoder.platform-projects-runtime-locations-preferences.update"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_GIT_OVERVIEW_PATH,
        "projects",
        "projects.git.overview.retrieve",
    )
    .with_required_permission("birdcoder.platform-projects-git-overview.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_GIT_DIFF_PATH,
        "projects",
        "projects.git.diff.retrieve",
    )
    .with_required_permission("birdcoder.platform-projects-git-overview.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_BRANCHES_PATH,
        "projects",
        "projects.git.branches.create",
    )
    .with_required_permission("birdcoder.platform-projects-git-branches.create"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_BRANCH_SWITCH_PATH,
        "projects",
        "projects.git.branchSwitch.create",
    )
    .with_required_permission("birdcoder.platform-projects-git-branch-switch.create"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_COMMITS_PATH,
        "projects",
        "projects.git.commits.create",
    )
    .with_required_permission("birdcoder.platform-projects-git-commits.create"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_PUSHES_PATH,
        "projects",
        "projects.git.pushes.create",
    )
    .with_required_permission("birdcoder.platform-projects-git-pushes.create"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_WORKTREES_PATH,
        "projects",
        "projects.git.worktrees.create",
    )
    .with_required_permission("birdcoder.platform-projects-git-worktrees.create"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_WORKTREE_REMOVALS_PATH,
        "projects",
        "projects.git.worktreeRemovals.create",
    )
    .with_required_permission("birdcoder.platform-projects-git-worktree-removals.create"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_WORKTREE_PRUNE_PATH,
        "projects",
        "projects.git.worktreePrune.create",
    )
    .with_required_permission("birdcoder.platform-projects-git-worktree-prune.create"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_COLLABORATORS_PATH,
        "projects",
        "projects.collaborators.list",
    )
    .with_required_permission("birdcoder.platform-projects-collaborators.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_COLLABORATORS_PATH,
        "projects",
        "projects.collaborators.create",
    )
    .with_required_permission("birdcoder.platform-projects-collaborators.create"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::DEPLOYMENTS_PATH,
        "deployments",
        "deployments.list",
    )
    .with_required_permission("birdcoder.platform-deployments.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_DEPLOYMENT_TARGETS_PATH,
        "projects",
        "projects.deploymentTargets.list",
    )
    .with_required_permission("birdcoder.platform-projects-deployment-targets.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_PUBLISH_PATH,
        "projects",
        "projects.publish.publish",
    )
    .with_required_permission("birdcoder.platform-projects-publish.execute"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::TEAMS_PATH,
        "workspaceTeams",
        "workspaceTeams.list",
    )
    .with_required_permission("birdcoder.collaboration-workspace-teams.read"),
];

pub fn workspace_app_api_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(WORKSPACE_APP_API_ROUTES)
}
