use axum::{routing::get, routing::post, routing::put, Router};

use crate::handlers::{self, WorkspaceAppState};
use crate::paths;

pub fn build_workspace_app_router() -> Router<WorkspaceAppState> {
    Router::new()
        .route(
            paths::WORKSPACES_PATH,
            get(handlers::list_workspaces).post(handlers::create_workspace),
        )
        .route(
            paths::WORKSPACE_DETAIL_PATH,
            get(handlers::get_workspace)
                .patch(handlers::update_workspace)
                .delete(handlers::delete_workspace),
        )
        .route(
            paths::PROJECTS_PATH,
            get(handlers::list_projects).post(handlers::create_project),
        )
        .route(
            paths::PROJECT_DETAIL_PATH,
            get(handlers::get_project)
                .patch(handlers::update_project)
                .delete(handlers::delete_project),
        )
        .route(
            paths::PROJECT_DOCUMENT_BINDINGS_PATH,
            get(handlers::list_project_document_bindings)
                .post(handlers::create_project_document_binding),
        )
        .route(
            paths::PROJECT_DOCUMENT_BINDING_DETAIL_PATH,
            get(handlers::get_project_document_binding)
                .delete(handlers::delete_project_document_binding),
        )
        .route(
            paths::PROJECT_SANDBOX_BINDING_PATH,
            get(handlers::get_project_sandbox_binding)
                .put(handlers::upsert_project_sandbox_binding)
                .delete(handlers::delete_project_sandbox_binding),
        )
        .route(
            paths::PROJECT_RUNTIME_LOCATIONS_PATH,
            get(handlers::list_project_runtime_locations)
                .post(handlers::create_project_runtime_location),
        )
        .route(
            paths::PROJECT_RUNTIME_LOCATION_DETAIL_PATH,
            get(handlers::get_project_runtime_location)
                .patch(handlers::update_project_runtime_location)
                .delete(handlers::delete_project_runtime_location),
        )
        .route(
            paths::PROJECT_RUNTIME_LOCATION_REBIND_PATH,
            post(handlers::rebind_project_runtime_location),
        )
        .route(
            paths::PROJECT_RUNTIME_LOCATION_VERIFICATION_REQUEST_PATH,
            post(handlers::request_project_runtime_location_verification),
        )
        .route(
            paths::PROJECT_RUNTIME_LOCATION_PREFERENCES_PATH,
            get(handlers::list_project_runtime_location_preferences),
        )
        .route(
            paths::PROJECT_RUNTIME_LOCATION_PREFERENCE_PATH,
            put(handlers::update_project_runtime_location_preference),
        )
        .route(
            paths::PROJECT_GIT_OVERVIEW_PATH,
            get(handlers::get_project_git_overview),
        )
        .route(
            paths::PROJECT_GIT_DIFF_PATH,
            get(handlers::get_project_git_diff),
        )
        .route(
            paths::PROJECT_GIT_BRANCHES_PATH,
            post(handlers::create_project_git_branch),
        )
        .route(
            paths::PROJECT_GIT_BRANCH_SWITCH_PATH,
            post(handlers::switch_project_git_branch),
        )
        .route(
            paths::PROJECT_GIT_COMMITS_PATH,
            post(handlers::commit_project_git_changes),
        )
        .route(
            paths::PROJECT_GIT_PUSHES_PATH,
            post(handlers::push_project_git_branch),
        )
        .route(
            paths::PROJECT_GIT_WORKTREES_PATH,
            post(handlers::create_project_git_worktree),
        )
        .route(
            paths::PROJECT_GIT_WORKTREE_REMOVALS_PATH,
            post(handlers::remove_project_git_worktree),
        )
        .route(
            paths::PROJECT_GIT_WORKTREE_PRUNE_PATH,
            post(handlers::prune_project_git_worktrees),
        )
}
