//! Deep link URL parsing and request validation.
//!
//! The protocol follows the CC Switch `v1/import` shape: the version is the
//! URL host, the action is the path, and all data lives in query parameters.
//! `resource` selects the handler; unknown resources are rejected with a
//! clear message so new link types can be added without breaking old ones.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use tauri::Url;

use super::DEEPLINK_SCHEME;

pub const IMPORT_HOST: &str = "v1";
pub const IMPORT_PATH: &str = "/import";
/// Channel kinds the model configuration store accepts.
pub const SUPPORTED_KINDS: &[&str] = &["official", "relay", "custom"];
/// Default channel kind for links that do not carry one.
pub const DEFAULT_CHANNEL_KIND: &str = "relay";
/// Full set of `app` values the CC Switch `v1/import` contract accepts,
/// including `claude-desktop` (Claude Desktop app import). Birdcoder unifies
/// model configuration, so the value only needs to pass validation.
pub const SUPPORTED_APPS: &[&str] = &[
    "claude",
    "claude-desktop",
    "codex",
    "gemini",
    "grokbuild",
    "opencode",
    "openclaw",
    "hermes",
];
/// Upper bound for the number of vendors a single import link may carry.
pub const MAX_IMPORT_VENDORS: usize = 16;

/// Parsed deep link payload forwarded to the webview for confirmation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeepLinkImportRequest {
    /// Unique id of this arrival, generated by the host. The shell uses it
    /// to deduplicate a request delivered both by the cold-start drain and
    /// by the `deep-link-import` event (registration race); the import
    /// handler ignores it.
    #[serde(default)]
    pub id: String,
    /// Protocol version, from the URL host (`v1`).
    pub version: String,
    /// Import target (`provider` today; mcp / prompt / skill / ... later).
    pub resource: String,
    /// Model channel kind: `official` / `relay` / `custom` (default relay).
    pub kind: String,
    /// CC Switch `app` value the link was generated for (validation only).
    pub app: String,
    /// Display name of the imported channel.
    pub name: String,
    /// HTTP(S) API endpoint of the imported channel.
    pub endpoint: String,
    /// API key stored alongside the channel.
    pub api_key: String,
    /// Optional default model id.
    pub model: String,
    /// Gateway OpenAI-compatible base URL (`{host}/v1`) the import uses to
    /// query the key-scoped vendor/model catalog (`GET {base}/vendors`) and
    /// write complete channel offerings. Links without it import without
    /// offerings.
    #[serde(default)]
    pub models_base_url: String,
    /// Model providers (vendor codes) the link was generated for, e.g.
    /// `openai` / `anthropic` / `deepseek`. Legacy fallback for links that
    /// carry vendors explicitly; the gateway catalog query takes precedence.
    #[serde(default)]
    pub vendors: Vec<String>,
}

/// Entry point: validates scheme / host / path and dispatches on
/// `resource`. Returns a fully validated request for the confirm dialog.
pub fn parse_deeplink_url(url: &Url) -> Result<DeepLinkImportRequest, String> {
    if url.scheme() != DEEPLINK_SCHEME {
        return Err(format!("unexpected deep link scheme \"{}\"", url.scheme()));
    }
    if url.host_str() != Some(IMPORT_HOST) || url.path() != IMPORT_PATH {
        return Err(format!(
            "unsupported deep link path; expected {DEEPLINK_SCHEME}://{IMPORT_HOST}{IMPORT_PATH}"
        ));
    }

    // Keep the raw pairs: the `vendor` parameter may repeat (multi-select),
    // and a `HashMap` would collapse duplicates to a single value.
    let pairs: Vec<(String, String)> = url.query_pairs().into_owned().collect();
    let params: HashMap<String, String> = pairs.iter().cloned().collect();
    let vendors = collect_vendor_params(&pairs);
    let resource = params.get("resource").map(String::as_str).unwrap_or_default();
    match resource {
        "provider" => parse_provider_import_request(&params, vendors),
        other => Err(format!(
            "unsupported deep link resource \"{other}\"; only resource=provider is supported for now"
        )),
    }
}

/// Collects the vendor codes carried by an import link. `vendor` values may
/// repeat (`vendor=openai&vendor=anthropic`) or join with commas
/// (`vendor=openai,anthropic`); codes are trimmed, lowercased and deduplicated
/// while preserving arrival order. Unknown or empty values are skipped — the
/// channel simply imports without that offering.
fn collect_vendor_params(pairs: &[(String, String)]) -> Vec<String> {
    let mut vendors: Vec<String> = Vec::new();
    for (key, value) in pairs {
        if key != "vendor" {
            continue;
        }
        for part in value.split(',') {
            let code = part.trim().to_lowercase();
            if code.is_empty() || vendors.contains(&code) {
                continue;
            }
            vendors.push(code);
        }
    }
    vendors
}

fn parse_provider_import_request(
    params: &HashMap<String, String>,
    vendors: Vec<String>,
) -> Result<DeepLinkImportRequest, String> {
    let request = DeepLinkImportRequest {
        // One id per arrival: two clicks on the same link get distinct ids
        // (and import two channels), while the same arrival delivered twice
        // (event + drain) is deduplicated by the shell.
        id: uuid::Uuid::new_v4().to_string(),
        version: IMPORT_HOST.to_owned(),
        resource: "provider".to_owned(),
        kind: params
            .get("kind")
            .map(String::as_str)
            .unwrap_or(DEFAULT_CHANNEL_KIND)
            .to_owned(),
        app: params.get("app").map(String::as_str).unwrap_or_default().to_owned(),
        name: params
            .get("name")
            .map(|value| value.trim())
            .unwrap_or_default()
            .to_owned(),
        endpoint: params.get("endpoint").cloned().unwrap_or_default(),
        api_key: params.get("apiKey").cloned().unwrap_or_default(),
        model: params.get("model").cloned().unwrap_or_default(),
        models_base_url: params.get("modelsBaseUrl").cloned().unwrap_or_default(),
        vendors,
    };
    validate_provider_import_request(&request)?;
    Ok(request)
}

/// Shared provider request validation, run by the parser and re-run by the
/// import handler: the import command is reachable from the webview with
/// arbitrary payloads, so the handler must not trust the dialog's state.
pub fn validate_provider_import_request(request: &DeepLinkImportRequest) -> Result<(), String> {
    if !SUPPORTED_KINDS.contains(&request.kind.as_str()) {
        return Err(format!(
            "unsupported deep link channel kind \"{}\"; expected one of {}",
            request.kind,
            SUPPORTED_KINDS.join(" / ")
        ));
    }
    if !SUPPORTED_APPS.contains(&request.app.as_str()) {
        return Err(format!(
            "unsupported deep link app \"{}\"; expected one of {}",
            request.app,
            SUPPORTED_APPS.join(" / ")
        ));
    }
    if request.name.is_empty() {
        return Err("deep link import is missing the required \"name\" parameter".to_owned());
    }
    let parsed_endpoint = Url::parse(&request.endpoint)
        .map_err(|_| "deep link import is missing a valid \"endpoint\" parameter".to_owned())?;
    if parsed_endpoint.scheme() != "http" && parsed_endpoint.scheme() != "https" {
        return Err("deep link \"endpoint\" must be an HTTP(S) URL".to_owned());
    }
    if request.api_key.is_empty() {
        return Err("deep link import is missing the required \"apiKey\" parameter".to_owned());
    }
    if !request.models_base_url.is_empty() {
        let parsed_models_base = Url::parse(&request.models_base_url)
            .map_err(|_| "deep link \"modelsBaseUrl\" must be a valid URL".to_owned())?;
        if parsed_models_base.scheme() != "http" && parsed_models_base.scheme() != "https" {
            return Err("deep link \"modelsBaseUrl\" must be an HTTP(S) URL".to_owned());
        }
    }
    if request.vendors.len() > MAX_IMPORT_VENDORS {
        return Err(format!(
            "deep link import carries too many vendors ({}); expected at most {MAX_IMPORT_VENDORS}",
            request.vendors.len()
        ));
    }
    for code in &request.vendors {
        if !is_valid_vendor_code(code) {
            return Err(format!(
                "deep link import carries an invalid vendor code \"{code}\""
            ));
        }
    }
    Ok(())
}

/// Vendor codes must be lowercase ASCII words with optional `-` separators
/// (e.g. `openai`, `01ai`, `grok-2`), matching the codes used by the model
/// management vendor presets and the Cloud Router model catalog.
fn is_valid_vendor_code(code: &str) -> bool {
    if code.is_empty() || code.len() > 64 {
        return false;
    }
    let mut bytes = code.bytes();
    let Some(first) = bytes.next() else {
        return false;
    };
    if !first.is_ascii_lowercase() && !first.is_ascii_digit() {
        return false;
    }
    bytes.all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
}

#[cfg(test)]
mod tests {
    use super::{
        parse_deeplink_url, validate_provider_import_request, DEFAULT_CHANNEL_KIND,
        MAX_IMPORT_VENDORS,
    };
    use crate::host::deeplink::DEEPLINK_SCHEME;
    use tauri::Url;

    fn import_url(query: &str) -> Url {
        Url::parse(&format!("{DEEPLINK_SCHEME}://v1/import?{query}")).unwrap()
    }

    fn provider_query() -> String {
        "resource=provider&app=claude&name=My%20Provider&endpoint=https%3A%2F%2Fapi.example.com&apiKey=sk-test-123&model=claude-sonnet-4"
            .to_owned()
    }

    #[test]
    fn parses_cc_switch_compatible_provider_link() {
        let request = parse_deeplink_url(&import_url(&provider_query())).unwrap();
        assert_eq!(request.version, "v1");
        assert_eq!(request.resource, "provider");
        // Links without a `kind` parameter are relays (backward compatible
        // with the original birdcoder://v1/import contract).
        assert_eq!(request.kind, DEFAULT_CHANNEL_KIND);
        assert_eq!(request.app, "claude");
        assert_eq!(request.name, "My Provider");
        assert_eq!(request.endpoint, "https://api.example.com");
        assert_eq!(request.api_key, "sk-test-123");
        assert_eq!(request.model, "claude-sonnet-4");
        // No `vendor` parameter: imports without offerings.
        assert!(request.vendors.is_empty());
    }

    #[test]
    fn parses_repeated_vendor_parameters() {
        let request = parse_deeplink_url(&import_url(&format!(
            "{}&vendor=openai&vendor=anthropic&vendor=deepseek",
            provider_query()
        )))
        .unwrap();
        assert_eq!(request.vendors, ["openai", "anthropic", "deepseek"]);
    }

    #[test]
    fn parses_comma_separated_vendor_parameters() {
        let request = parse_deeplink_url(&import_url(&format!(
            "{}&vendor=openai%2Canthropic",
            provider_query()
        )))
        .unwrap();
        assert_eq!(request.vendors, ["openai", "anthropic"]);
    }

    #[test]
    fn normalizes_and_deduplicates_vendor_parameters() {
        let request = parse_deeplink_url(&import_url(&format!(
            "{}&vendor=OpenAI&vendor=openai,&vendor=,deepseek",
            provider_query()
        )))
        .unwrap();
        // Codes are lowercased, empty parts skipped, duplicates dropped while
        // preserving arrival order.
        assert_eq!(request.vendors, ["openai", "deepseek"]);
    }

    #[test]
    fn rejects_invalid_vendor_codes() {
        let url = import_url(&format!("{}&vendor=open_ai", provider_query()));
        let error = parse_deeplink_url(&url).unwrap_err();
        assert!(error.contains("invalid vendor code \"open_ai\""), "{error}");
        let url = import_url(&format!("{}&vendor=-leading", provider_query()));
        let error = parse_deeplink_url(&url).unwrap_err();
        assert!(error.contains("invalid vendor code \"-leading\""), "{error}");
        let url = import_url(&format!("{}&vendor=open%20ai", provider_query()));
        let error = parse_deeplink_url(&url).unwrap_err();
        assert!(error.contains("invalid vendor code \"open ai\""), "{error}");
    }

    #[test]
    fn rejects_too_many_vendors() {
        let mut query = provider_query();
        for index in 0..=MAX_IMPORT_VENDORS {
            query.push_str(&format!("&vendor=vendor-{index}"));
        }
        let error = parse_deeplink_url(&import_url(&query)).unwrap_err();
        assert!(error.contains("too many vendors"), "{error}");
    }

    #[test]
    fn parses_explicit_channel_kind() {
        let request = parse_deeplink_url(&import_url(&format!(
            "{}&kind=official",
            provider_query()
        )))
        .unwrap();
        assert_eq!(request.kind, "official");
        let request = parse_deeplink_url(&import_url(&format!(
            "{}&kind=custom",
            provider_query()
        )))
        .unwrap();
        assert_eq!(request.kind, "custom");
    }

    #[test]
    fn rejects_unsupported_resource() {
        let url = import_url("resource=mcp&app=claude&name=X&endpoint=https%3A%2F%2Fapi.example.com&apiKey=sk-test");
        let error = parse_deeplink_url(&url).unwrap_err();
        assert!(error.contains("unsupported deep link resource \"mcp\""), "{error}");
    }

    #[test]
    fn rejects_invalid_kind() {
        let url = import_url(&format!("{}&kind=proxy", provider_query()));
        let error = parse_deeplink_url(&url).unwrap_err();
        assert!(error.contains("unsupported deep link channel kind \"proxy\""), "{error}");
    }

    #[test]
    fn rejects_unsupported_app() {
        let url = import_url("resource=provider&app=notepad&name=X&endpoint=https%3A%2F%2Fapi.example.com&apiKey=sk-test");
        let error = parse_deeplink_url(&url).unwrap_err();
        assert!(error.contains("unsupported deep link app \"notepad\""), "{error}");
    }

    #[test]
    fn rejects_missing_name_or_key() {
        let url = import_url("resource=provider&app=claude&endpoint=https%3A%2F%2Fapi.example.com&apiKey=sk-test");
        assert!(parse_deeplink_url(&url).is_err());
        let url = import_url("resource=provider&app=claude&name=X&endpoint=https%3A%2F%2Fapi.example.com");
        assert!(parse_deeplink_url(&url).is_err());
    }

    #[test]
    fn rejects_non_http_endpoint() {
        let url = import_url("resource=provider&app=claude&name=X&endpoint=file%3A%2F%2F%2Fetc%2Fpasswd&apiKey=sk-test");
        let error = parse_deeplink_url(&url).unwrap_err();
        assert!(error.contains("must be an HTTP(S) URL"), "{error}");
    }

    #[test]
    fn rejects_wrong_scheme_or_path() {
        let wrong_scheme = Url::parse("ccswitch://v1/import?resource=provider").unwrap();
        assert!(parse_deeplink_url(&wrong_scheme).is_err());
        let wrong_path = Url::parse("birdcoder://v1/config?resource=provider").unwrap();
        assert!(parse_deeplink_url(&wrong_path).is_err());
    }

    #[test]
    fn revalidates_webview_supplied_request() {
        // The import command accepts arbitrary payloads from the webview;
        // the shared validator must reject each tampered field.
        let base = parse_deeplink_url(&import_url(&provider_query())).unwrap();
        let mut tampered = base.clone();
        tampered.kind = "proxy".to_owned();
        assert!(validate_provider_import_request(&tampered).is_err());
        tampered = base.clone();
        tampered.endpoint = "file:///etc/passwd".to_owned();
        assert!(validate_provider_import_request(&tampered).is_err());
        tampered = base.clone();
        tampered.api_key.clear();
        assert!(validate_provider_import_request(&tampered).is_err());
        tampered = base.clone();
        tampered.name.clear();
        assert!(validate_provider_import_request(&tampered).is_err());
        tampered = base.clone();
        tampered.vendors = vec!["open_ai".to_owned()];
        assert!(validate_provider_import_request(&tampered).is_err());
        tampered = base.clone();
        tampered.vendors = vec!["openai".to_owned(); MAX_IMPORT_VENDORS + 1];
        assert!(validate_provider_import_request(&tampered).is_err());
    }
}
