//! Deep link URL parsing and request validation.
//!
//! The protocol follows the CC Switch `v1/import` shape: the version is the
//! URL host, the action is the path, and all data lives in query parameters.
//! `resource` selects the handler; unknown resources are rejected with a
//! clear message so new link types can be added without breaking old ones.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use tauri::Url;

use super::DEEPLINK_SCHEME;

pub const IMPORT_HOST: &str = "v1";
pub const IMPORT_PATH: &str = "/import";
/// Channel kinds the model configuration store accepts.
pub const SUPPORTED_KINDS: &[&str] = &["official", "relay", "custom"];
/// Default channel kind for links that do not carry one.
pub const DEFAULT_CHANNEL_KIND: &str = "relay";
/// Full set of `app` values the CC Switch `v1/import` contract accepts,
/// including `claude-desktop` (Claude Desktop app import). Birdcoder unifies
/// model configuration, so the value only needs to pass validation.
pub const SUPPORTED_APPS: &[&str] = &[
    "claude",
    "claude-desktop",
    "codex",
    "gemini",
    "grokbuild",
    "opencode",
    "openclaw",
    "hermes",
];

/// Parsed deep link payload forwarded to the webview for confirmation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeepLinkImportRequest {
    /// Unique id of this arrival, generated by the host. The shell uses it
    /// to deduplicate a request delivered both by the cold-start drain and
    /// by the `deep-link-import` event (registration race); the import
    /// handler ignores it.
    #[serde(default)]
    pub id: String,
    /// Protocol version, from the URL host (`v1`).
    pub version: String,
    /// Import target (`provider` today; mcp / prompt / skill / ... later).
    pub resource: String,
    /// Model channel kind: `official` / `relay` / `custom` (default relay).
    pub kind: String,
    /// CC Switch `app` value the link was generated for (validation only).
    pub app: String,
    /// Display name of the imported channel.
    pub name: String,
    /// HTTP(S) API endpoint of the imported channel.
    pub endpoint: String,
    /// API key stored alongside the channel.
    pub api_key: String,
    /// Optional default model id.
    pub model: String,
}

/// Entry point: validates scheme / host / path and dispatches on
/// `resource`. Returns a fully validated request for the confirm dialog.
pub fn parse_deeplink_url(url: &Url) -> Result<DeepLinkImportRequest, String> {
    if url.scheme() != DEEPLINK_SCHEME {
        return Err(format!("unexpected deep link scheme \"{}\"", url.scheme()));
    }
    if url.host_str() != Some(IMPORT_HOST) || url.path() != IMPORT_PATH {
        return Err(format!(
            "unsupported deep link path; expected {DEEPLINK_SCHEME}://{IMPORT_HOST}{IMPORT_PATH}"
        ));
    }

    let params: HashMap<String, String> = url.query_pairs().into_owned().collect();
    let resource = params.get("resource").map(String::as_str).unwrap_or_default();
    match resource {
        "provider" => parse_provider_import_request(&params),
        other => Err(format!(
            "unsupported deep link resource \"{other}\"; only resource=provider is supported for now"
        )),
    }
}

fn parse_provider_import_request(
    params: &HashMap<String, String>,
) -> Result<DeepLinkImportRequest, String> {
    let request = DeepLinkImportRequest {
        // One id per arrival: two clicks on the same link get distinct ids
        // (and import two channels), while the same arrival delivered twice
        // (event + drain) is deduplicated by the shell.
        id: uuid::Uuid::new_v4().to_string(),
        version: IMPORT_HOST.to_owned(),
        resource: "provider".to_owned(),
        kind: params
            .get("kind")
            .map(String::as_str)
            .unwrap_or(DEFAULT_CHANNEL_KIND)
            .to_owned(),
        app: params.get("app").map(String::as_str).unwrap_or_default().to_owned(),
        name: params
            .get("name")
            .map(|value| value.trim())
            .unwrap_or_default()
            .to_owned(),
        endpoint: params.get("endpoint").cloned().unwrap_or_default(),
        api_key: params.get("apiKey").cloned().unwrap_or_default(),
        model: params.get("model").cloned().unwrap_or_default(),
    };
    validate_provider_import_request(&request)?;
    Ok(request)
}

/// Shared provider request validation, run by the parser and re-run by the
/// import handler: the import command is reachable from the webview with
/// arbitrary payloads, so the handler must not trust the dialog's state.
pub fn validate_provider_import_request(request: &DeepLinkImportRequest) -> Result<(), String> {
    if !SUPPORTED_KINDS.contains(&request.kind.as_str()) {
        return Err(format!(
            "unsupported deep link channel kind \"{}\"; expected one of {}",
            request.kind,
            SUPPORTED_KINDS.join(" / ")
        ));
    }
    if !SUPPORTED_APPS.contains(&request.app.as_str()) {
        return Err(format!(
            "unsupported deep link app \"{}\"; expected one of {}",
            request.app,
            SUPPORTED_APPS.join(" / ")
        ));
    }
    if request.name.is_empty() {
        return Err("deep link import is missing the required \"name\" parameter".to_owned());
    }
    let parsed_endpoint = Url::parse(&request.endpoint)
        .map_err(|_| "deep link import is missing a valid \"endpoint\" parameter".to_owned())?;
    if parsed_endpoint.scheme() != "http" && parsed_endpoint.scheme() != "https" {
        return Err("deep link \"endpoint\" must be an HTTP(S) URL".to_owned());
    }
    if request.api_key.is_empty() {
        return Err("deep link import is missing the required \"apiKey\" parameter".to_owned());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{parse_deeplink_url, validate_provider_import_request, DEFAULT_CHANNEL_KIND};
    use crate::host::deeplink::DEEPLINK_SCHEME;
    use tauri::Url;

    fn import_url(query: &str) -> Url {
        Url::parse(&format!("{DEEPLINK_SCHEME}://v1/import?{query}")).unwrap()
    }

    fn provider_query() -> String {
        "resource=provider&app=claude&name=My%20Provider&endpoint=https%3A%2F%2Fapi.example.com&apiKey=sk-test-123&model=claude-sonnet-4"
            .to_owned()
    }

    #[test]
    fn parses_cc_switch_compatible_provider_link() {
        let request = parse_deeplink_url(&import_url(&provider_query())).unwrap();
        assert_eq!(request.version, "v1");
        assert_eq!(request.resource, "provider");
        // Links without a `kind` parameter are relays (backward compatible
        // with the original birdcoder://v1/import contract).
        assert_eq!(request.kind, DEFAULT_CHANNEL_KIND);
        assert_eq!(request.app, "claude");
        assert_eq!(request.name, "My Provider");
        assert_eq!(request.endpoint, "https://api.example.com");
        assert_eq!(request.api_key, "sk-test-123");
        assert_eq!(request.model, "claude-sonnet-4");
    }

    #[test]
    fn parses_explicit_channel_kind() {
        let request = parse_deeplink_url(&import_url(&format!(
            "{}&kind=official",
            provider_query()
        )))
        .unwrap();
        assert_eq!(request.kind, "official");
        let request = parse_deeplink_url(&import_url(&format!(
            "{}&kind=custom",
            provider_query()
        )))
        .unwrap();
        assert_eq!(request.kind, "custom");
    }

    #[test]
    fn rejects_unsupported_resource() {
        let url = import_url("resource=mcp&app=claude&name=X&endpoint=https%3A%2F%2Fapi.example.com&apiKey=sk-test");
        let error = parse_deeplink_url(&url).unwrap_err();
        assert!(error.contains("unsupported deep link resource \"mcp\""), "{error}");
    }

    #[test]
    fn rejects_invalid_kind() {
        let url = import_url(&format!("{}&kind=proxy", provider_query()));
        let error = parse_deeplink_url(&url).unwrap_err();
        assert!(error.contains("unsupported deep link channel kind \"proxy\""), "{error}");
    }

    #[test]
    fn rejects_unsupported_app() {
        let url = import_url("resource=provider&app=notepad&name=X&endpoint=https%3A%2F%2Fapi.example.com&apiKey=sk-test");
        let error = parse_deeplink_url(&url).unwrap_err();
        assert!(error.contains("unsupported deep link app \"notepad\""), "{error}");
    }

    #[test]
    fn rejects_missing_name_or_key() {
        let url = import_url("resource=provider&app=claude&endpoint=https%3A%2F%2Fapi.example.com&apiKey=sk-test");
        assert!(parse_deeplink_url(&url).is_err());
        let url = import_url("resource=provider&app=claude&name=X&endpoint=https%3A%2F%2Fapi.example.com");
        assert!(parse_deeplink_url(&url).is_err());
    }

    #[test]
    fn rejects_non_http_endpoint() {
        let url = import_url("resource=provider&app=claude&name=X&endpoint=file%3A%2F%2F%2Fetc%2Fpasswd&apiKey=sk-test");
        let error = parse_deeplink_url(&url).unwrap_err();
        assert!(error.contains("must be an HTTP(S) URL"), "{error}");
    }

    #[test]
    fn rejects_wrong_scheme_or_path() {
        let wrong_scheme = Url::parse("ccswitch://v1/import?resource=provider").unwrap();
        assert!(parse_deeplink_url(&wrong_scheme).is_err());
        let wrong_path = Url::parse("birdcoder://v1/config?resource=provider").unwrap();
        assert!(parse_deeplink_url(&wrong_path).is_err());
    }

    #[test]
    fn revalidates_webview_supplied_request() {
        // The import command accepts arbitrary payloads from the webview;
        // the shared validator must reject each tampered field.
        let base = parse_deeplink_url(&import_url(&provider_query())).unwrap();
        let mut tampered = base.clone();
        tampered.kind = "proxy".to_owned();
        assert!(validate_provider_import_request(&tampered).is_err());
        tampered = base.clone();
        tampered.endpoint = "file:///etc/passwd".to_owned();
        assert!(validate_provider_import_request(&tampered).is_err());
        tampered = base.clone();
        tampered.api_key.clear();
        assert!(validate_provider_import_request(&tampered).is_err());
        tampered = base.clone();
        tampered.name.clear();
        assert!(validate_provider_import_request(&tampered).is_err());
    }
}
