import {
  type TauriProjectRuntimeLocationBinding,
  ProjectDeviceMountRegistry,
} from '../services/ProjectDeviceMountRegistry.ts';
import type {
  DesktopRuntimeLocationBindingIdentity,
  DesktopRuntimeLocationIdentityPort,
} from '../services/interfaces/IDesktopRuntimeLocationIdentityPort.ts';
import {
  isBirdCoderTauriRuntime,
  resolveBirdCoderTauriInvoke,
  type BirdCoderTauriInvoke,
} from './tauriRuntime.ts';

const DESKTOP_RUNTIME_TARGET_ID_PATTERN =
  /^desktop-device:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/iu;
const DESKTOP_RUNTIME_ROOT_LOCATOR_PATTERN =
  /^desktop-root:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/iu;

interface DesktopRuntimeLocationInstallIdentityResponse {
  runtimeTargetId: string;
}

export interface TauriDesktopRuntimeLocationIdentityPortOptions {
  invoke?: () => Promise<BirdCoderTauriInvoke | null>;
  isTauriRuntime?: () => Promise<boolean>;
  mountRegistry: ProjectDeviceMountRegistry;
}

function resolveDesktopPathFlavor(path: string): 'windows' | 'posix' {
  const normalizedPath = path.trim();
  if (/^[a-zA-Z]:[\\/]/u.test(normalizedPath) || normalizedPath.startsWith('\\\\')) {
    return 'windows';
  }
  if (normalizedPath.startsWith('/')) {
    return 'posix';
  }

  throw new Error('A desktop runtime location requires an absolute native path.');
}

function readInstallRuntimeTargetId(value: unknown): string {
  if (
    !value ||
    typeof value !== 'object' ||
    !DESKTOP_RUNTIME_TARGET_ID_PATTERN.test(
      (value as Partial<DesktopRuntimeLocationInstallIdentityResponse>).runtimeTargetId ?? '',
    )
  ) {
    throw new Error('The desktop host returned an invalid runtime target identity.');
  }

  return (value as DesktopRuntimeLocationInstallIdentityResponse).runtimeTargetId;
}

function readRootLocator(value: unknown): string {
  const rootLocator = typeof value === 'string' ? value.trim() : '';
  if (!DESKTOP_RUNTIME_ROOT_LOCATOR_PATTERN.test(rootLocator)) {
    throw new Error('The desktop host returned an invalid runtime root locator.');
  }

  return rootLocator;
}

function toIdentity(
  runtimeTargetId: string,
  pathFlavor: DesktopRuntimeLocationBindingIdentity['pathFlavor'],
  binding: TauriProjectRuntimeLocationBinding,
): DesktopRuntimeLocationBindingIdentity | null {
  if (!binding.rootLocator) {
    return null;
  }

  return {
    displayName: binding.displayName,
    locationKind: 'local_directory',
    pathFlavor,
    requiresRebind: binding.requiresRebind,
    rootLocator: binding.rootLocator,
    runtimeLocationCreateGeneration: binding.runtimeLocationCreateGeneration,
    ...(binding.runtimeLocationId ? { runtimeLocationId: binding.runtimeLocationId } : {}),
    ...(binding.runtimeLocationVersion
      ? { runtimeLocationVersion: binding.runtimeLocationVersion }
      : {}),
    runtimeTargetId,
    runtimeTargetKind: 'desktop',
  };
}

/**
 * Tauri-only runtime identity adapter. Random opaque values are generated by
 * the native host and associated with a subject-scoped durable mount record.
 */
export class TauriDesktopRuntimeLocationIdentityPort
  implements DesktopRuntimeLocationIdentityPort {
  private readonly invoke: () => Promise<BirdCoderTauriInvoke | null>;
  private readonly isTauriRuntime: () => Promise<boolean>;
  private readonly mountRegistry: ProjectDeviceMountRegistry;

  constructor({
    invoke = resolveBirdCoderTauriInvoke,
    isTauriRuntime = isBirdCoderTauriRuntime,
    mountRegistry,
  }: TauriDesktopRuntimeLocationIdentityPortOptions) {
    this.invoke = invoke;
    this.isTauriRuntime = isTauriRuntime;
    this.mountRegistry = mountRegistry;
  }

  async resolveDesktopRuntimeLocationBinding(input: {
    absolutePath: string;
    projectId: string;
  }): Promise<DesktopRuntimeLocationBindingIdentity | null> {
    if (!(await this.isTauriRuntime())) {
      return null;
    }

    const pathFlavor = resolveDesktopPathFlavor(input.absolutePath);
    const subjectKey = await this.mountRegistry.getCurrentSubjectKey();
    if (!subjectKey) {
      return null;
    }

    const invoke = await this.invoke();
    if (!invoke) {
      return null;
    }

    const runtimeTargetId = readInstallRuntimeTargetId(
      await invoke<DesktopRuntimeLocationInstallIdentityResponse>(
        'desktop_runtime_location_install_identity',
      ),
    );
    let binding = await this.mountRegistry.resolveTauriRuntimeLocationBinding({
      absolutePath: input.absolutePath,
      expectedSubjectKey: subjectKey,
      projectId: input.projectId,
    });
    if (!binding) {
      return null;
    }

    if (!binding.rootLocator) {
      const rootLocator = readRootLocator(
        await invoke<string>('desktop_runtime_location_create_root_locator'),
      );
      binding = await this.mountRegistry.ensureTauriRuntimeLocationRootLocator({
        absolutePath: input.absolutePath,
        expectedSubjectKey: subjectKey,
        projectId: input.projectId,
        rootLocator,
      });
    }

    return binding ? toIdentity(runtimeTargetId, pathFlavor, binding) : null;
  }

  async persistRemoteRuntimeLocationBinding(input: {
    absolutePath: string;
    projectId: string;
    rootLocator: string;
    runtimeLocationId: string;
    runtimeLocationVersion: string;
  }): Promise<void> {
    if (!(await this.isTauriRuntime())) {
      throw new Error('Desktop runtime location persistence is unavailable outside Tauri.');
    }

    const subjectKey = await this.mountRegistry.getCurrentSubjectKey();
    if (!subjectKey) {
      throw new Error('Sign in before persisting a desktop runtime location binding.');
    }

    const persisted = await this.mountRegistry.persistTauriRuntimeLocationRemoteBinding({
      ...input,
      expectedSubjectKey: subjectKey,
    });
    if (!persisted) {
      throw new Error('The desktop runtime location binding could not be retained locally.');
    }
  }

  async clearRemoteRuntimeLocationBinding(input: {
    absolutePath: string;
    projectId: string;
    rootLocator: string;
  }): Promise<void> {
    if (!(await this.isTauriRuntime())) {
      throw new Error('Desktop runtime location persistence is unavailable outside Tauri.');
    }

    const subjectKey = await this.mountRegistry.getCurrentSubjectKey();
    if (!subjectKey) {
      throw new Error('Sign in before clearing a desktop runtime location binding.');
    }

    const cleared = await this.mountRegistry.clearTauriRuntimeLocationRemoteBinding({
      ...input,
      expectedSubjectKey: subjectKey,
    });
    if (cleared === null) {
      throw new Error('The stale desktop runtime location binding could not be cleared locally.');
    }
  }
}

export { resolveDesktopPathFlavor };
