import type { editor } from 'monaco-editor';

export const BIRDCODER_EDITOR_THEME_ID = 'birdcoder-dark-professional';

export const BIRDCODER_EDITOR_THEME: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '7D8590', fontStyle: 'italic' },
    { token: 'comment.doc', foreground: '8B949E', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'FF7B72' },
    { token: 'keyword.control', foreground: 'FF7B72' },
    { token: 'keyword.operator', foreground: '79C0FF' },
    { token: 'operator', foreground: '79C0FF' },
    { token: 'delimiter', foreground: 'B1BAC4' },
    { token: 'delimiter.bracket', foreground: 'D2A8FF' },
    { token: 'string', foreground: 'A5D6FF' },
    { token: 'string.quote', foreground: 'A5D6FF' },
    { token: 'string.escape', foreground: '79C0FF', fontStyle: 'bold' },
    { token: 'regexp', foreground: '7EE787' },
    { token: 'number', foreground: '79C0FF' },
    { token: 'number.hex', foreground: '79C0FF' },
    { token: 'number.float', foreground: '79C0FF' },
    { token: 'type', foreground: '7EE787' },
    { token: 'type.identifier', foreground: '7EE787' },
    { token: 'typeParameter', foreground: '7EE787' },
    { token: 'class', foreground: '7EE787' },
    { token: 'interface', foreground: '7EE787' },
    { token: 'namespace', foreground: '7EE787' },
    { token: 'function', foreground: 'D2A8FF' },
    { token: 'function.call', foreground: 'D2A8FF' },
    { token: 'method', foreground: 'D2A8FF' },
    { token: 'constructor', foreground: 'D2A8FF' },
    { token: 'variable', foreground: 'FFA657' },
    { token: 'variable.predefined', foreground: 'FFA657' },
    { token: 'parameter', foreground: 'FFA657' },
    { token: 'constant', foreground: '79C0FF' },
    { token: 'constant.language', foreground: '79C0FF' },
    { token: 'annotation', foreground: 'D2A8FF' },
    { token: 'tag', foreground: '7EE787' },
    { token: 'metatag', foreground: 'FF7B72' },
    { token: 'attribute.name', foreground: 'D2A8FF' },
    { token: 'attribute.value', foreground: 'A5D6FF' },
    { token: 'key', foreground: '79C0FF' },
    { token: 'invalid', foreground: 'F0F6FC', background: 'F8514966' },
  ],
  colors: {
    'editor.background': '#0D1117',
    'editor.foreground': '#E6EDF3',
    'editorGutter.background': '#0D1117',
    'editorLineNumber.foreground': '#6E7681',
    'editorLineNumber.activeForeground': '#E6EDF3',
    'editorCursor.foreground': '#58A6FF',
    'editor.selectionBackground': '#1F6FEB66',
    'editor.inactiveSelectionBackground': '#1F6FEB33',
    'editor.selectionHighlightBackground': '#3D444D66',
    'editor.wordHighlightBackground': '#BB800933',
    'editor.wordHighlightStrongBackground': '#BB800955',
    'editor.findMatchBackground': '#9E6A03AA',
    'editor.findMatchHighlightBackground': '#BB800955',
    'editor.findRangeHighlightBackground': '#1F6FEB22',
    'editor.lineHighlightBackground': '#161B22',
    'editor.lineHighlightBorder': '#21262D00',
    'editorWhitespace.foreground': '#484F5866',
    'editorIndentGuide.background1': '#21262D',
    'editorIndentGuide.activeBackground1': '#484F58',
    'editorBracketMatch.background': '#1F6FEB33',
    'editorBracketMatch.border': '#58A6FF',
    'editorBracketHighlight.foreground1': '#FFD700',
    'editorBracketHighlight.foreground2': '#DA70D6',
    'editorBracketHighlight.foreground3': '#179FFF',
    'editorBracketHighlight.foreground4': '#7EE787',
    'editorBracketHighlight.foreground5': '#FFA657',
    'editorBracketHighlight.foreground6': '#FF7B72',
    'editorError.foreground': '#F85149',
    'editorWarning.foreground': '#D29922',
    'editorInfo.foreground': '#58A6FF',
    'editorHint.foreground': '#8B949E',
    'editorLink.activeForeground': '#58A6FF',
    'editorCodeLens.foreground': '#8B949E',
    'editorInlayHint.foreground': '#8B949E',
    'editorInlayHint.background': '#161B22',
    'editorWidget.background': '#161B22',
    'editorWidget.border': '#30363D',
    'editorHoverWidget.background': '#161B22',
    'editorHoverWidget.border': '#30363D',
    'editorSuggestWidget.background': '#161B22',
    'editorSuggestWidget.border': '#30363D',
    'editorSuggestWidget.foreground': '#E6EDF3',
    'editorSuggestWidget.highlightForeground': '#58A6FF',
    'editorSuggestWidget.selectedBackground': '#1F6FEB55',
    'editorStickyScroll.background': '#0D1117',
    'editorStickyScroll.border': '#21262D',
    'editorOverviewRuler.border': '#0D111700',
    'minimap.background': '#0D1117',
    'minimap.selectionHighlight': '#58A6FF66',
    'scrollbarSlider.background': '#6E768133',
    'scrollbarSlider.hoverBackground': '#8B949E55',
    'scrollbarSlider.activeBackground': '#B1BAC466',
    'diffEditor.insertedTextBackground': '#2EA04333',
    'diffEditor.removedTextBackground': '#F8514933',
    'diffEditor.insertedLineBackground': '#2EA04318',
    'diffEditor.removedLineBackground': '#F8514918',
    'diffEditor.diagonalFill': '#30363D',
  },
};
