use sdkwork_web_contract::{HttpMethod, HttpRoute};
use sdkwork_web_core::HttpRouteManifest;

use crate::paths;

pub const WORKSPACE_APP_API_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::WORKSPACES_PATH,
        "workspaces",
        "workspaces.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::WORKSPACES_PATH,
        "workspaces",
        "workspaces.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::WORKSPACE_DETAIL_PATH,
        "workspaces",
        "workspaces.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        paths::WORKSPACE_DETAIL_PATH,
        "workspaces",
        "workspaces.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::WORKSPACE_DETAIL_PATH,
        "workspaces",
        "workspaces.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::WORKSPACE_REALTIME_PATH,
        "workspaces",
        "workspaces.realtime.subscribe",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::WORKSPACE_MEMBERS_PATH,
        "workspaces",
        "workspaces.members.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::WORKSPACE_MEMBERS_PATH,
        "workspaces",
        "workspaces.members.upsert",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECTS_PATH,
        "projects",
        "projects.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECTS_PATH,
        "projects",
        "projects.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_DETAIL_PATH,
        "projects",
        "projects.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        paths::PROJECT_DETAIL_PATH,
        "projects",
        "projects.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::PROJECT_DETAIL_PATH,
        "projects",
        "projects.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_GIT_OVERVIEW_PATH,
        "projects",
        "projects.git.overview.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_BRANCHES_PATH,
        "projects",
        "projects.git.branches.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_BRANCH_SWITCH_PATH,
        "projects",
        "projects.git.branchSwitch.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_COMMITS_PATH,
        "projects",
        "projects.git.commits.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_PUSHES_PATH,
        "projects",
        "projects.git.pushes.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_WORKTREES_PATH,
        "projects",
        "projects.git.worktrees.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_WORKTREE_REMOVALS_PATH,
        "projects",
        "projects.git.worktreeRemovals.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_GIT_WORKTREE_PRUNE_PATH,
        "projects",
        "projects.git.worktreePrune.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::PROJECT_COLLABORATORS_PATH,
        "projects",
        "projects.collaborators.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_COLLABORATORS_PATH,
        "projects",
        "projects.collaborators.upsert",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::DEPLOYMENTS_PATH,
        "deployments",
        "deployments.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::PROJECT_PUBLISH_PATH,
        "projects",
        "projects.publish.create",
    ),
];

pub fn workspace_app_api_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(WORKSPACE_APP_API_ROUTES)
}
