name: sdkwork_birdcoder_flutter_mobile_console_core
description: SDKWork Birdcoder Flutter Mobile Console Core
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
