// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-backend-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkOperationDescriptor,
  BirdcoderSdkQueryValue,
} from '../types';

export const AUTHORIZATION_HEADER = 'Authorization';
export const SDKWORK_ACCESS_TOKEN_HEADER = 'Sdkwork-Access-Token';

export interface BirdcoderSdkTransportRequest {
  body?: unknown;
  headers?: Record<string, string | undefined>;
  method: BirdcoderSdkOperationDescriptor['method'];
  path: string;
  query?: Record<string, BirdcoderSdkQueryValue>;
}

export interface BirdcoderSdkTransport {
  request<TResponse>(request: BirdcoderSdkTransportRequest): Promise<TResponse>;
}

export interface BirdcoderSdkAuthTokens {
  accessToken?: string;
  authToken?: string;
}

export interface BirdcoderSdkRequestOptions {
  headers?: Record<string, string | undefined>;
}

export type BirdcoderSdkRequestOperation = <TResponse>(
  operationKey: string,
  args?: {
    body?: unknown;
    pathParams?: object;
    query?: Record<string, BirdcoderSdkQueryValue>;
  },
  requestOptions?: BirdcoderSdkRequestOptions,
) => Promise<TResponse>;

export interface CreateBirdcoderSdkOperationRequesterOptions {
  accessToken?: string;
  authToken?: string;
  operationIndex: Record<string, BirdcoderSdkOperationDescriptor>;
  surface: string;
  transport: BirdcoderSdkTransport;
}

export interface BirdcoderSdkOperationRequester {
  clearSdkworkAuthTokens(): void;
  requestOperation: BirdcoderSdkRequestOperation;
  setSdkworkAuthTokens(tokens: BirdcoderSdkAuthTokens): void;
}

export function createBirdcoderSdkOperationRequester({
  accessToken,
  authToken,
  operationIndex,
  surface,
  transport,
}: CreateBirdcoderSdkOperationRequesterOptions): BirdcoderSdkOperationRequester {
  let authTokens: BirdcoderSdkAuthTokens = {
    accessToken,
    authToken,
  };

  function buildSdkworkAuthHeaders(): Record<string, string | undefined> {
    return {
      [AUTHORIZATION_HEADER]: authTokens.authToken ? `Bearer ${authTokens.authToken}` : undefined,
      [SDKWORK_ACCESS_TOKEN_HEADER]: authTokens.accessToken,
    };
  }

  function resolveOperationPath(
    operation: BirdcoderSdkOperationDescriptor,
    pathParams: object = {},
  ): string {
    return operation.pathParamNames.reduce((currentPath, name) => {
      const value = (pathParams as Record<string, string>)[name];
      if (!value) {
        throw new Error(`Missing required path parameter "${name}" for ${operation.key}.`);
      }
      return currentPath.replace(`{${name}}`, encodeURIComponent(value));
    }, operation.path);
  }

  function requestOperation<TResponse>(
    operationKey: string,
    args: {
      body?: unknown;
      pathParams?: object;
      query?: Record<string, BirdcoderSdkQueryValue>;
    } = {},
    requestOptions: BirdcoderSdkRequestOptions = {},
  ): Promise<TResponse> {
    const operation = operationIndex[operationKey];
    if (!operation) {
      throw new Error(`Unknown BirdCoder ${surface} SDK operation: ${operationKey}.`);
    }

    const request: BirdcoderSdkTransportRequest = {
      headers: {
        ...buildSdkworkAuthHeaders(),
        ...requestOptions.headers,
      },
      method: operation.method,
      path: resolveOperationPath(operation, args.pathParams),
    };
    if (args.body !== undefined) {
      request.body = args.body;
    }
    if (args.query !== undefined) {
      request.query = args.query;
    }
    return transport.request<TResponse>(request);
  }

  return {
    clearSdkworkAuthTokens() {
      authTokens = {};
    },
    requestOperation,
    setSdkworkAuthTokens(tokens: BirdcoderSdkAuthTokens) {
      authTokens = { ...tokens };
    },
  };
}
