// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-backend-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http/index.ts';
import type * as Types from '../types/index.ts';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type PlatformProjectsDeploymentTargetsListPathParams = Types.PlatformProjectsDeploymentTargetsListPathParams;
type PlatformProjectsDeploymentTargetsListQuery = Types.PlatformProjectsDeploymentTargetsListQuery;

export interface PlatformApi {
  deploymentGovernance: {
    list(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderDeploymentRecordSummaryListEnvelope>;
  };
  projects: {
    deploymentTargets: {
      list(pathParams: PlatformProjectsDeploymentTargetsListPathParams, query?: PlatformProjectsDeploymentTargetsListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderDeploymentTargetSummaryListEnvelope>;
    };
  };
  releases: {
    list(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderReleaseSummaryListEnvelope>;
  };
}

export function createPlatformApi(requestOperation: BirdcoderSdkRequestOperation): PlatformApi {
  return {
    deploymentGovernance: {
      list(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderDeploymentRecordSummaryListEnvelope>("platform.deploymentGovernance.list", {}, options);
      }
    },
    projects: {
      deploymentTargets: {
        list(pathParams: PlatformProjectsDeploymentTargetsListPathParams, query: PlatformProjectsDeploymentTargetsListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderDeploymentTargetSummaryListEnvelope>("platform.projects.deploymentTargets.list", { pathParams, query }, options);
        }
      }
    },
    releases: {
      list(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderReleaseSummaryListEnvelope>("platform.releases.list", {}, options);
      }
    }
  };
}
