// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http/index.ts';
import type * as Types from '../types/index.ts';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;


export interface AuthApi {
  passwordResetRequests: {
    create(body: Types.BirdCoderIamPasswordResetRequestCreateRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderBooleanSuccessEnvelope>;
  };
  passwordResets: {
    create(body: Types.BirdCoderIamPasswordResetCreateRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderBooleanSuccessEnvelope>;
  };
  registrations: {
    create(body: Types.BirdCoderIamRegistrationCreateRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamSessionEnvelope>;
  };
  sessions: {
    create(body: Types.BirdCoderIamCreateSessionRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamSessionEnvelope>;
    current: {
      delete(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderBooleanSuccessEnvelope>;
      retrieve(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamSessionEnvelope>;
      update(body: Types.BirdCoderIamUpdateCurrentSessionRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamSessionEnvelope>;
    };
    refresh(body: Types.BirdCoderIamRefreshSessionRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamSessionEnvelope>;
  };
}

export function createAuthApi(requestOperation: BirdcoderSdkRequestOperation): AuthApi {
  return {
    passwordResetRequests: {
      create(body: Types.BirdCoderIamPasswordResetRequestCreateRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderBooleanSuccessEnvelope>("auth.passwordResetRequests.create", { body }, options);
      }
    },
    passwordResets: {
      create(body: Types.BirdCoderIamPasswordResetCreateRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderBooleanSuccessEnvelope>("auth.passwordResets.create", { body }, options);
      }
    },
    registrations: {
      create(body: Types.BirdCoderIamRegistrationCreateRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderIamSessionEnvelope>("auth.registrations.create", { body }, options);
      }
    },
    sessions: {
      create(body: Types.BirdCoderIamCreateSessionRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderIamSessionEnvelope>("auth.sessions.create", { body }, options);
      },
      current: {
        delete(options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderBooleanSuccessEnvelope>("auth.sessions.current.delete", {}, options);
        },
        retrieve(options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamSessionEnvelope>("auth.sessions.current.retrieve", {}, options);
        },
        update(body: Types.BirdCoderIamUpdateCurrentSessionRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamSessionEnvelope>("auth.sessions.current.update", { body }, options);
        }
      },
      refresh(body: Types.BirdCoderIamRefreshSessionRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderIamSessionEnvelope>("auth.sessions.refresh", { body }, options);
      }
    }
  };
}
