// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http/index.ts';
import type * as Types from '../types/index.ts';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type IamWorkspacesMembersListPathParams = Types.IamWorkspacesMembersListPathParams;
type IamWorkspacesMembersListQuery = Types.IamWorkspacesMembersListQuery;
type IamWorkspacesMembersUpsertPathParams = Types.IamWorkspacesMembersUpsertPathParams;

export interface IamApi {
  organizationMemberships: {
    list(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamOrganizationMemberSummaryListEnvelope>;
  };
  organizations: {
    list(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamOrganizationSummaryListEnvelope>;
    tree: {
      retrieve(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamOrganizationSummaryListEnvelope>;
    };
  };
  roleBindings: {
    list(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamUserRoleSummaryListEnvelope>;
  };
  users: {
    current: {
      retrieve(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamUserProfileEnvelope>;
      update(body: Types.BirdCoderUpdateCurrentUserProfileRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamUserProfileEnvelope>;
    };
  };
  workspaces: {
    members: {
      list(pathParams: IamWorkspacesMembersListPathParams, query?: IamWorkspacesMembersListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderWorkspaceMemberSummaryListEnvelope>;
      upsert(pathParams: IamWorkspacesMembersUpsertPathParams, body: Types.BirdCoderUpsertWorkspaceMemberRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderWorkspaceMemberSummaryEnvelope>;
    };
  };
}

export function createIamApi(requestOperation: BirdcoderSdkRequestOperation): IamApi {
  return {
    organizationMemberships: {
      list(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderIamOrganizationMemberSummaryListEnvelope>("iam.organizationMemberships.list", {}, options);
      }
    },
    organizations: {
      list(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderIamOrganizationSummaryListEnvelope>("iam.organizations.list", {}, options);
      },
      tree: {
        retrieve(options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamOrganizationSummaryListEnvelope>("iam.organizations.tree.retrieve", {}, options);
        }
      }
    },
    roleBindings: {
      list(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderIamUserRoleSummaryListEnvelope>("iam.roleBindings.list", {}, options);
      }
    },
    users: {
      current: {
        retrieve(options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamUserProfileEnvelope>("iam.users.current.retrieve", {}, options);
        },
        update(body: Types.BirdCoderUpdateCurrentUserProfileRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamUserProfileEnvelope>("iam.users.current.update", { body }, options);
        }
      }
    },
    workspaces: {
      members: {
        list(pathParams: IamWorkspacesMembersListPathParams, query: IamWorkspacesMembersListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderWorkspaceMemberSummaryListEnvelope>("iam.workspaces.members.list", { pathParams, query }, options);
        },
        upsert(pathParams: IamWorkspacesMembersUpsertPathParams, body: Types.BirdCoderUpsertWorkspaceMemberRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderWorkspaceMemberSummaryEnvelope>("iam.workspaces.members.upsert", { pathParams, body }, options);
        }
      }
    }
  };
}
