// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http/index.ts';
import type * as Types from '../types/index.ts';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type IntelligenceCodingSessionsArtifactsListPathParams = Types.IntelligenceCodingSessionsArtifactsListPathParams;
type IntelligenceCodingSessionsCheckpointsApprovalCreatePathParams = Types.IntelligenceCodingSessionsCheckpointsApprovalCreatePathParams;
type IntelligenceCodingSessionsCheckpointsListPathParams = Types.IntelligenceCodingSessionsCheckpointsListPathParams;
type IntelligenceCodingSessionsDeletePathParams = Types.IntelligenceCodingSessionsDeletePathParams;
type IntelligenceCodingSessionsEventsListPathParams = Types.IntelligenceCodingSessionsEventsListPathParams;
type IntelligenceCodingSessionsForksCreatePathParams = Types.IntelligenceCodingSessionsForksCreatePathParams;
type IntelligenceCodingSessionsListQuery = Types.IntelligenceCodingSessionsListQuery;
type IntelligenceCodingSessionsMessagesDeletePathParams = Types.IntelligenceCodingSessionsMessagesDeletePathParams;
type IntelligenceCodingSessionsMessagesUpdatePathParams = Types.IntelligenceCodingSessionsMessagesUpdatePathParams;
type IntelligenceCodingSessionsQuestionsAnswersCreatePathParams = Types.IntelligenceCodingSessionsQuestionsAnswersCreatePathParams;
type IntelligenceCodingSessionsRetrievePathParams = Types.IntelligenceCodingSessionsRetrievePathParams;
type IntelligenceCodingSessionsTurnsCreatePathParams = Types.IntelligenceCodingSessionsTurnsCreatePathParams;
type IntelligenceCodingSessionsUpdatePathParams = Types.IntelligenceCodingSessionsUpdatePathParams;

export interface IntelligenceApi {
  codingSessions: {
    artifacts: {
      list(pathParams: IntelligenceCodingSessionsArtifactsListPathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderCodingSessionArtifactListEnvelope>;
    };
    checkpoints: {
      approval: {
        create(pathParams: IntelligenceCodingSessionsCheckpointsApprovalCreatePathParams, body: Types.BirdCoderSubmitApprovalDecisionRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderApprovalDecisionResultEnvelope>;
      };
      list(pathParams: IntelligenceCodingSessionsCheckpointsListPathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderCodingSessionCheckpointListEnvelope>;
    };
    create(body: Types.BirdCoderCreateCodingSessionRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderCodingSessionSummaryEnvelope>;
    delete(pathParams: IntelligenceCodingSessionsDeletePathParams, options?: BirdcoderSdkRequestOptions): Promise<void>;
    events: {
      list(pathParams: IntelligenceCodingSessionsEventsListPathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderCodingSessionEventListEnvelope>;
    };
    forks: {
      create(pathParams: IntelligenceCodingSessionsForksCreatePathParams, body: Types.BirdCoderForkCodingSessionRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderCodingSessionSummaryEnvelope>;
    };
    list(query?: IntelligenceCodingSessionsListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderCodingSessionSummaryListEnvelope>;
    messages: {
      delete(pathParams: IntelligenceCodingSessionsMessagesDeletePathParams, options?: BirdcoderSdkRequestOptions): Promise<void>;
      update(pathParams: IntelligenceCodingSessionsMessagesUpdatePathParams, body: Types.BirdCoderEditCodingSessionMessageRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderEditCodingSessionMessageResultEnvelope>;
    };
    questions: {
      answers: {
        create(pathParams: IntelligenceCodingSessionsQuestionsAnswersCreatePathParams, body: Types.BirdCoderSubmitUserQuestionAnswerRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderUserQuestionAnswerResultEnvelope>;
      };
    };
    retrieve(pathParams: IntelligenceCodingSessionsRetrievePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderCodingSessionSummaryEnvelope>;
    turns: {
      create(pathParams: IntelligenceCodingSessionsTurnsCreatePathParams, body: Types.BirdCoderCreateCodingSessionTurnRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderCodingSessionTurnEnvelope>;
    };
    update(pathParams: IntelligenceCodingSessionsUpdatePathParams, body: Types.BirdCoderUpdateCodingSessionRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderCodingSessionSummaryEnvelope>;
  };
}

export function createIntelligenceApi(requestOperation: BirdcoderSdkRequestOperation): IntelligenceApi {
  return {
    codingSessions: {
      artifacts: {
        list(pathParams: IntelligenceCodingSessionsArtifactsListPathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderCodingSessionArtifactListEnvelope>("intelligence.codingSessions.artifacts.list", { pathParams }, options);
        }
      },
      checkpoints: {
        approval: {
          create(pathParams: IntelligenceCodingSessionsCheckpointsApprovalCreatePathParams, body: Types.BirdCoderSubmitApprovalDecisionRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderApprovalDecisionResultEnvelope>("intelligence.codingSessions.checkpoints.approval.create", { pathParams, body }, options);
          }
        },
        list(pathParams: IntelligenceCodingSessionsCheckpointsListPathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderCodingSessionCheckpointListEnvelope>("intelligence.codingSessions.checkpoints.list", { pathParams }, options);
        }
      },
      create(body: Types.BirdCoderCreateCodingSessionRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderCodingSessionSummaryEnvelope>("intelligence.codingSessions.create", { body }, options);
      },
      delete(pathParams: IntelligenceCodingSessionsDeletePathParams, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<void>("intelligence.codingSessions.delete", { pathParams }, options);
      },
      events: {
        list(pathParams: IntelligenceCodingSessionsEventsListPathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderCodingSessionEventListEnvelope>("intelligence.codingSessions.events.list", { pathParams }, options);
        }
      },
      forks: {
        create(pathParams: IntelligenceCodingSessionsForksCreatePathParams, body: Types.BirdCoderForkCodingSessionRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderCodingSessionSummaryEnvelope>("intelligence.codingSessions.forks.create", { pathParams, body }, options);
        }
      },
      list(query: IntelligenceCodingSessionsListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderCodingSessionSummaryListEnvelope>("intelligence.codingSessions.list", { query }, options);
      },
      messages: {
        delete(pathParams: IntelligenceCodingSessionsMessagesDeletePathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<void>("intelligence.codingSessions.messages.delete", { pathParams }, options);
        },
        update(pathParams: IntelligenceCodingSessionsMessagesUpdatePathParams, body: Types.BirdCoderEditCodingSessionMessageRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderEditCodingSessionMessageResultEnvelope>("intelligence.codingSessions.messages.update", { pathParams, body }, options);
        }
      },
      questions: {
        answers: {
          create(pathParams: IntelligenceCodingSessionsQuestionsAnswersCreatePathParams, body: Types.BirdCoderSubmitUserQuestionAnswerRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderUserQuestionAnswerResultEnvelope>("intelligence.codingSessions.questions.answers.create", { pathParams, body }, options);
          }
        }
      },
      retrieve(pathParams: IntelligenceCodingSessionsRetrievePathParams, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderCodingSessionSummaryEnvelope>("intelligence.codingSessions.retrieve", { pathParams }, options);
      },
      turns: {
        create(pathParams: IntelligenceCodingSessionsTurnsCreatePathParams, body: Types.BirdCoderCreateCodingSessionTurnRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderCodingSessionTurnEnvelope>("intelligence.codingSessions.turns.create", { pathParams, body }, options);
        }
      },
      update(pathParams: IntelligenceCodingSessionsUpdatePathParams, body: Types.BirdCoderUpdateCodingSessionRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderCodingSessionSummaryEnvelope>("intelligence.codingSessions.update", { pathParams, body }, options);
      }
    }
  };
}
