// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http/index.ts';
import type * as Types from '../types/index.ts';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type OauthDeviceAuthorizationsPasswordCompletionsCreatePathParams = Types.OauthDeviceAuthorizationsPasswordCompletionsCreatePathParams;
type OauthDeviceAuthorizationsRetrievePathParams = Types.OauthDeviceAuthorizationsRetrievePathParams;
type OauthDeviceAuthorizationsScansCreatePathParams = Types.OauthDeviceAuthorizationsScansCreatePathParams;

export interface OauthApi {
  oauth: {
    authorizationUrls: {
      create(body: Types.BirdCoderIamOAuthAuthorizationCreateRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamOAuthAuthorizationEnvelope>;
    };
    deviceAuthorizations: {
      create(body: Types.BirdCoderIamDeviceAuthorizationCreateRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamDeviceAuthorizationEnvelope>;
      passwordCompletions: {
        create(pathParams: OauthDeviceAuthorizationsPasswordCompletionsCreatePathParams, body: Types.BirdCoderIamDeviceAuthorizationPasswordCompletionRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamSessionEnvelope>;
      };
      retrieve(pathParams: OauthDeviceAuthorizationsRetrievePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamDeviceAuthorizationEnvelope>;
      scans: {
        create(pathParams: OauthDeviceAuthorizationsScansCreatePathParams, body: Types.BirdCoderIamDeviceAuthorizationScanRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderBooleanSuccessEnvelope>;
      };
    };
    sessions: {
      create(body: Types.BirdCoderIamOAuthSessionCreateRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamSessionEnvelope>;
    };
  };
}

export function createOauthApi(requestOperation: BirdcoderSdkRequestOperation): OauthApi {
  return {
    oauth: {
      authorizationUrls: {
        create(body: Types.BirdCoderIamOAuthAuthorizationCreateRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamOAuthAuthorizationEnvelope>("oauth.authorizationUrls.create", { body }, options);
        }
      },
      deviceAuthorizations: {
        create(body: Types.BirdCoderIamDeviceAuthorizationCreateRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamDeviceAuthorizationEnvelope>("oauth.deviceAuthorizations.create", { body }, options);
        },
        passwordCompletions: {
          create(pathParams: OauthDeviceAuthorizationsPasswordCompletionsCreatePathParams, body: Types.BirdCoderIamDeviceAuthorizationPasswordCompletionRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderIamSessionEnvelope>("oauth.deviceAuthorizations.passwordCompletions.create", { pathParams, body }, options);
          }
        },
        retrieve(pathParams: OauthDeviceAuthorizationsRetrievePathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamDeviceAuthorizationEnvelope>("oauth.deviceAuthorizations.retrieve", { pathParams }, options);
        },
        scans: {
          create(pathParams: OauthDeviceAuthorizationsScansCreatePathParams, body: Types.BirdCoderIamDeviceAuthorizationScanRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderBooleanSuccessEnvelope>("oauth.deviceAuthorizations.scans.create", { pathParams, body }, options);
          }
        }
      },
      sessions: {
        create(body: Types.BirdCoderIamOAuthSessionCreateRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamSessionEnvelope>("oauth.sessions.create", { body }, options);
        }
      }
    }
  };
}
