// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http/index.ts';
import type * as Types from '../types/index.ts';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type RuntimeEnginesCapabilitiesRetrievePathParams = Types.RuntimeEnginesCapabilitiesRetrievePathParams;

export interface RuntimeApi {
  engines: {
    capabilities: {
      retrieve(pathParams: RuntimeEnginesCapabilitiesRetrievePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderEngineCapabilityMatrixEnvelope>;
    };
    list(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderEngineDescriptorListEnvelope>;
  };
  modelConfig: {
    retrieve(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderCodeEngineModelConfigEnvelope>;
    update(body: Types.BirdCoderSyncCodeEngineModelConfigRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderCodeEngineModelConfigSyncResultEnvelope>;
  };
  models: {
    list(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderModelCatalogEntryListEnvelope>;
  };
  nativeSessionProviders: {
    list(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderNativeSessionProviderSummaryListEnvelope>;
  };
}

export function createRuntimeApi(requestOperation: BirdcoderSdkRequestOperation): RuntimeApi {
  return {
    engines: {
      capabilities: {
        retrieve(pathParams: RuntimeEnginesCapabilitiesRetrievePathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderEngineCapabilityMatrixEnvelope>("runtime.engines.capabilities.retrieve", { pathParams }, options);
        }
      },
      list(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderEngineDescriptorListEnvelope>("runtime.engines.list", {}, options);
      }
    },
    modelConfig: {
      retrieve(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderCodeEngineModelConfigEnvelope>("runtime.modelConfig.retrieve", {}, options);
      },
      update(body: Types.BirdCoderSyncCodeEngineModelConfigRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderCodeEngineModelConfigSyncResultEnvelope>("runtime.modelConfig.update", { body }, options);
      }
    },
    models: {
      list(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderModelCatalogEntryListEnvelope>("runtime.models.list", {}, options);
      }
    },
    nativeSessionProviders: {
      list(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderNativeSessionProviderSummaryListEnvelope>("runtime.nativeSessionProviders.list", {}, options);
      }
    }
  };
}
