// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http/index.ts';
import type * as Types from '../types/index.ts';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type SkillsSkillPackagesInstallationsCreatePathParams = Types.SkillsSkillPackagesInstallationsCreatePathParams;
type SkillsSkillPackagesListQuery = Types.SkillsSkillPackagesListQuery;

export interface SkillsApi {
  skillPackages: {
    installations: {
      create(pathParams: SkillsSkillPackagesInstallationsCreatePathParams, body: Types.BirdCoderInstallSkillPackageRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderSkillInstallationSummaryEnvelope>;
    };
    list(query?: SkillsSkillPackagesListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderSkillPackageSummaryListEnvelope>;
  };
}

export function createSkillsApi(requestOperation: BirdcoderSdkRequestOperation): SkillsApi {
  return {
    skillPackages: {
      installations: {
        create(pathParams: SkillsSkillPackagesInstallationsCreatePathParams, body: Types.BirdCoderInstallSkillPackageRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderSkillInstallationSummaryEnvelope>("skills.skillPackages.installations.create", { pathParams, body }, options);
        }
      },
      list(query: SkillsSkillPackagesListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderSkillPackageSummaryListEnvelope>("skills.skillPackages.list", { query }, options);
      }
    }
  };
}
