// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http/index.ts';
import type * as Types from '../types/index.ts';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type TemplatesAppTemplatesListQuery = Types.TemplatesAppTemplatesListQuery;

export interface TemplatesApi {
  appTemplates: {
    list(query?: TemplatesAppTemplatesListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderAppTemplateSummaryListEnvelope>;
  };
}

export function createTemplatesApi(requestOperation: BirdcoderSdkRequestOperation): TemplatesApi {
  return {
    appTemplates: {
      list(query: TemplatesAppTemplatesListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderAppTemplateSummaryListEnvelope>("templates.appTemplates.list", { query }, options);
      }
    }
  };
}
