pub struct SessionRow {
    pub id: String,
    pub uuid: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub version: i64,
    pub is_deleted: i64,
    pub workspace_id: String,
    pub project_id: String,
    pub title: String,
    pub status: String,
    pub entry_surface: String,
    pub host_mode: String,
    pub engine_id: String,
    pub model_id: String,
    pub last_turn_at: Option<String>,
    pub native_session_id: Option<String>,
    pub sort_timestamp: Option<i64>,
    pub transcript_updated_at: Option<String>,
    pub pinned: i64,
    pub archived: i64,
    pub unread: i64,
}

pub struct MessageRow {
    pub id: String,
    pub uuid: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub version: i64,
    pub is_deleted: i64,
    pub coding_session_id: String,
    pub turn_id: Option<String>,
    pub role: String,
    pub content: String,
    pub metadata_json: String,
    pub timestamp_ms: Option<i64>,
    pub name: Option<String>,
    pub tool_calls_json: Option<String>,
    pub tool_call_id: Option<String>,
    pub file_changes_json: Option<String>,
    pub commands_json: Option<String>,
    pub task_progress_json: Option<String>,
}

pub struct RuntimeRow {
    pub id: String,
    pub created_at: String,
    pub updated_at: String,
    pub version: i64,
    pub is_deleted: i64,
    pub coding_session_id: String,
    pub engine_id: String,
    pub model_id: String,
    pub host_mode: String,
    pub status: String,
    pub transport_kind: String,
    pub native_session_id: Option<String>,
    pub native_turn_container_id: Option<String>,
    pub capability_snapshot_json: String,
    pub metadata_json: String,
}

pub struct TurnRow {
    pub id: String,
    pub created_at: String,
    pub updated_at: String,
    pub version: i64,
    pub is_deleted: i64,
    pub coding_session_id: String,
    pub runtime_id: String,
    pub request_kind: String,
    pub status: String,
    pub input_summary: String,
    pub started_at: Option<String>,
    pub completed_at: Option<String>,
}

pub struct EventRow {
    pub id: String,
    pub created_at: String,
    pub updated_at: String,
    pub version: i64,
    pub is_deleted: i64,
    pub coding_session_id: String,
    pub turn_id: Option<String>,
    pub runtime_id: Option<String>,
    pub event_kind: String,
    pub sequence_no: i64,
    pub payload_json: String,
}

pub struct ArtifactRow {
    pub id: String,
    pub created_at: String,
    pub updated_at: String,
    pub version: i64,
    pub is_deleted: i64,
    pub coding_session_id: String,
    pub turn_id: Option<String>,
    pub artifact_kind: String,
    pub title: String,
    pub blob_ref: Option<String>,
    pub metadata_json: String,
}

pub struct CheckpointRow {
    pub id: String,
    pub created_at: String,
    pub updated_at: String,
    pub version: i64,
    pub is_deleted: i64,
    pub coding_session_id: String,
    pub runtime_id: Option<String>,
    pub checkpoint_kind: String,
    pub resumable: i64,
    pub state_json: String,
}

pub struct OperationRow {
    pub id: String,
    pub created_at: String,
    pub updated_at: String,
    pub version: i64,
    pub is_deleted: i64,
    pub coding_session_id: String,
    pub turn_id: String,
    pub status: String,
    pub stream_url: String,
    pub stream_kind: String,
    pub artifact_refs_json: String,
}

pub struct PromptEntryRow {
    pub id: String,
    pub created_at: String,
    pub updated_at: String,
    pub version: i64,
    pub is_deleted: i64,
    pub coding_session_id: String,
    pub prompt_text: String,
    pub normalized_prompt_text: String,
    pub last_used_at: String,
    pub use_count: i64,
}
