// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-backend-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http';
import type * as Types from '../types';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type IamTeamsListQuery = Types.IamTeamsListQuery;
type IamTeamsMembersListPathParams = Types.IamTeamsMembersListPathParams;

export interface IamApi {
  auditEvents: {
    list(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderAdminAuditEventSummaryListEnvelope>;
  };
  policies: {
    list(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderAdminPolicySummaryListEnvelope>;
  };
  teams: {
    list(query?: IamTeamsListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderTeamSummaryListEnvelope>;
    members: {
      list(pathParams: IamTeamsMembersListPathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderTeamMemberSummaryListEnvelope>;
    };
  };
}

export function createIamApi(requestOperation: BirdcoderSdkRequestOperation): IamApi {
  return {
    auditEvents: {
      list(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderAdminAuditEventSummaryListEnvelope>("iam.auditEvents.list", {}, options);
      }
    },
    policies: {
      list(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderAdminPolicySummaryListEnvelope>("iam.policies.list", {}, options);
      }
    },
    teams: {
      list(query: IamTeamsListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderTeamSummaryListEnvelope>("iam.teams.list", { query }, options);
      },
      members: {
        list(pathParams: IamTeamsMembersListPathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderTeamMemberSummaryListEnvelope>("iam.teams.members.list", { pathParams }, options);
        }
      }
    }
  };
}
