// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-backend-v3.openapi.json. Do not edit by hand.

export { createBirdcoderBackendSdkClient } from './sdk.ts';
export type {
  BirdcoderBackendSdkClient,
  CreateBirdcoderBackendSdkClientOptions,
} from './sdk.ts';
export * from './sdk.ts';
export * from './api/index.ts';
export * from './types/index.ts';
export * from './http/index.ts';
