// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-backend-v3.openapi.json. Do not edit by hand.

import {
  createBirdcoderSdkOperationRequester,
  type BirdcoderSdkAuthTokens,
  type BirdcoderSdkTransport,
} from './http';
import { BIRDCODER_BACKEND_SDK_OPERATION_INDEX } from './types';
import { createIamApi, type IamApi } from './api/iam';
import { createPlatformApi, type PlatformApi } from './api/platform';

export interface CreateBirdcoderBackendSdkClientOptions {
  accessToken?: string;
  authToken?: string;
  transport: BirdcoderSdkTransport;
}

export interface BirdcoderBackendSdkClient {
  clearSdkworkAuthTokens(): void;
  setSdkworkAuthTokens(tokens: BirdcoderSdkAuthTokens): void;
  iam: IamApi;
  platform: PlatformApi;
}

export function createBirdcoderBackendSdkClient(
  options: CreateBirdcoderBackendSdkClientOptions,
): BirdcoderBackendSdkClient {
  const requester = createBirdcoderSdkOperationRequester({
    accessToken: options.accessToken,
    authToken: options.authToken,
    operationIndex: BIRDCODER_BACKEND_SDK_OPERATION_INDEX,
    surface: "backend",
    transport: options.transport,
  });

  return {
    clearSdkworkAuthTokens: requester.clearSdkworkAuthTokens,
    setSdkworkAuthTokens: requester.setSdkworkAuthTokens,
    iam: createIamApi(requester.requestOperation),
    platform: createPlatformApi(requester.requestOperation),
  };
}
