// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http';
import type * as Types from '../types';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type AuthOauthAuthorizationUrlsRetrieveQuery = Types.AuthOauthAuthorizationUrlsRetrieveQuery;
type AuthQrLoginCodesRetrievePathParams = Types.AuthQrLoginCodesRetrievePathParams;

export interface AuthApi {
  config: {
    retrieve(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderUserCenterMetadataEnvelope>;
  };
  oauthAuthorizationUrls: {
    retrieve(query: AuthOauthAuthorizationUrlsRetrieveQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderUserCenterOAuthAuthorizationEnvelope>;
  };
  oauthSessions: {
    create(body: Types.BirdCoderUserCenterOAuthLoginRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderUserCenterSessionEnvelope>;
  };
  passwordResetRequests: {
    create(body: Types.BirdCoderUserCenterPasswordResetChallengeRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderBooleanSuccessEnvelope>;
  };
  passwordResets: {
    create(body: Types.BirdCoderUserCenterPasswordResetRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderBooleanSuccessEnvelope>;
  };
  qrLoginCodes: {
    create(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderUserCenterLoginQrCodeEnvelope>;
    retrieve(pathParams: AuthQrLoginCodesRetrievePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderUserCenterLoginQrStatusEnvelope>;
  };
  registrations: {
    create(body: Types.BirdCoderUserCenterRegisterRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderUserCenterSessionEnvelope>;
  };
  sessionExchanges: {
    create(body: Types.BirdCoderUserCenterSessionExchangeRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderUserCenterSessionEnvelope>;
  };
  sessions: {
    create(body: Types.BirdCoderUserCenterLoginRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderUserCenterSessionEnvelope>;
    current: {
      delete(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderBooleanSuccessEnvelope>;
      retrieve(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderNullableUserCenterSessionEnvelope>;
    };
  };
  verificationCodes: {
    create(body: Types.BirdCoderUserCenterSendVerifyCodeRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderBooleanSuccessEnvelope>;
  };
}

export function createAuthApi(requestOperation: BirdcoderSdkRequestOperation): AuthApi {
  return {
    config: {
      retrieve(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderUserCenterMetadataEnvelope>("auth.config.retrieve", {}, options);
      }
    },
    oauthAuthorizationUrls: {
      retrieve(query: AuthOauthAuthorizationUrlsRetrieveQuery, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderUserCenterOAuthAuthorizationEnvelope>("auth.oauthAuthorizationUrls.retrieve", { query }, options);
      }
    },
    oauthSessions: {
      create(body: Types.BirdCoderUserCenterOAuthLoginRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderUserCenterSessionEnvelope>("auth.oauthSessions.create", { body }, options);
      }
    },
    passwordResetRequests: {
      create(body: Types.BirdCoderUserCenterPasswordResetChallengeRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderBooleanSuccessEnvelope>("auth.passwordResetRequests.create", { body }, options);
      }
    },
    passwordResets: {
      create(body: Types.BirdCoderUserCenterPasswordResetRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderBooleanSuccessEnvelope>("auth.passwordResets.create", { body }, options);
      }
    },
    qrLoginCodes: {
      create(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderUserCenterLoginQrCodeEnvelope>("auth.qrLoginCodes.create", {}, options);
      },
      retrieve(pathParams: AuthQrLoginCodesRetrievePathParams, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderUserCenterLoginQrStatusEnvelope>("auth.qrLoginCodes.retrieve", { pathParams }, options);
      }
    },
    registrations: {
      create(body: Types.BirdCoderUserCenterRegisterRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderUserCenterSessionEnvelope>("auth.registrations.create", { body }, options);
      }
    },
    sessionExchanges: {
      create(body: Types.BirdCoderUserCenterSessionExchangeRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderUserCenterSessionEnvelope>("auth.sessionExchanges.create", { body }, options);
      }
    },
    sessions: {
      create(body: Types.BirdCoderUserCenterLoginRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderUserCenterSessionEnvelope>("auth.sessions.create", { body }, options);
      },
      current: {
        delete(options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderBooleanSuccessEnvelope>("auth.sessions.current.delete", {}, options);
        },
        retrieve(options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderNullableUserCenterSessionEnvelope>("auth.sessions.current.retrieve", {}, options);
        }
      }
    },
    verificationCodes: {
      create(body: Types.BirdCoderUserCenterSendVerifyCodeRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderBooleanSuccessEnvelope>("auth.verificationCodes.create", { body }, options);
      }
    }
  };
}
