// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http';
import type * as Types from '../types';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type CollaborationWorkspaceTeamsListQuery = Types.CollaborationWorkspaceTeamsListQuery;

export interface CollaborationApi {
  workspaceTeams: {
    list(query?: CollaborationWorkspaceTeamsListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderTeamSummaryListEnvelope>;
  };
}

export function createCollaborationApi(requestOperation: BirdcoderSdkRequestOperation): CollaborationApi {
  return {
    workspaceTeams: {
      list(query: CollaborationWorkspaceTeamsListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderTeamSummaryListEnvelope>("collaboration.workspaceTeams.list", { query }, options);
      }
    }
  };
}
