// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http/index.ts';
import type * as Types from '../types/index.ts';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;


export interface ContentApi {
  documents: {
    list(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectDocumentSummaryListEnvelope>;
  };
}

export function createContentApi(requestOperation: BirdcoderSdkRequestOperation): ContentApi {
  return {
    documents: {
      list(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderProjectDocumentSummaryListEnvelope>("content.documents.list", {}, options);
      }
    }
  };
}
