// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http';
import type * as Types from '../types';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type IamTeamsListQuery = Types.IamTeamsListQuery;
type IamWorkspacesMembersListPathParams = Types.IamWorkspacesMembersListPathParams;
type IamWorkspacesMembersUpsertPathParams = Types.IamWorkspacesMembersUpsertPathParams;

export interface IamApi {
  teams: {
    list(query?: IamTeamsListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderTeamSummaryListEnvelope>;
  };
  users: {
    current: {
      retrieve(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderUserCenterProfileEnvelope>;
      update(body: Types.BirdCoderUpdateCurrentUserProfileRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderUserCenterProfileEnvelope>;
    };
  };
  workspaces: {
    members: {
      list(pathParams: IamWorkspacesMembersListPathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderWorkspaceMemberSummaryListEnvelope>;
      upsert(pathParams: IamWorkspacesMembersUpsertPathParams, body: Types.BirdCoderUpsertWorkspaceMemberRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderWorkspaceMemberSummaryEnvelope>;
    };
  };
}

export function createIamApi(requestOperation: BirdcoderSdkRequestOperation): IamApi {
  return {
    teams: {
      list(query: IamTeamsListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderTeamSummaryListEnvelope>("iam.teams.list", { query }, options);
      }
    },
    users: {
      current: {
        retrieve(options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderUserCenterProfileEnvelope>("iam.users.current.retrieve", {}, options);
        },
        update(body: Types.BirdCoderUpdateCurrentUserProfileRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderUserCenterProfileEnvelope>("iam.users.current.update", { body }, options);
        }
      }
    },
    workspaces: {
      members: {
        list(pathParams: IamWorkspacesMembersListPathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderWorkspaceMemberSummaryListEnvelope>("iam.workspaces.members.list", { pathParams }, options);
        },
        upsert(pathParams: IamWorkspacesMembersUpsertPathParams, body: Types.BirdCoderUpsertWorkspaceMemberRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderWorkspaceMemberSummaryEnvelope>("iam.workspaces.members.upsert", { pathParams, body }, options);
        }
      }
    }
  };
}
