// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http/index.ts';
import type * as Types from '../types/index.ts';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type IamWorkspacesMembersListPathParams = Types.IamWorkspacesMembersListPathParams;
type IamWorkspacesMembersUpsertPathParams = Types.IamWorkspacesMembersUpsertPathParams;

export interface IamApi {
  users: {
    current: {
      retrieve(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamUserProfileEnvelope>;
      update(body: Types.BirdCoderUpdateCurrentUserProfileRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamUserProfileEnvelope>;
    };
  };
  workspaces: {
    members: {
      list(pathParams: IamWorkspacesMembersListPathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderWorkspaceMemberSummaryListEnvelope>;
      upsert(pathParams: IamWorkspacesMembersUpsertPathParams, body: Types.BirdCoderUpsertWorkspaceMemberRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderWorkspaceMemberSummaryEnvelope>;
    };
  };
}

export function createIamApi(requestOperation: BirdcoderSdkRequestOperation): IamApi {
  return {
    users: {
      current: {
        retrieve(options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamUserProfileEnvelope>("iam.users.current.retrieve", {}, options);
        },
        update(body: Types.BirdCoderUpdateCurrentUserProfileRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamUserProfileEnvelope>("iam.users.current.update", { body }, options);
        }
      }
    },
    workspaces: {
      members: {
        list(pathParams: IamWorkspacesMembersListPathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderWorkspaceMemberSummaryListEnvelope>("iam.workspaces.members.list", { pathParams }, options);
        },
        upsert(pathParams: IamWorkspacesMembersUpsertPathParams, body: Types.BirdCoderUpsertWorkspaceMemberRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderWorkspaceMemberSummaryEnvelope>("iam.workspaces.members.upsert", { pathParams, body }, options);
        }
      }
    }
  };
}
