// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http/index.ts';
import type * as Types from '../types/index.ts';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type OpenPlatformQrAuthSessionsPasswordsCreatePathParams = Types.OpenPlatformQrAuthSessionsPasswordsCreatePathParams;
type OpenPlatformQrAuthSessionsRetrievePathParams = Types.OpenPlatformQrAuthSessionsRetrievePathParams;
type OpenPlatformQrAuthSessionsScansCreatePathParams = Types.OpenPlatformQrAuthSessionsScansCreatePathParams;

export interface OpenPlatformApi {
  qrAuth: {
    sessions: {
      create(body: Types.BirdCoderIamQrAuthSessionCreateRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamQrAuthSessionEnvelope>;
      passwords: {
        create(pathParams: OpenPlatformQrAuthSessionsPasswordsCreatePathParams, body: Types.BirdCoderIamQrAuthSessionPasswordRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamSessionEnvelope>;
      };
      retrieve(pathParams: OpenPlatformQrAuthSessionsRetrievePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamQrAuthSessionEnvelope>;
      scans: {
        create(pathParams: OpenPlatformQrAuthSessionsScansCreatePathParams, body: Types.BirdCoderIamQrAuthSessionScanRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderBooleanSuccessEnvelope>;
      };
    };
  };
}

export function createOpenPlatformApi(requestOperation: BirdcoderSdkRequestOperation): OpenPlatformApi {
  return {
    qrAuth: {
      sessions: {
        create(body: Types.BirdCoderIamQrAuthSessionCreateRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamQrAuthSessionEnvelope>("openPlatform.qrAuth.sessions.create", { body }, options);
        },
        passwords: {
          create(pathParams: OpenPlatformQrAuthSessionsPasswordsCreatePathParams, body: Types.BirdCoderIamQrAuthSessionPasswordRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderIamSessionEnvelope>("openPlatform.qrAuth.sessions.passwords.create", { pathParams, body }, options);
          }
        },
        retrieve(pathParams: OpenPlatformQrAuthSessionsRetrievePathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamQrAuthSessionEnvelope>("openPlatform.qrAuth.sessions.retrieve", { pathParams }, options);
        },
        scans: {
          create(pathParams: OpenPlatformQrAuthSessionsScansCreatePathParams, body: Types.BirdCoderIamQrAuthSessionScanRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderBooleanSuccessEnvelope>("openPlatform.qrAuth.sessions.scans.create", { pathParams, body }, options);
          }
        }
      }
    }
  };
}
