// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http/index.ts';
import type * as Types from '../types/index.ts';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type PlatformDeploymentsListQuery = Types.PlatformDeploymentsListQuery;
type PlatformProjectsCollaboratorsCreatePathParams = Types.PlatformProjectsCollaboratorsCreatePathParams;
type PlatformProjectsCollaboratorsListPathParams = Types.PlatformProjectsCollaboratorsListPathParams;
type PlatformProjectsCollaboratorsListQuery = Types.PlatformProjectsCollaboratorsListQuery;
type PlatformProjectsDeletePathParams = Types.PlatformProjectsDeletePathParams;
type PlatformProjectsDeploymentTargetsListPathParams = Types.PlatformProjectsDeploymentTargetsListPathParams;
type PlatformProjectsDeploymentTargetsListQuery = Types.PlatformProjectsDeploymentTargetsListQuery;
type PlatformProjectsGitBranchesCreatePathParams = Types.PlatformProjectsGitBranchesCreatePathParams;
type PlatformProjectsGitBranchSwitchCreatePathParams = Types.PlatformProjectsGitBranchSwitchCreatePathParams;
type PlatformProjectsGitCommitsCreatePathParams = Types.PlatformProjectsGitCommitsCreatePathParams;
type PlatformProjectsGitDiffRetrievePathParams = Types.PlatformProjectsGitDiffRetrievePathParams;
type PlatformProjectsGitDiffRetrieveQuery = Types.PlatformProjectsGitDiffRetrieveQuery;
type PlatformProjectsGitOverviewRetrievePathParams = Types.PlatformProjectsGitOverviewRetrievePathParams;
type PlatformProjectsGitOverviewRetrieveQuery = Types.PlatformProjectsGitOverviewRetrieveQuery;
type PlatformProjectsGitPushesCreatePathParams = Types.PlatformProjectsGitPushesCreatePathParams;
type PlatformProjectsGitWorktreePruneCreatePathParams = Types.PlatformProjectsGitWorktreePruneCreatePathParams;
type PlatformProjectsGitWorktreeRemovalsCreatePathParams = Types.PlatformProjectsGitWorktreeRemovalsCreatePathParams;
type PlatformProjectsGitWorktreesCreatePathParams = Types.PlatformProjectsGitWorktreesCreatePathParams;
type PlatformProjectsListQuery = Types.PlatformProjectsListQuery;
type PlatformProjectsPublishPublishPathParams = Types.PlatformProjectsPublishPublishPathParams;
type PlatformProjectsRetrievePathParams = Types.PlatformProjectsRetrievePathParams;
type PlatformProjectsRuntimeLocationsCreatePathParams = Types.PlatformProjectsRuntimeLocationsCreatePathParams;
type PlatformProjectsRuntimeLocationsDeletePathParams = Types.PlatformProjectsRuntimeLocationsDeletePathParams;
type PlatformProjectsRuntimeLocationsListPathParams = Types.PlatformProjectsRuntimeLocationsListPathParams;
type PlatformProjectsRuntimeLocationsListQuery = Types.PlatformProjectsRuntimeLocationsListQuery;
type PlatformProjectsRuntimeLocationsPreferencesListPathParams = Types.PlatformProjectsRuntimeLocationsPreferencesListPathParams;
type PlatformProjectsRuntimeLocationsPreferencesListQuery = Types.PlatformProjectsRuntimeLocationsPreferencesListQuery;
type PlatformProjectsRuntimeLocationsPreferencesUpdatePathParams = Types.PlatformProjectsRuntimeLocationsPreferencesUpdatePathParams;
type PlatformProjectsRuntimeLocationsRebindPathParams = Types.PlatformProjectsRuntimeLocationsRebindPathParams;
type PlatformProjectsRuntimeLocationsRequestVerificationPathParams = Types.PlatformProjectsRuntimeLocationsRequestVerificationPathParams;
type PlatformProjectsRuntimeLocationsRetrievePathParams = Types.PlatformProjectsRuntimeLocationsRetrievePathParams;
type PlatformProjectsRuntimeLocationsUpdatePathParams = Types.PlatformProjectsRuntimeLocationsUpdatePathParams;
type PlatformProjectsUpdatePathParams = Types.PlatformProjectsUpdatePathParams;
type PlatformProjectsWorkspaceBindingDeletePathParams = Types.PlatformProjectsWorkspaceBindingDeletePathParams;
type PlatformProjectsWorkspaceBindingRetrievePathParams = Types.PlatformProjectsWorkspaceBindingRetrievePathParams;
type PlatformProjectsWorkspaceBindingUpdatePathParams = Types.PlatformProjectsWorkspaceBindingUpdatePathParams;
type PlatformWorkspacesDeletePathParams = Types.PlatformWorkspacesDeletePathParams;
type PlatformWorkspacesListQuery = Types.PlatformWorkspacesListQuery;
type PlatformWorkspacesRetrievePathParams = Types.PlatformWorkspacesRetrievePathParams;
type PlatformWorkspacesUpdatePathParams = Types.PlatformWorkspacesUpdatePathParams;

export interface PlatformApi {
  deployments: {
    list(query?: PlatformDeploymentsListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderDeploymentRecordSummaryListEnvelope>;
  };
  projects: {
    collaborators: {
      create(pathParams: PlatformProjectsCollaboratorsCreatePathParams, body: Types.BirdCoderUpsertProjectCollaboratorRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectCollaboratorSummaryEnvelope>;
      list(pathParams: PlatformProjectsCollaboratorsListPathParams, query?: PlatformProjectsCollaboratorsListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectCollaboratorSummaryListEnvelope>;
    };
    create(body: Types.BirdCoderCreateProjectRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectSummaryEnvelope>;
    delete(pathParams: PlatformProjectsDeletePathParams, options?: BirdcoderSdkRequestOptions): Promise<void>;
    deploymentTargets: {
      list(pathParams: PlatformProjectsDeploymentTargetsListPathParams, query?: PlatformProjectsDeploymentTargetsListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderDeploymentTargetSummaryListEnvelope>;
    };
    git: {
      branches: {
        create(pathParams: PlatformProjectsGitBranchesCreatePathParams, body: Types.BirdCoderCreateProjectGitBranchRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
      branchSwitch: {
        create(pathParams: PlatformProjectsGitBranchSwitchCreatePathParams, body: Types.BirdCoderSwitchProjectGitBranchRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
      commits: {
        create(pathParams: PlatformProjectsGitCommitsCreatePathParams, body: Types.BirdCoderCommitProjectGitChangesRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
      diff: {
        retrieve(pathParams: PlatformProjectsGitDiffRetrievePathParams, query: PlatformProjectsGitDiffRetrieveQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitDiffEnvelope>;
      };
      overview: {
        retrieve(pathParams: PlatformProjectsGitOverviewRetrievePathParams, query: PlatformProjectsGitOverviewRetrieveQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
      pushes: {
        create(pathParams: PlatformProjectsGitPushesCreatePathParams, body: Types.BirdCoderPushProjectGitBranchRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
      worktreePrune: {
        create(pathParams: PlatformProjectsGitWorktreePruneCreatePathParams, body: Types.BirdCoderPruneProjectGitWorktreesRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
      worktreeRemovals: {
        create(pathParams: PlatformProjectsGitWorktreeRemovalsCreatePathParams, body: Types.BirdCoderRemoveProjectGitWorktreeRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
      worktrees: {
        create(pathParams: PlatformProjectsGitWorktreesCreatePathParams, body: Types.BirdCoderCreateProjectGitWorktreeRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
    };
    list(query?: PlatformProjectsListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectSummaryListEnvelope>;
    publish: {
      publish(pathParams: PlatformProjectsPublishPublishPathParams, body: Types.BirdCoderPublishProjectRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectPublishResultEnvelope>;
    };
    retrieve(pathParams: PlatformProjectsRetrievePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectSummaryEnvelope>;
    runtimeLocations: {
      create(pathParams: PlatformProjectsRuntimeLocationsCreatePathParams, body: Types.BirdCoderCreateProjectRuntimeLocationRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectRuntimeLocationEnvelope>;
      delete(pathParams: PlatformProjectsRuntimeLocationsDeletePathParams, options?: BirdcoderSdkRequestOptions): Promise<void>;
      list(pathParams: PlatformProjectsRuntimeLocationsListPathParams, query?: PlatformProjectsRuntimeLocationsListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectRuntimeLocationListEnvelope>;
      preferences: {
        list(pathParams: PlatformProjectsRuntimeLocationsPreferencesListPathParams, query?: PlatformProjectsRuntimeLocationsPreferencesListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectRuntimeLocationPreferenceListEnvelope>;
        update(pathParams: PlatformProjectsRuntimeLocationsPreferencesUpdatePathParams, body: Types.BirdCoderSetProjectRuntimeLocationPreferenceRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectRuntimeLocationPreferenceEnvelope>;
      };
      rebind(pathParams: PlatformProjectsRuntimeLocationsRebindPathParams, body: Types.BirdCoderRebindProjectRuntimeLocationRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectRuntimeLocationCommandEnvelope>;
      requestVerification(pathParams: PlatformProjectsRuntimeLocationsRequestVerificationPathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectRuntimeLocationCommandEnvelope>;
      retrieve(pathParams: PlatformProjectsRuntimeLocationsRetrievePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectRuntimeLocationEnvelope>;
      update(pathParams: PlatformProjectsRuntimeLocationsUpdatePathParams, body: Types.BirdCoderUpdateProjectRuntimeLocationRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectRuntimeLocationEnvelope>;
    };
    update(pathParams: PlatformProjectsUpdatePathParams, body: Types.BirdCoderUpdateProjectRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectSummaryEnvelope>;
    workspaceBinding: {
      delete(pathParams: PlatformProjectsWorkspaceBindingDeletePathParams, options?: BirdcoderSdkRequestOptions): Promise<void>;
      retrieve(pathParams: PlatformProjectsWorkspaceBindingRetrievePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectWorkspaceBindingEnvelope>;
      update(pathParams: PlatformProjectsWorkspaceBindingUpdatePathParams, body: Types.BirdCoderUpsertProjectWorkspaceBindingRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectWorkspaceBindingEnvelope>;
    };
  };
  workspaces: {
    create(body: Types.BirdCoderCreateWorkspaceRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderWorkspaceSummaryEnvelope>;
    delete(pathParams: PlatformWorkspacesDeletePathParams, options?: BirdcoderSdkRequestOptions): Promise<void>;
    list(query?: PlatformWorkspacesListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderWorkspaceSummaryListEnvelope>;
    retrieve(pathParams: PlatformWorkspacesRetrievePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderWorkspaceSummaryEnvelope>;
    update(pathParams: PlatformWorkspacesUpdatePathParams, body: Types.BirdCoderUpdateWorkspaceRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderWorkspaceSummaryEnvelope>;
  };
}

export function createPlatformApi(requestOperation: BirdcoderSdkRequestOperation): PlatformApi {
  return {
    deployments: {
      list(query: PlatformDeploymentsListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderDeploymentRecordSummaryListEnvelope>("platform.deployments.list", { query }, options);
      }
    },
    projects: {
      collaborators: {
        create(pathParams: PlatformProjectsCollaboratorsCreatePathParams, body: Types.BirdCoderUpsertProjectCollaboratorRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderProjectCollaboratorSummaryEnvelope>("platform.projects.collaborators.create", { pathParams, body }, options);
        },
        list(pathParams: PlatformProjectsCollaboratorsListPathParams, query: PlatformProjectsCollaboratorsListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderProjectCollaboratorSummaryListEnvelope>("platform.projects.collaborators.list", { pathParams, query }, options);
        }
      },
      create(body: Types.BirdCoderCreateProjectRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderProjectSummaryEnvelope>("platform.projects.create", { body }, options);
      },
      delete(pathParams: PlatformProjectsDeletePathParams, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<void>("platform.projects.delete", { pathParams }, options);
      },
      deploymentTargets: {
        list(pathParams: PlatformProjectsDeploymentTargetsListPathParams, query: PlatformProjectsDeploymentTargetsListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderDeploymentTargetSummaryListEnvelope>("platform.projects.deploymentTargets.list", { pathParams, query }, options);
        }
      },
      git: {
        branches: {
          create(pathParams: PlatformProjectsGitBranchesCreatePathParams, body: Types.BirdCoderCreateProjectGitBranchRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.branches.create", { pathParams, body }, options);
          }
        },
        branchSwitch: {
          create(pathParams: PlatformProjectsGitBranchSwitchCreatePathParams, body: Types.BirdCoderSwitchProjectGitBranchRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.branchSwitch.create", { pathParams, body }, options);
          }
        },
        commits: {
          create(pathParams: PlatformProjectsGitCommitsCreatePathParams, body: Types.BirdCoderCommitProjectGitChangesRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.commits.create", { pathParams, body }, options);
          }
        },
        diff: {
          retrieve(pathParams: PlatformProjectsGitDiffRetrievePathParams, query: PlatformProjectsGitDiffRetrieveQuery, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitDiffEnvelope>("platform.projects.git.diff.retrieve", { pathParams, query }, options);
          }
        },
        overview: {
          retrieve(pathParams: PlatformProjectsGitOverviewRetrievePathParams, query: PlatformProjectsGitOverviewRetrieveQuery, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.overview.retrieve", { pathParams, query }, options);
          }
        },
        pushes: {
          create(pathParams: PlatformProjectsGitPushesCreatePathParams, body: Types.BirdCoderPushProjectGitBranchRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.pushes.create", { pathParams, body }, options);
          }
        },
        worktreePrune: {
          create(pathParams: PlatformProjectsGitWorktreePruneCreatePathParams, body: Types.BirdCoderPruneProjectGitWorktreesRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.worktreePrune.create", { pathParams, body }, options);
          }
        },
        worktreeRemovals: {
          create(pathParams: PlatformProjectsGitWorktreeRemovalsCreatePathParams, body: Types.BirdCoderRemoveProjectGitWorktreeRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.worktreeRemovals.create", { pathParams, body }, options);
          }
        },
        worktrees: {
          create(pathParams: PlatformProjectsGitWorktreesCreatePathParams, body: Types.BirdCoderCreateProjectGitWorktreeRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.worktrees.create", { pathParams, body }, options);
          }
        }
      },
      list(query: PlatformProjectsListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderProjectSummaryListEnvelope>("platform.projects.list", { query }, options);
      },
      publish: {
        publish(pathParams: PlatformProjectsPublishPublishPathParams, body: Types.BirdCoderPublishProjectRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderProjectPublishResultEnvelope>("platform.projects.publish.publish", { pathParams, body }, options);
        }
      },
      retrieve(pathParams: PlatformProjectsRetrievePathParams, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderProjectSummaryEnvelope>("platform.projects.retrieve", { pathParams }, options);
      },
      runtimeLocations: {
        create(pathParams: PlatformProjectsRuntimeLocationsCreatePathParams, body: Types.BirdCoderCreateProjectRuntimeLocationRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderProjectRuntimeLocationEnvelope>("platform.projects.runtimeLocations.create", { pathParams, body }, options);
        },
        delete(pathParams: PlatformProjectsRuntimeLocationsDeletePathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<void>("platform.projects.runtimeLocations.delete", { pathParams }, options);
        },
        list(pathParams: PlatformProjectsRuntimeLocationsListPathParams, query: PlatformProjectsRuntimeLocationsListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderProjectRuntimeLocationListEnvelope>("platform.projects.runtimeLocations.list", { pathParams, query }, options);
        },
        preferences: {
          list(pathParams: PlatformProjectsRuntimeLocationsPreferencesListPathParams, query: PlatformProjectsRuntimeLocationsPreferencesListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectRuntimeLocationPreferenceListEnvelope>("platform.projects.runtimeLocations.preferences.list", { pathParams, query }, options);
          },
          update(pathParams: PlatformProjectsRuntimeLocationsPreferencesUpdatePathParams, body: Types.BirdCoderSetProjectRuntimeLocationPreferenceRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectRuntimeLocationPreferenceEnvelope>("platform.projects.runtimeLocations.preferences.update", { pathParams, body }, options);
          }
        },
        rebind(pathParams: PlatformProjectsRuntimeLocationsRebindPathParams, body: Types.BirdCoderRebindProjectRuntimeLocationRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderProjectRuntimeLocationCommandEnvelope>("platform.projects.runtimeLocations.rebind", { pathParams, body }, options);
        },
        requestVerification(pathParams: PlatformProjectsRuntimeLocationsRequestVerificationPathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderProjectRuntimeLocationCommandEnvelope>("platform.projects.runtimeLocations.requestVerification", { pathParams }, options);
        },
        retrieve(pathParams: PlatformProjectsRuntimeLocationsRetrievePathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderProjectRuntimeLocationEnvelope>("platform.projects.runtimeLocations.retrieve", { pathParams }, options);
        },
        update(pathParams: PlatformProjectsRuntimeLocationsUpdatePathParams, body: Types.BirdCoderUpdateProjectRuntimeLocationRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderProjectRuntimeLocationEnvelope>("platform.projects.runtimeLocations.update", { pathParams, body }, options);
        }
      },
      update(pathParams: PlatformProjectsUpdatePathParams, body: Types.BirdCoderUpdateProjectRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderProjectSummaryEnvelope>("platform.projects.update", { pathParams, body }, options);
      },
      workspaceBinding: {
        delete(pathParams: PlatformProjectsWorkspaceBindingDeletePathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<void>("platform.projects.workspaceBinding.delete", { pathParams }, options);
        },
        retrieve(pathParams: PlatformProjectsWorkspaceBindingRetrievePathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderProjectWorkspaceBindingEnvelope>("platform.projects.workspaceBinding.retrieve", { pathParams }, options);
        },
        update(pathParams: PlatformProjectsWorkspaceBindingUpdatePathParams, body: Types.BirdCoderUpsertProjectWorkspaceBindingRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderProjectWorkspaceBindingEnvelope>("platform.projects.workspaceBinding.update", { pathParams, body }, options);
        }
      }
    },
    workspaces: {
      create(body: Types.BirdCoderCreateWorkspaceRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderWorkspaceSummaryEnvelope>("platform.workspaces.create", { body }, options);
      },
      delete(pathParams: PlatformWorkspacesDeletePathParams, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<void>("platform.workspaces.delete", { pathParams }, options);
      },
      list(query: PlatformWorkspacesListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderWorkspaceSummaryListEnvelope>("platform.workspaces.list", { query }, options);
      },
      retrieve(pathParams: PlatformWorkspacesRetrievePathParams, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderWorkspaceSummaryEnvelope>("platform.workspaces.retrieve", { pathParams }, options);
      },
      update(pathParams: PlatformWorkspacesUpdatePathParams, body: Types.BirdCoderUpdateWorkspaceRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderWorkspaceSummaryEnvelope>("platform.workspaces.update", { pathParams, body }, options);
      }
    }
  };
}
