// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http/index.ts';
import type * as Types from '../types/index.ts';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type PlatformProjectsCollaboratorsListPathParams = Types.PlatformProjectsCollaboratorsListPathParams;
type PlatformProjectsCollaboratorsUpsertPathParams = Types.PlatformProjectsCollaboratorsUpsertPathParams;
type PlatformProjectsDeletePathParams = Types.PlatformProjectsDeletePathParams;
type PlatformProjectsDeploymentTargetsListPathParams = Types.PlatformProjectsDeploymentTargetsListPathParams;
type PlatformProjectsGitBranchesCreatePathParams = Types.PlatformProjectsGitBranchesCreatePathParams;
type PlatformProjectsGitBranchSwitchCreatePathParams = Types.PlatformProjectsGitBranchSwitchCreatePathParams;
type PlatformProjectsGitCommitsCreatePathParams = Types.PlatformProjectsGitCommitsCreatePathParams;
type PlatformProjectsGitOverviewRetrievePathParams = Types.PlatformProjectsGitOverviewRetrievePathParams;
type PlatformProjectsGitPushesCreatePathParams = Types.PlatformProjectsGitPushesCreatePathParams;
type PlatformProjectsGitWorktreePruneCreatePathParams = Types.PlatformProjectsGitWorktreePruneCreatePathParams;
type PlatformProjectsGitWorktreeRemovalsCreatePathParams = Types.PlatformProjectsGitWorktreeRemovalsCreatePathParams;
type PlatformProjectsGitWorktreesCreatePathParams = Types.PlatformProjectsGitWorktreesCreatePathParams;
type PlatformProjectsListQuery = Types.PlatformProjectsListQuery;
type PlatformProjectsPublishCreatePathParams = Types.PlatformProjectsPublishCreatePathParams;
type PlatformProjectsRetrievePathParams = Types.PlatformProjectsRetrievePathParams;
type PlatformProjectsUpdatePathParams = Types.PlatformProjectsUpdatePathParams;
type PlatformWorkspacesDeletePathParams = Types.PlatformWorkspacesDeletePathParams;
type PlatformWorkspacesListQuery = Types.PlatformWorkspacesListQuery;
type PlatformWorkspacesRealtimeSubscribePathParams = Types.PlatformWorkspacesRealtimeSubscribePathParams;
type PlatformWorkspacesRealtimeSubscribeQuery = Types.PlatformWorkspacesRealtimeSubscribeQuery;
type PlatformWorkspacesRetrievePathParams = Types.PlatformWorkspacesRetrievePathParams;
type PlatformWorkspacesUpdatePathParams = Types.PlatformWorkspacesUpdatePathParams;

export interface PlatformApi {
  deployments: {
    list(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderDeploymentRecordSummaryListEnvelope>;
  };
  projects: {
    collaborators: {
      list(pathParams: PlatformProjectsCollaboratorsListPathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectCollaboratorSummaryListEnvelope>;
      upsert(pathParams: PlatformProjectsCollaboratorsUpsertPathParams, body: Types.BirdCoderUpsertProjectCollaboratorRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectCollaboratorSummaryEnvelope>;
    };
    create(body: Types.BirdCoderCreateProjectRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectSummaryEnvelope>;
    delete(pathParams: PlatformProjectsDeletePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderDeletedResourceEnvelope>;
    deploymentTargets: {
      list(pathParams: PlatformProjectsDeploymentTargetsListPathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderDeploymentTargetSummaryListEnvelope>;
    };
    git: {
      branches: {
        create(pathParams: PlatformProjectsGitBranchesCreatePathParams, body: Types.BirdCoderCreateProjectGitBranchRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
      branchSwitch: {
        create(pathParams: PlatformProjectsGitBranchSwitchCreatePathParams, body: Types.BirdCoderSwitchProjectGitBranchRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
      commits: {
        create(pathParams: PlatformProjectsGitCommitsCreatePathParams, body: Types.BirdCoderCommitProjectGitChangesRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
      overview: {
        retrieve(pathParams: PlatformProjectsGitOverviewRetrievePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
      pushes: {
        create(pathParams: PlatformProjectsGitPushesCreatePathParams, body: Types.BirdCoderPushProjectGitBranchRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
      worktreePrune: {
        create(pathParams: PlatformProjectsGitWorktreePruneCreatePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
      worktreeRemovals: {
        create(pathParams: PlatformProjectsGitWorktreeRemovalsCreatePathParams, body: Types.BirdCoderRemoveProjectGitWorktreeRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
      worktrees: {
        create(pathParams: PlatformProjectsGitWorktreesCreatePathParams, body: Types.BirdCoderCreateProjectGitWorktreeRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectGitOverviewEnvelope>;
      };
    };
    list(query?: PlatformProjectsListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectSummaryListEnvelope>;
    publish: {
      create(pathParams: PlatformProjectsPublishCreatePathParams, body: Types.BirdCoderPublishProjectRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectPublishResultEnvelope>;
    };
    retrieve(pathParams: PlatformProjectsRetrievePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectSummaryEnvelope>;
    update(pathParams: PlatformProjectsUpdatePathParams, body: Types.BirdCoderUpdateProjectRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderProjectSummaryEnvelope>;
  };
  workspaces: {
    create(body: Types.BirdCoderCreateWorkspaceRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderWorkspaceSummaryEnvelope>;
    delete(pathParams: PlatformWorkspacesDeletePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderDeletedResourceEnvelope>;
    list(query?: PlatformWorkspacesListQuery, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderWorkspaceSummaryListEnvelope>;
    realtime: {
      subscribe(pathParams: PlatformWorkspacesRealtimeSubscribePathParams, query?: PlatformWorkspacesRealtimeSubscribeQuery, options?: BirdcoderSdkRequestOptions): Promise<void>;
    };
    retrieve(pathParams: PlatformWorkspacesRetrievePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderWorkspaceSummaryEnvelope>;
    update(pathParams: PlatformWorkspacesUpdatePathParams, body: Types.BirdCoderUpdateWorkspaceRequest, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderWorkspaceSummaryEnvelope>;
  };
}

export function createPlatformApi(requestOperation: BirdcoderSdkRequestOperation): PlatformApi {
  return {
    deployments: {
      list(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderDeploymentRecordSummaryListEnvelope>("platform.deployments.list", {}, options);
      }
    },
    projects: {
      collaborators: {
        list(pathParams: PlatformProjectsCollaboratorsListPathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderProjectCollaboratorSummaryListEnvelope>("platform.projects.collaborators.list", { pathParams }, options);
        },
        upsert(pathParams: PlatformProjectsCollaboratorsUpsertPathParams, body: Types.BirdCoderUpsertProjectCollaboratorRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderProjectCollaboratorSummaryEnvelope>("platform.projects.collaborators.upsert", { pathParams, body }, options);
        }
      },
      create(body: Types.BirdCoderCreateProjectRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderProjectSummaryEnvelope>("platform.projects.create", { body }, options);
      },
      delete(pathParams: PlatformProjectsDeletePathParams, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderDeletedResourceEnvelope>("platform.projects.delete", { pathParams }, options);
      },
      deploymentTargets: {
        list(pathParams: PlatformProjectsDeploymentTargetsListPathParams, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderDeploymentTargetSummaryListEnvelope>("platform.projects.deploymentTargets.list", { pathParams }, options);
        }
      },
      git: {
        branches: {
          create(pathParams: PlatformProjectsGitBranchesCreatePathParams, body: Types.BirdCoderCreateProjectGitBranchRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.branches.create", { pathParams, body }, options);
          }
        },
        branchSwitch: {
          create(pathParams: PlatformProjectsGitBranchSwitchCreatePathParams, body: Types.BirdCoderSwitchProjectGitBranchRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.branchSwitch.create", { pathParams, body }, options);
          }
        },
        commits: {
          create(pathParams: PlatformProjectsGitCommitsCreatePathParams, body: Types.BirdCoderCommitProjectGitChangesRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.commits.create", { pathParams, body }, options);
          }
        },
        overview: {
          retrieve(pathParams: PlatformProjectsGitOverviewRetrievePathParams, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.overview.retrieve", { pathParams }, options);
          }
        },
        pushes: {
          create(pathParams: PlatformProjectsGitPushesCreatePathParams, body: Types.BirdCoderPushProjectGitBranchRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.pushes.create", { pathParams, body }, options);
          }
        },
        worktreePrune: {
          create(pathParams: PlatformProjectsGitWorktreePruneCreatePathParams, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.worktreePrune.create", { pathParams }, options);
          }
        },
        worktreeRemovals: {
          create(pathParams: PlatformProjectsGitWorktreeRemovalsCreatePathParams, body: Types.BirdCoderRemoveProjectGitWorktreeRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.worktreeRemovals.create", { pathParams, body }, options);
          }
        },
        worktrees: {
          create(pathParams: PlatformProjectsGitWorktreesCreatePathParams, body: Types.BirdCoderCreateProjectGitWorktreeRequest, options: BirdcoderSdkRequestOptions = {}) {
            return requestOperation<Types.BirdCoderProjectGitOverviewEnvelope>("platform.projects.git.worktrees.create", { pathParams, body }, options);
          }
        }
      },
      list(query: PlatformProjectsListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderProjectSummaryListEnvelope>("platform.projects.list", { query }, options);
      },
      publish: {
        create(pathParams: PlatformProjectsPublishCreatePathParams, body: Types.BirdCoderPublishProjectRequest, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderProjectPublishResultEnvelope>("platform.projects.publish.create", { pathParams, body }, options);
        }
      },
      retrieve(pathParams: PlatformProjectsRetrievePathParams, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderProjectSummaryEnvelope>("platform.projects.retrieve", { pathParams }, options);
      },
      update(pathParams: PlatformProjectsUpdatePathParams, body: Types.BirdCoderUpdateProjectRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderProjectSummaryEnvelope>("platform.projects.update", { pathParams, body }, options);
      }
    },
    workspaces: {
      create(body: Types.BirdCoderCreateWorkspaceRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderWorkspaceSummaryEnvelope>("platform.workspaces.create", { body }, options);
      },
      delete(pathParams: PlatformWorkspacesDeletePathParams, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderDeletedResourceEnvelope>("platform.workspaces.delete", { pathParams }, options);
      },
      list(query: PlatformWorkspacesListQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderWorkspaceSummaryListEnvelope>("platform.workspaces.list", { query }, options);
      },
      realtime: {
        subscribe(pathParams: PlatformWorkspacesRealtimeSubscribePathParams, query: PlatformWorkspacesRealtimeSubscribeQuery = {}, options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<void>("platform.workspaces.realtime.subscribe", { pathParams, query }, options);
        }
      },
      retrieve(pathParams: PlatformWorkspacesRetrievePathParams, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderWorkspaceSummaryEnvelope>("platform.workspaces.retrieve", { pathParams }, options);
      },
      update(pathParams: PlatformWorkspacesUpdatePathParams, body: Types.BirdCoderUpdateWorkspaceRequest, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderWorkspaceSummaryEnvelope>("platform.workspaces.update", { pathParams, body }, options);
      }
    }
  };
}
