// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http/index.ts';
import type * as Types from '../types/index.ts';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;
type SystemOperationsRetrievePathParams = Types.SystemOperationsRetrievePathParams;

export interface SystemApi {
  descriptor: {
    retrieve(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderCodingServerDescriptorEnvelope>;
  };
  health: {
    retrieve(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderCoreHealthSummaryEnvelope>;
  };
  iam: {
    runtime: {
      retrieve(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamRuntimeSettingsEnvelope>;
    };
    verificationPolicy: {
      retrieve(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderIamVerificationPolicyEnvelope>;
    };
  };
  operations: {
    retrieve(pathParams: SystemOperationsRetrievePathParams, options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderOperationDescriptorEnvelope>;
  };
  routes: {
    list(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderApiRouteCatalogEntryListEnvelope>;
  };
  runtime: {
    retrieve(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderCoreRuntimeSummaryEnvelope>;
  };
}

export function createSystemApi(requestOperation: BirdcoderSdkRequestOperation): SystemApi {
  return {
    descriptor: {
      retrieve(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderCodingServerDescriptorEnvelope>("system.descriptor.retrieve", {}, options);
      }
    },
    health: {
      retrieve(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderCoreHealthSummaryEnvelope>("system.health.retrieve", {}, options);
      }
    },
    iam: {
      runtime: {
        retrieve(options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamRuntimeSettingsEnvelope>("system.iam.runtime.retrieve", {}, options);
        }
      },
      verificationPolicy: {
        retrieve(options: BirdcoderSdkRequestOptions = {}) {
          return requestOperation<Types.BirdCoderIamVerificationPolicyEnvelope>("system.iam.verificationPolicy.retrieve", {}, options);
        }
      }
    },
    operations: {
      retrieve(pathParams: SystemOperationsRetrievePathParams, options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderOperationDescriptorEnvelope>("system.operations.retrieve", { pathParams }, options);
      }
    },
    routes: {
      list(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderApiRouteCatalogEntryListEnvelope>("system.routes.list", {}, options);
      }
    },
    runtime: {
      retrieve(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderCoreRuntimeSummaryEnvelope>("system.runtime.retrieve", {}, options);
      }
    }
  };
}
