// Generated by scripts/generate-birdcoder-sdk-family.mjs from sdks/specs/openapi/birdcoder-app-v3.openapi.json. Do not edit by hand.

import type {
  BirdcoderSdkRequestOperation,
  BirdcoderSdkRequestOptions,
} from '../http';
import type * as Types from '../types';

type BirdcoderSdkQueryValue = Types.BirdcoderSdkQueryValue;


export interface TemplatesApi {
  appTemplates: {
    list(options?: BirdcoderSdkRequestOptions): Promise<Types.BirdCoderAppTemplateSummaryListEnvelope>;
  };
}

export function createTemplatesApi(requestOperation: BirdcoderSdkRequestOperation): TemplatesApi {
  return {
    appTemplates: {
      list(options: BirdcoderSdkRequestOptions = {}) {
        return requestOperation<Types.BirdCoderAppTemplateSummaryListEnvelope>("templates.appTemplates.list", {}, options);
      }
    }
  };
}
