import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { readFileSync } from 'node:fs';

import { ensureTauriTargetClean } from './ensure-tauri-target-clean.mjs';

const modulePath = path.resolve(import.meta.dirname, 'ensure-tauri-target-clean.mjs');

assert.match(
  readFileSync(modulePath, 'utf8'),
  /if \(invokedScriptPath && invokedScriptPath === currentModulePath\) \{\s*try \{\s*runCli\(\);\s*\} catch \(error\) \{\s*console\.error\(error instanceof Error \? error\.message : String\(error\)\);\s*process\.exit\(1\);\s*\}\s*\}/s,
  'ensure-tauri-target-clean must wrap the CLI entrypoint with a top-level error handler',
);

function withTempDir(callback) {
  const tempDir = mkdtempSync(path.join(os.tmpdir(), 'birdcoder-tauri-target-clean-'));

  try {
    callback(tempDir);
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
}

function writePermissionManifest(srcTauriDir, manifestName, permissionEntries) {
  const manifestDir = path.join(srcTauriDir, 'target', 'debug', 'build', 'tauri-test', 'out');
  mkdirSync(manifestDir, { recursive: true });
  writeFileSync(path.join(manifestDir, manifestName), JSON.stringify(permissionEntries), 'utf8');
}

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const targetDir = path.join(srcTauriDir, 'target');
  const permissionFile = path.join(
    targetDir,
    'debug',
    'build',
    'tauri-test',
    'out',
    'permissions',
    'app',
    'autogenerated',
    'commands',
    'app_hide.toml',
  );

  mkdirSync(path.dirname(permissionFile), { recursive: true });
  writeFileSync(permissionFile, 'identifier = "app:hide"', 'utf8');
  writePermissionManifest(srcTauriDir, 'tauri-core-app-permission-files', [
    process.platform === 'win32' ? `\\\\?\\${permissionFile}` : permissionFile,
  ]);

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(result.removedTarget, false, 'healthy permission manifests should not trigger cleanup');
  assert.equal(existsSync(targetDir), true, 'healthy target directory must stay intact');
});

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const targetDir = path.join(srcTauriDir, 'target');
  const missingPermissionFile = path.join(
    targetDir,
    'debug',
    'build',
    'tauri-test',
    'out',
    'permissions',
    'app',
    'autogenerated',
    'commands',
    'app_hide.toml',
  );

  writePermissionManifest(srcTauriDir, 'tauri-core-app-permission-files', [missingPermissionFile]);

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(result.removedTarget, true, 'stale permission manifests must trigger cleanup');
  assert.equal(existsSync(targetDir), false, 'stale target directory must be removed');
});

withTempDir((tempDir) => {
  const desktopPackageDir = path.join(tempDir, 'sdkwork-birdcoder-desktop');
  const srcTauriDir = path.join(desktopPackageDir, 'src-tauri');
  const packageTargetDir = path.join(desktopPackageDir, '.tauri-target');
  const missingPermissionFile = path.join(
    packageTargetDir,
    'debug',
    'build',
    'tauri-test',
    'out',
    'permissions',
    'app',
    'autogenerated',
    'commands',
    'app_hide.toml',
  );

  mkdirSync(path.dirname(path.join(srcTauriDir, 'tauri.conf.json')), { recursive: true });
  writeFileSync(path.join(srcTauriDir, 'tauri.conf.json'), '{}', 'utf8');
  mkdirSync(path.join(packageTargetDir, 'debug', 'build', 'tauri-test', 'out'), { recursive: true });
  writeFileSync(
    path.join(packageTargetDir, 'debug', 'build', 'tauri-test', 'out', 'tauri-core-app-permission-files'),
    JSON.stringify([missingPermissionFile]),
    'utf8',
  );

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(
    result.removedTarget,
    true,
    'stale desktop .tauri-target permission manifests must trigger cleanup',
  );
  assert.equal(
    existsSync(packageTargetDir),
    false,
    'stale desktop .tauri-target caches must be removed alongside src-tauri target cleanup',
  );
});

console.log('ok - stale Tauri target cleanup only removes invalid permission caches');
