import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

import ts from 'typescript';

import {
  generateCodingServerClientTypes,
} from './generate-coding-server-client-types.ts';

const fixtureRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'birdcoder-client-types-codegen-'));
const sourceFile = path.join(fixtureRoot, 'coding-server-openapi.ts');
const outputFile = path.join(fixtureRoot, 'generated', 'coding-server-client.ts');

fs.writeFileSync(
  path.join(fixtureRoot, 'server-api.ts'),
  `export type BirdCoderApiQueryValue = boolean | number | string | null | undefined;
export interface BirdCoderApiTransportRequest {
  body?: unknown;
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  query?: Record<string, BirdCoderApiQueryValue>;
}
export interface BirdCoderApiTransport {
  request<TResponse>(request: BirdCoderApiTransportRequest): Promise<TResponse>;
}
`,
);

fs.writeFileSync(
  sourceFile,
  `export const BIRDCODER_FINALIZED_CODING_SERVER_OPENAPI_EVIDENCE = {
  canonicalRelativePath: 'server/windows/x64/openapi/coding-server-v1.json',
  mirroredRelativePaths: ['server/windows/x64/openapi/coding-server-v1.json'],
  openapi: '3.1.0',
  releaseTag: 'release-local',
  sha256: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
  targetCount: 1,
  targets: ['windows/x64'],
  title: 'SDKWork BirdCoder Coding Server API',
  version: 'v1',
} as const;

export const BIRDCODER_FINALIZED_CODING_SERVER_OPENAPI_OPERATIONS = [
  {
    method: 'GET',
    operationId: 'app.listProjects',
    path: '/api/app/v1/projects',
    summary: 'List projects',
    surface: 'app',
  },
  {
    method: 'GET',
    operationId: 'app.listWorkspaces',
    path: '/api/app/v1/workspaces',
    summary: 'List workspaces',
    surface: 'app',
  },
  {
    method: 'GET',
    operationId: 'core.getOperation',
    path: '/api/core/v1/operations/:operationId',
    summary: 'Get operation status',
    surface: 'core',
  },
  {
    method: 'POST',
    operationId: 'core.submitApprovalDecision',
    path: '/api/core/v1/approvals/:approvalId/decision',
    summary: 'Submit approval decision',
    surface: 'core',
  },
] as const;
`,
);

const result = await generateCodingServerClientTypes({
  outputFile,
  sourceFile,
});

assert.equal(result.operationCount, 4);
assert.equal(result.outputFile, outputFile);
assert.equal(result.sourceFile, sourceFile);
assert.ok(fs.existsSync(outputFile));

const generatedSource = fs.readFileSync(outputFile, 'utf8');
assert.match(generatedSource, /Generated by scripts\/generate-coding-server-client-types\.ts/);
assert.match(generatedSource, /buildBirdCoderFinalizedCodingServerClientRequest/);
assert.match(generatedSource, /createBirdCoderFinalizedCodingServerClient/);
assert.match(generatedSource, /core\.getOperation/);
assert.match(generatedSource, /approvalId: string/);

const consumerFile = path.join(fixtureRoot, 'generated-client-consumer.ts');
fs.writeFileSync(
  consumerFile,
  `import {
  buildBirdCoderFinalizedCodingServerClientRequest,
} from './generated/coding-server-client.ts';

const listProjectsRequest = buildBirdCoderFinalizedCodingServerClientRequest('app.listProjects', {
  query: {
    workspaceId: 'workspace-1',
  },
});

const listWorkspacesRequest = buildBirdCoderFinalizedCodingServerClientRequest('app.listWorkspaces');

const submitApprovalDecisionRequest = buildBirdCoderFinalizedCodingServerClientRequest(
  'core.submitApprovalDecision',
  {
    body: {
      decision: 'approved',
    },
    pathParams: {
      approvalId: 'approval-1',
    },
  },
);

void listProjectsRequest;
void listWorkspacesRequest;
void submitApprovalDecisionRequest;
`,
);

const program = ts.createProgram({
  options: {
    allowImportingTsExtensions: true,
    module: ts.ModuleKind.NodeNext,
    moduleResolution: ts.ModuleResolutionKind.NodeNext,
    noEmit: true,
    skipLibCheck: true,
    strict: true,
    target: ts.ScriptTarget.ES2022,
  },
  rootNames: [consumerFile],
});
const diagnostics = ts.getPreEmitDiagnostics(program);
assert.deepEqual(
  diagnostics.map((diagnostic) => {
    const message = ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n');
    if (!diagnostic.file || diagnostic.start === undefined) {
      return message;
    }
    const location = diagnostic.file.getLineAndCharacterOfPosition(diagnostic.start);
    return `${path.basename(diagnostic.file.fileName)}:${location.line + 1}:${location.character + 1} ${message}`;
  }),
  [],
);

const generatedModule = await import(`${pathToFileURL(outputFile).href}?t=${Date.now()}`);

assert.deepEqual(
  generatedModule.resolveBirdCoderFinalizedCodingServerClientOperation('app.listProjects'),
  {
    method: 'GET',
    operationId: 'app.listProjects',
    path: '/api/app/v1/projects',
    pathParamNames: [],
    summary: 'List projects',
    surface: 'app',
  },
);

assert.deepEqual(
  generatedModule.buildBirdCoderFinalizedCodingServerClientRequest('app.listProjects', {
    query: {
      workspaceId: 'workspace-1',
    },
  }),
  {
    method: 'GET',
    path: '/api/app/v1/projects',
    query: {
      workspaceId: 'workspace-1',
    },
  },
);

assert.deepEqual(
  generatedModule.buildBirdCoderFinalizedCodingServerClientRequest('core.getOperation', {
    pathParams: {
      operationId: 'op-1',
    },
  }),
  {
    method: 'GET',
    path: '/api/core/v1/operations/op-1',
  },
);

assert.throws(
  () => generatedModule.buildBirdCoderFinalizedCodingServerClientRequest('core.submitApprovalDecision', {}),
  /Missing required path parameter "approvalId"/,
);

const observedRequests: unknown[] = [];
const genericClient = generatedModule.createBirdCoderFinalizedCodingServerClient({
  async request<TResponse>(request: unknown): Promise<TResponse> {
    observedRequests.push(request);
    return {
      ok: true,
    } as TResponse;
  },
});

const genericResponse = await genericClient.request('core.submitApprovalDecision', {
  body: {
    decision: 'approved',
  },
  pathParams: {
    approvalId: 'approval-1',
  },
});
assert.deepEqual(genericResponse, { ok: true });
assert.deepEqual(observedRequests, [
  {
    body: {
      decision: 'approved',
    },
    method: 'POST',
    path: '/api/core/v1/approvals/approval-1/decision',
  },
]);

fs.rmSync(fixtureRoot, { recursive: true, force: true });
console.log('coding server client types codegen contract passed.');
