import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { pathToFileURL } from 'node:url';

interface GeneratedOpenApiOperation {
  method: string;
  operationId: string;
  path: string;
  summary: string;
  surface: string;
}

interface GeneratedOpenApiModule {
  BIRDCODER_FINALIZED_CODING_SERVER_OPENAPI_OPERATIONS?: readonly GeneratedOpenApiOperation[];
}

function readOptionValue(argv: string[], index: number, flag: string): string {
  const next = argv[index + 1];
  const normalizedNext = String(next ?? '').trim();
  if (!normalizedNext || normalizedNext.startsWith('--')) {
    throw new Error(`Missing value for ${flag}.`);
  }

  return normalizedNext;
}

function defaultSourceFile(): string {
  return path.join(
    process.cwd(),
    'packages',
    'sdkwork-birdcoder-types',
    'src',
    'generated',
    'coding-server-openapi.ts',
  );
}

function defaultOutputFile(): string {
  return path.join(
    process.cwd(),
    'packages',
    'sdkwork-birdcoder-types',
    'src',
    'generated',
    'coding-server-client.ts',
  );
}

export function parseArgs(argv: string[]) {
  const options = {
    outputFile: defaultOutputFile(),
    sourceFile: defaultSourceFile(),
  };

  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (token === '--source-file') {
      options.sourceFile = path.resolve(readOptionValue(argv, index, '--source-file'));
      index += 1;
      continue;
    }

    if (token === '--output-file') {
      options.outputFile = path.resolve(readOptionValue(argv, index, '--output-file'));
      index += 1;
      continue;
    }
  }

  return options;
}

function collectPathParamNames(routePath: string): string[] {
  return Array.from(routePath.matchAll(/:([A-Za-z0-9_]+)/g), (match) => match[1]);
}

function toPathParamsTypeSource(pathParamNames: readonly string[]): string {
  if (pathParamNames.length === 0) {
    return '{}';
  }

  return `{ ${pathParamNames.map((name) => `${name}: string`).join('; ')} }`;
}

async function loadGeneratedOpenApiModule(sourceFile: string): Promise<GeneratedOpenApiModule> {
  const normalizedSourceFile = path.resolve(sourceFile);
  if (!fs.existsSync(normalizedSourceFile)) {
    throw new Error(`Missing generated coding-server OpenAPI source file: ${normalizedSourceFile}`);
  }

  const sourceStat = fs.statSync(normalizedSourceFile);
  const moduleRef = `${pathToFileURL(normalizedSourceFile).href}?t=${sourceStat.mtimeMs}`;
  return import(moduleRef) as Promise<GeneratedOpenApiModule>;
}

function normalizeOperations(
  operations: readonly GeneratedOpenApiOperation[] | undefined,
): Array<GeneratedOpenApiOperation & { pathParamNames: string[] }> {
  const normalized = (operations ?? []).map((operation) => ({
    method: String(operation.method ?? '').trim().toUpperCase(),
    operationId: String(operation.operationId ?? '').trim(),
    path: String(operation.path ?? '').trim(),
    summary: String(operation.summary ?? '').trim(),
    surface: String(operation.surface ?? '').trim(),
    pathParamNames: collectPathParamNames(String(operation.path ?? '')),
  }));

  normalized.sort((left, right) => left.operationId.localeCompare(right.operationId));
  return normalized;
}

function buildOperationRecordSource(
  operations: ReadonlyArray<GeneratedOpenApiOperation & { pathParamNames: string[] }>,
): string {
  const lines = operations.map((operation) => {
    const descriptor = JSON.stringify({
      method: operation.method,
      operationId: operation.operationId,
      path: operation.path,
      pathParamNames: operation.pathParamNames,
      summary: operation.summary,
      surface: operation.surface,
    }, null, 2)
      .replace(/^/gm, '    ');

    return `  ${JSON.stringify(operation.operationId)}: ${descriptor},`;
  });

  return `{
${lines.join('\n')}
} as const`;
}

function buildPathParamsMapSource(
  operations: ReadonlyArray<GeneratedOpenApiOperation & { pathParamNames: string[] }>,
): string {
  const lines = operations.map((operation) => {
    return `  ${JSON.stringify(operation.operationId)}: ${toPathParamsTypeSource(operation.pathParamNames)};`;
  });

  return `{
${lines.join('\n')}
}`;
}

function buildGeneratedSource(
  operations: ReadonlyArray<GeneratedOpenApiOperation & { pathParamNames: string[] }>,
): string {
  const operationRecordSource = buildOperationRecordSource(operations);
  const pathParamsMapSource = buildPathParamsMapSource(operations);

  return `// Generated by scripts/generate-coding-server-client-types.ts from generated coding-server OpenAPI operations. Do not edit by hand.

import type {
  BirdCoderApiQueryValue,
  BirdCoderApiTransport,
  BirdCoderApiTransportRequest,
} from '../server-api.ts';

export const BIRDCODER_FINALIZED_CODING_SERVER_CLIENT_OPERATIONS = ${operationRecordSource};

export type BirdCoderFinalizedCodingServerClientOperationId =
  keyof typeof BIRDCODER_FINALIZED_CODING_SERVER_CLIENT_OPERATIONS;

interface BirdCoderFinalizedCodingServerClientPathParamsMap ${pathParamsMapSource}

export type BirdCoderFinalizedCodingServerClientPathParams<
  TOperationId extends BirdCoderFinalizedCodingServerClientOperationId,
> = BirdCoderFinalizedCodingServerClientPathParamsMap[TOperationId];

export type BirdCoderFinalizedCodingServerClientRequestOptions<
  TOperationId extends BirdCoderFinalizedCodingServerClientOperationId,
> =
  keyof BirdCoderFinalizedCodingServerClientPathParams<TOperationId> extends never
    ? {
        body?: unknown;
        pathParams?: undefined;
        query?: Record<string, BirdCoderApiQueryValue>;
      }
    : {
        body?: unknown;
        pathParams: BirdCoderFinalizedCodingServerClientPathParams<TOperationId>;
        query?: Record<string, BirdCoderApiQueryValue>;
      };

export type BirdCoderFinalizedCodingServerClientOperation<
  TOperationId extends BirdCoderFinalizedCodingServerClientOperationId =
    BirdCoderFinalizedCodingServerClientOperationId,
> = (typeof BIRDCODER_FINALIZED_CODING_SERVER_CLIENT_OPERATIONS)[TOperationId];

function replacePathParams(
  pathTemplate: string,
  pathParamNames: readonly string[],
  pathParams: Record<string, string> | undefined,
): string {
  if (pathParamNames.length === 0) {
    return pathTemplate;
  }

  let resolvedPath = pathTemplate;
  for (const paramName of pathParamNames) {
    const rawValue = pathParams?.[paramName];
    if (!rawValue) {
      throw new Error(\`Missing required path parameter "\${paramName}" for \${pathTemplate}.\`);
    }

    resolvedPath = resolvedPath.replace(\`:\${paramName}\`, encodeURIComponent(String(rawValue)));
  }

  return resolvedPath;
}

export function resolveBirdCoderFinalizedCodingServerClientOperation<
  TOperationId extends BirdCoderFinalizedCodingServerClientOperationId,
>(
  operationId: TOperationId,
): BirdCoderFinalizedCodingServerClientOperation<TOperationId> {
  return BIRDCODER_FINALIZED_CODING_SERVER_CLIENT_OPERATIONS[operationId];
}

export function buildBirdCoderFinalizedCodingServerClientRequest<
  TOperationId extends BirdCoderFinalizedCodingServerClientOperationId,
>(
  operationId: TOperationId,
  options: BirdCoderFinalizedCodingServerClientRequestOptions<TOperationId> =
    {} as BirdCoderFinalizedCodingServerClientRequestOptions<TOperationId>,
): BirdCoderApiTransportRequest {
  const operation = resolveBirdCoderFinalizedCodingServerClientOperation(operationId);
  const pathParams = (options as { pathParams?: Record<string, string> }).pathParams;
  const body = (options as { body?: unknown }).body;
  const query = (options as { query?: Record<string, BirdCoderApiQueryValue> }).query;
  const request: BirdCoderApiTransportRequest = {
    method: operation.method,
    path: replacePathParams(operation.path, operation.pathParamNames, pathParams),
  };

  if (body !== undefined) {
    request.body = body;
  }

  if (query !== undefined) {
    request.query = query;
  }

  return request;
}

export interface BirdCoderFinalizedCodingServerClient {
  request<TResponse, TOperationId extends BirdCoderFinalizedCodingServerClientOperationId>(
    operationId: TOperationId,
    options?: BirdCoderFinalizedCodingServerClientRequestOptions<TOperationId>,
  ): Promise<TResponse>;
}

export function createBirdCoderFinalizedCodingServerClient(
  transport: BirdCoderApiTransport,
): BirdCoderFinalizedCodingServerClient {
  return {
    async request<TResponse, TOperationId extends BirdCoderFinalizedCodingServerClientOperationId>(
      operationId: TOperationId,
      options?: BirdCoderFinalizedCodingServerClientRequestOptions<TOperationId>,
    ): Promise<TResponse> {
      return transport.request<TResponse>(
        buildBirdCoderFinalizedCodingServerClientRequest(operationId, options),
      );
    },
  };
}
`;
}

export async function generateCodingServerClientTypes({
  outputFile = defaultOutputFile(),
  sourceFile = defaultSourceFile(),
} = {}) {
  const module = await loadGeneratedOpenApiModule(sourceFile);
  const operations = normalizeOperations(module.BIRDCODER_FINALIZED_CODING_SERVER_OPENAPI_OPERATIONS);
  if (operations.length === 0) {
    throw new Error('Generated coding-server OpenAPI source did not expose any operations.');
  }

  const normalizedOutputFile = path.resolve(outputFile);
  fs.mkdirSync(path.dirname(normalizedOutputFile), { recursive: true });
  fs.writeFileSync(normalizedOutputFile, buildGeneratedSource(operations));

  return {
    operationCount: operations.length,
    outputFile: normalizedOutputFile,
    sourceFile: path.resolve(sourceFile),
  };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const result = await generateCodingServerClientTypes(parseArgs(process.argv.slice(2)));
  console.log(JSON.stringify(result, null, 2));
}
