import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import {
  generateCodingServerOpenApiTypes,
} from './generate-coding-server-openapi-types.mjs';

const fixtureRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'birdcoder-openapi-types-codegen-'));
const releaseAssetsDir = path.join(fixtureRoot, 'release-assets');
const outputFile = path.join(fixtureRoot, 'generated', 'coding-server-openapi.ts');

fs.mkdirSync(path.join(releaseAssetsDir, 'server', 'windows', 'x64', 'openapi'), { recursive: true });
fs.writeFileSync(
  path.join(releaseAssetsDir, 'server', 'windows', 'x64', 'openapi', 'coding-server-v1.json'),
  JSON.stringify({
    openapi: '3.1.0',
    info: {
      title: 'SDKWork BirdCoder Coding Server API',
      version: 'v1',
    },
    paths: {
      '/api/core/v1/descriptor': {
        get: {
          operationId: 'core.getDescriptor',
          summary: 'Get coding-server descriptor',
          tags: ['core'],
        },
      },
      '/api/app/v1/projects': {
        get: {
          operationId: 'app.listProjects',
          summary: 'List projects',
          tags: ['app'],
        },
      },
      '/api/admin/v1/releases': {
        get: {
          operationId: 'admin.listReleases',
          summary: 'List releases',
          tags: ['admin'],
        },
      },
    },
  }, null, 2),
);

fs.writeFileSync(
  path.join(releaseAssetsDir, 'release-manifest.json'),
  JSON.stringify({
    releaseTag: 'release-local',
    codingServerOpenApiEvidence: {
      canonicalRelativePath: 'server/windows/x64/openapi/coding-server-v1.json',
      mirroredRelativePaths: ['server/windows/x64/openapi/coding-server-v1.json'],
      targetCount: 1,
      targets: ['windows/x64'],
      sha256: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
      openapi: '3.1.0',
      version: 'v1',
      title: 'SDKWork BirdCoder Coding Server API',
    },
  }, null, 2),
);

const result = generateCodingServerOpenApiTypes({
  releaseAssetsDir,
  outputFile,
});

assert.equal(result.releaseTag, 'release-local');
assert.equal(result.outputFile, outputFile);
assert.equal(result.operationCount, 3);
assert.ok(fs.existsSync(outputFile));

const generatedSource = fs.readFileSync(outputFile, 'utf8');
assert.match(generatedSource, /Generated by scripts\/generate-coding-server-openapi-types\.mjs/);
assert.match(generatedSource, /BIRDCODER_FINALIZED_CODING_SERVER_OPENAPI_EVIDENCE/);
assert.match(generatedSource, /BIRDCODER_FINALIZED_CODING_SERVER_OPENAPI_OPERATIONS/);
assert.match(generatedSource, /core\.getDescriptor/);
assert.match(generatedSource, /app\.listProjects/);
assert.match(generatedSource, /admin\.listReleases/);
assert.match(generatedSource, /windows\/x64/);

fs.rmSync(fixtureRoot, { recursive: true, force: true });
console.log('coding server openapi types codegen contract passed.');
