import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import {
  collectCodingServerOpenApiOperations,
  generateCodingServerOpenApiTypes,
} from './generate-coding-server-openapi-types.mjs';

const fixtureRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'birdcoder-openapi-types-codegen-'));
const releaseAssetsDir = path.join(fixtureRoot, 'release-assets');
const outputFile = path.join(fixtureRoot, 'generated', 'coding-server-openapi.ts');

fs.mkdirSync(path.join(releaseAssetsDir, 'server', 'windows', 'x64', 'openapi'), { recursive: true });
fs.writeFileSync(
  path.join(releaseAssetsDir, 'server', 'windows', 'x64', 'openapi', 'coding-server-v1.json'),
  JSON.stringify({
    openapi: '3.1.0',
    info: {
      title: 'SDKWork BirdCoder Coding Server API',
      version: 'v1',
    },
    paths: {
      '/app/v3/api/system/descriptor': {
        get: {
          operationId: 'descriptor.retrieve',
          summary: 'Get coding-server descriptor',
          tags: ['system'],
          'x-sdkwork-surface': 'app',
        },
      },
      '/app/v3/api/projects': {
        get: {
          operationId: 'projects.list',
          summary: 'List projects',
          tags: ['platform'],
          'x-sdkwork-surface': 'app',
        },
      },
      '/backend/v3/api/releases': {
        get: {
          operationId: 'releases.list',
          summary: 'List releases',
          tags: ['platform'],
          'x-sdkwork-surface': 'backend',
        },
      },
    },
  }, null, 2),
);

fs.writeFileSync(
  path.join(releaseAssetsDir, 'release-manifest.json'),
  JSON.stringify({
    releaseTag: 'release-local',
    codingServerOpenApiEvidence: {
      canonicalRelativePath: 'server/windows/x64/openapi/coding-server-v1.json',
      mirroredRelativePaths: ['server/windows/x64/openapi/coding-server-v1.json'],
      targetCount: 1,
      targets: ['windows/x64'],
      sha256: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
      openapi: '3.1.0',
      version: 'v1',
      title: 'SDKWork BirdCoder Coding Server API',
    },
  }, null, 2),
);

const result = generateCodingServerOpenApiTypes({
  releaseAssetsDir,
  outputFile,
});

assert.equal(result.releaseTag, 'release-local');
assert.equal(result.outputFile, outputFile);
assert.equal(result.operationCount, 3);
assert.ok(fs.existsSync(outputFile));

const generatedSource = fs.readFileSync(outputFile, 'utf8');
assert.match(generatedSource, /Generated by scripts\/generate-coding-server-openapi-types\.mjs/);
assert.match(generatedSource, /BIRDCODER_FINALIZED_CODING_SERVER_OPENAPI_EVIDENCE/);
assert.match(generatedSource, /BIRDCODER_FINALIZED_CODING_SERVER_OPENAPI_OPERATIONS/);
assert.match(generatedSource, /descriptor\.retrieve/);
assert.match(generatedSource, /projects\.list/);
assert.match(generatedSource, /releases\.list/);
assert.doesNotMatch(generatedSource, /(?:app|backend)\.[a-zA-Z]/);
assert.match(generatedSource, /"surface": "app"/);
assert.match(generatedSource, /"surface": "backend"/);
assert.doesNotMatch(generatedSource, /"surface": "admin"/);
assert.match(generatedSource, /windows\/x64/);

const inferredOperations = collectCodingServerOpenApiOperations({
  paths: {
    '/app/v3/api/projects': {
      get: {
        operationId: 'projects.list',
        summary: 'List projects',
      },
    },
    '/backend/v3/api/releases': {
      get: {
        operationId: 'releases.list',
        summary: 'List releases',
      },
    },
    '/app/v3/api/system/descriptor': {
      get: {
        operationId: 'descriptor.retrieve',
        summary: 'Get descriptor',
      },
    },
  },
});
assert.equal(
  inferredOperations.find((operation) => operation.operationId === 'projects.list')?.surface,
  'app',
);
assert.equal(
  inferredOperations.find((operation) => operation.operationId === 'releases.list')?.surface,
  'backend',
);
assert.equal(
  inferredOperations.find((operation) => operation.operationId === 'descriptor.retrieve')?.surface,
  'app',
);
assert.throws(
  () =>
    collectCodingServerOpenApiOperations({
      paths: {
        '/api/core/v1/health': {
          get: {
            operationId: 'health.retrieve',
            summary: 'Legacy health route',
          },
        },
      },
    }),
  /forbidden noncanonical API prefix/,
);
assert.throws(
  () =>
    collectCodingServerOpenApiOperations({
      paths: {
        '/app/v3/api/system/health': {
          get: {
            operationId: 'health.retrieve',
            summary: 'Health route with stale surface',
            tags: ['system'],
            'x-sdkwork-surface': 'core',
          },
        },
      },
    }),
  /noncanonical x-sdkwork-surface/,
);

fs.rmSync(fixtureRoot, { recursive: true, force: true });
console.log('coding server openapi types codegen contract passed.');
