import assert from 'node:assert/strict';
import fs from 'node:fs';

const root = new URL('../', import.meta.url);
const read = (path) => fs.readFileSync(new URL(path, root), 'utf8');
const app = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-workbench/src/terminal/BirdcoderTerminalApp.tsx');
const projectRuntimeLocation = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-workbench/src/terminal/projectTerminalRuntimeLocation.ts');
const runtime = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-workbench/src/terminal/birdcoderTerminalRuntime.ts');
const launch = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-workbench/src/terminal/sdkworkTerminalLaunch.ts');
const appContent = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-shell/src/application/app/birdcoderAppContent.tsx');
const appMainBody = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-shell/src/application/app/birdcoderAppMainBody.tsx');
const codePage = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-code/src/pages/CodePage.tsx');
const codeSurfaceProps = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-code/src/pages/useCodePageSurfaceProps.ts');
const codeTerminalPanel = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-code/src/pages/CodeTerminalIntegrationPanel.tsx');
const studioPage = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-studio/src/pages/StudioPage.tsx');
const studioMainContent = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-studio/src/pages/StudioMainContent.tsx');
const studioTerminalPanel = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-studio/src/pages/StudioTerminalIntegrationPanel.tsx');
const commandRuntime = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-workbench/src/terminal/runtime.ts');
const profileAvailability = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-workbench/src/terminal/profileAvailability.ts');
const runtimeTarget = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-workbench/src/terminal/runtimeTarget.ts');
const tauriRuntime = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-infrastructure/src/platform/tauriRuntime.ts');
const openLocalFolder = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-infrastructure/src/platform/openLocalFolder.ts');
const projectDeviceMountSubject = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-infrastructure/src/services/projectDeviceMountSubject.ts');
const sessions = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-workbench/src/terminal/sessions.ts');
const shell = read('../sdkwork-terminal/apps/sdkwork-terminal-pc/packages/sdkwork-terminal-pc-shell/src/launch-controller.ts');
const bridge = read('../sdkwork-terminal/apps/sdkwork-terminal-pc/packages/sdkwork-terminal-pc-shell/src/shell-runtime-bridge.ts');
const webIntegration = read('../sdkwork-terminal/apps/sdkwork-terminal-pc/packages/sdkwork-terminal-pc-shell/src/web-integration.tsx');
const terminalStylesContract = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-workbench/src/terminal/contracts/sdkworkTerminalStyles.d.ts');
const commonsIndex = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-workbench/src/index.ts');
const commonsPackage = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-workbench/package.json');

assert.match(app, /WebShellApp/);
assert.match(app, /createBrowserClipboardProvider/);
assert.match(app, /import '@sdkwork\/terminal-pc-shell\/styles\.css';/);
assert.match(terminalStylesContract, /declare module '@sdkwork\/terminal-pc-shell\/styles\.css';/);
assert.match(app, /webRuntimeTarget=\{webTarget\}/);
assert.match(app, /webRuntimeClient=\{webClient\}/);
assert.match(app, /runtimeLocationId\?: string \| null/);
assert.match(app, /agentSessionId\?: string \| null/);
assert.match(app, /const boundRuntimeLocationId = props\.runtimeLocationId\?\.trim\(\) \|\| null/);
assert.match(app, /const runtimeLocationId = boundRuntimeLocationId \?\?/);
assert.match(app, /runtimeLocationResolution\.scopeKey === runtimeLocationScopeKey/);
assert.match(app, /&& !boundRuntimeLocationId/);
assert.match(app, /resolveBirdcoderWebTerminalLaunchRequest/);
assert.match(app, /webLaunchSequenceRef\.current \+= 1/);
assert.match(app, /if \(!active\)/);
assert.match(app, /webRuntimeSessionIntent=\{webRuntimeSessionIntent\}/);
assert.match(app, /webRuntimeUnavailableMessage=\{resolveBirdcoderTerminalUnavailableMessage\(\)\}/);
assert.match(launch, /resolveBirdcoderWebTerminalLaunchRequest/);
assert.match(launch, /command: normalizedCommand[\s\S]*\['\/bin\/bash', '-lc', normalizedCommand\]/);
assert.match(launch, /auditScope[\s\S]*`remote-runtime:\$\{runtimeLocationId\}`/);
assert.doesNotMatch(
  launch.match(/export async function resolveBirdcoderWebTerminalLaunchRequest[\s\S]*?\n}\n\nexport function buildBirdcoderTerminalLaunchPlan/)?.[0] ?? '',
  /workingDirectory|request\.path/,
  'Browser launch intents must never carry a client working directory or path.',
);
assert.match(runtime, /createWebRuntimeBridgeClient/);
assert.match(runtime, /VITE_SDKWORK_BIRDCODER_APPLICATION_PUBLIC_HTTP_URL/);
assert.match(runtime, /authToken/);
assert.match(runtime, /accessToken/);
assert.match(runtimeTarget, /import \{ isBirdCoderTauriRuntime \} from '@sdkwork\/birdcoder-pc-infrastructure\/platform\/tauriRuntime';/);
assert.match(runtimeTarget, /return isBirdCoderTauriRuntime\(\);/);
assert.doesNotMatch(runtimeTarget, /__TAURI__|__TAURI_INTERNALS__/);
assert.doesNotMatch(runtimeTarget, /readBirdCoderRuntimePublicEnv/);
assert.doesNotMatch(runtimeTarget, /window\.location\.protocol/);
assert.match(tauriRuntime, /import \{[\s\S]*isTauri,[\s\S]*\} from '@tauri-apps\/api\/core';/);
assert.match(tauriRuntime, /typeof tauriWindow\?\.__TAURI__\?\.core\?\.invoke === 'function'/);
assert.match(tauriRuntime, /typeof tauriWindow\?\.__TAURI_INTERNALS__\?\.invoke === 'function'/);
assert.match(tauriRuntime, /return isTauri\(\);/);
assert.match(projectDeviceMountSubject, /import \{ isBirdCoderTauriRuntime \} from '\.\.\/platform\/tauriRuntime\.ts';/);
assert.match(projectDeviceMountSubject, /if \(!isBirdCoderTauriRuntime\(\)\)/);
assert.doesNotMatch(projectDeviceMountSubject, /function isDesktopMountRealm|__TAURI__|__TAURI_INTERNALS__/);
assert.match(openLocalFolder, /resolveBirdCoderTauriInvoke/);
assert.doesNotMatch(openLocalFolder, /__TAURI__|__TAURI_INTERNALS__|import\('@tauri-apps\/api\/core'\)/);
assert.match(runtime, /resolveBirdcoderBrowserTerminalClient/);
assert.match(runtime, /browserTerminalClientCache/);
assert.match(runtime, /tokenManager/);
assert.doesNotMatch(runtime, /if \(!authToken \|\| !accessToken\)/);
assert.doesNotMatch(runtime, /TERMINAL_RUNTIME_BASE_URL/);
assert.doesNotMatch(runtime, /getDefaultBirdCoderIdeServicesRuntimeConfig/);
assert.match(profileAvailability, /return \{ canLaunch: true, reason: null \};/);
assert.doesNotMatch(
  profileAvailability,
  /isBirdcoderTauriRuntime|@tauri-apps\/api\/core|terminal_cli_profile_detect|__TAURI__/,
  'Terminal profile presentation must remain host-neutral; runtime adapters own browser and Tauri execution.',
);
assert.doesNotMatch(sessions, /readTaggedValue/);
assert.match(sessions, /resolveBirdcoderBrowserTerminalClient/);
assert.match(sessions, /client\.sessionIndex\(\)/);
assert.match(sessions, /normalizeBrowserRuntimeSessionRecord/);
assert.doesNotMatch(sessions, /TERMINAL_RUNTIME_BASE_URL/);
assert.match(sessions, /case 'starting':/);
assert.match(sessions, /case 'failed':/);
assert.match(sessions, /case 'exited':/);
assert.match(sessions, /if \(!isBirdcoderTauriRuntime\(\)\)/);
assert.doesNotMatch(sessions, /!window\.__TAURI__/);
assert.match(app, /sessionRevision/);
assert.match(app, /terminal-runtime-loading/);
assert.match(app, /useProjectTerminalRuntimeLocationIdResolver/);
assert.match(projectRuntimeLocation, /agentSessionService\.listSessionsByProject/);
assert.match(projectRuntimeLocation, /agentSessionService\.listRuntimeBindings/);
assert.match(projectRuntimeLocation, /binding\.isCurrent[\s\S]*binding\.status === 'active'/);
assert.match(codePage, /selectedSessionRuntimeLocationId: selectedAgentSession\?\.runtimeLocationId/);
assert.match(codeSurfaceProps, /runtimeLocationId: selectedSessionRuntimeLocationId/);
assert.match(codeTerminalPanel, /runtimeLocationId=\{runtimeLocationId\}/);
assert.match(codeTerminalPanel, /left\.runtimeLocationId === right\.runtimeLocationId/);
assert.match(studioPage, /terminalRuntimeLocationId: selectedSession\?\.runtimeLocationId/);
assert.match(studioMainContent, /runtimeLocationId=\{terminalRuntimeLocationId\}/);
assert.match(studioTerminalPanel, /runtimeLocationId=\{runtimeLocationId\}/);
assert.match(studioTerminalPanel, /left\.runtimeLocationId === right\.runtimeLocationId/);
assert.match(appContent, /effectiveAgentSessionRuntimeLocationId = activeProjectAgentSessions\.find/);
assert.match(appContent, /runtimeLocationId=\{effectiveAgentSessionRuntimeLocationId\}/);
assert.match(appMainBody, /terminalAgentSessionId = terminalRequest\?\.agentSessionId\?\.trim\(\) \|\| agentSessionId/);
assert.match(appMainBody, /terminalProjectId = terminalRequest\?\.projectId\?\.trim\(\) \|\| projectId/);
assert.match(appMainBody, /terminalRequest\?\.runtimeLocationId\?\.trim\(\) \|\| runtimeLocationId/);
assert.match(appMainBody, /agentSessionId=\{terminalAgentSessionId\}/);
assert.match(appMainBody, /projectId=\{terminalProjectId\}/);
assert.match(appMainBody, /runtimeLocationId=\{terminalRuntimeLocationId\}/);
assert.match(appMainBody, /onWebLaunchBlocked=\{handleTerminalLaunchBlocked\}/);
assert.match(webIntegration, /<ShellApp mode="web" \{\.\.\.props\} \/>/);
assert.doesNotMatch(commonsIndex, /BirdcoderTerminalApp/);
assert.match(commonsPackage, /"\.\/terminal\/BirdcoderTerminalApp"/);
assert.match(shell, /export function applyWebRuntimeSessionIntent/);
assert.match(shell, /args\.mode !== "web"/);
assert.match(bridge, /applyWebRuntimeSessionIntentController/);

console.log('terminal browser runtime contract passed.');
