import assert from 'node:assert/strict';
import fs from 'node:fs';

const root = new URL('../', import.meta.url);
const read = (path) => fs.readFileSync(new URL(path, root), 'utf8');
const app = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/src/terminal/BirdcoderTerminalApp.tsx');
const runtime = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/src/terminal/birdcoderTerminalRuntime.ts');
const commandRuntime = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/src/terminal/runtime.ts');
const profileAvailability = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/src/terminal/profileAvailability.ts');
const runtimeTarget = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/src/terminal/runtimeTarget.ts');
const sessions = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/src/terminal/sessions.ts');
const shell = read('../sdkwork-terminal/apps/sdkwork-terminal-pc/packages/sdkwork-terminal-pc-shell/src/launch-controller.ts');
const bridge = read('../sdkwork-terminal/apps/sdkwork-terminal-pc/packages/sdkwork-terminal-pc-shell/src/shell-runtime-bridge.ts');
const webIntegration = read('../sdkwork-terminal/apps/sdkwork-terminal-pc/packages/sdkwork-terminal-pc-shell/src/web-integration.tsx');
const terminalStylesContract = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/src/terminal/contracts/sdkworkTerminalStyles.d.ts');
const commonsIndex = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/src/index.ts');
const commonsPackage = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/package.json');

assert.match(app, /WebShellApp/);
assert.match(app, /createBrowserClipboardProvider/);
assert.match(app, /import '@sdkwork\/terminal-pc-shell\/styles\.css';/);
assert.match(terminalStylesContract, /declare module '@sdkwork\/terminal-pc-shell\/styles\.css';/);
assert.match(app, /webRuntimeTarget=\{webTarget\}/);
assert.match(app, /webRuntimeClient=\{webClient\}/);
assert.doesNotMatch(app, /webRuntimeSessionIntent=/);
assert.match(app, /webRuntimeUnavailableMessage=\{resolveBirdcoderTerminalUnavailableMessage\(\)\}/);
assert.match(runtime, /createWebRuntimeBridgeClient/);
assert.match(runtime, /VITE_SDKWORK_BIRDCODER_APPLICATION_PUBLIC_HTTP_URL/);
assert.match(runtime, /authToken/);
assert.match(runtime, /accessToken/);
assert.match(runtimeTarget, /typeof host\.__TAURI__\?\.core\?\.invoke === 'function'/);
assert.match(runtimeTarget, /typeof host\.__TAURI_INTERNALS__\?\.invoke === 'function'/);
assert.match(runtimeTarget, /runtimeTarget && runtimeTarget !== 'desktop'/);
assert.match(runtimeTarget, /runtimeTarget === 'desktop' \|\| window\.location\.protocol === 'tauri:'/);
assert.doesNotMatch(runtimeTarget, /Boolean\(host\.__TAURI__ \|\| host\.__TAURI_INTERNALS__\)/);
assert.match(runtime, /resolveBirdcoderBrowserTerminalClient/);
assert.doesNotMatch(runtime, /TERMINAL_RUNTIME_BASE_URL/);
assert.doesNotMatch(runtime, /getDefaultBirdCoderIdeServicesRuntimeConfig/);
assert.match(profileAvailability, /if \(!isBirdcoderTauriRuntime\(\)\)/);
assert.doesNotMatch(profileAvailability, /!window\.__TAURI__/);
assert.doesNotMatch(sessions, /readTaggedValue/);
assert.match(sessions, /resolveBirdcoderBrowserTerminalClient/);
assert.match(sessions, /client\.sessionIndex\(\)/);
assert.match(sessions, /normalizeBrowserRuntimeSessionRecord/);
assert.doesNotMatch(sessions, /TERMINAL_RUNTIME_BASE_URL/);
assert.match(sessions, /case 'starting':/);
assert.match(sessions, /case 'failed':/);
assert.match(sessions, /case 'exited':/);
assert.match(sessions, /if \(!isBirdcoderTauriRuntime\(\)\)/);
assert.doesNotMatch(sessions, /!window\.__TAURI__/);
assert.match(webIntegration, /<ShellApp mode="web" \{\.\.\.props\} \/>/);
assert.doesNotMatch(commonsIndex, /BirdcoderTerminalApp/);
assert.match(commonsPackage, /"\.\/terminal\/BirdcoderTerminalApp"/);
assert.match(shell, /export function applyWebRuntimeSessionIntent/);
assert.match(shell, /args\.mode !== "web"/);
assert.match(bridge, /applyWebRuntimeSessionIntentController/);

console.log('terminal browser runtime contract passed.');
