import assert from 'node:assert/strict';
import fs from 'node:fs';

const root = new URL('../', import.meta.url);
const read = (path) => fs.readFileSync(new URL(path, root), 'utf8');
const app = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/src/terminal/BirdcoderTerminalApp.tsx');
const runtime = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/src/terminal/birdcoderTerminalRuntime.ts');
const commandRuntime = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/src/terminal/runtime.ts');
const intent = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/src/terminal/birdcoderTerminalLaunchIntent.ts');
const sessions = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/src/terminal/sessions.ts');
const shell = read('../sdkwork-terminal/apps/sdkwork-terminal-pc/packages/sdkwork-terminal-pc-shell/src/launch-controller.ts');
const bridge = read('../sdkwork-terminal/apps/sdkwork-terminal-pc/packages/sdkwork-terminal-pc-shell/src/shell-runtime-bridge.ts');
const webIntegration = read('../sdkwork-terminal/apps/sdkwork-terminal-pc/packages/sdkwork-terminal-pc-shell/src/web-integration.tsx');
const commonsIndex = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/src/index.ts');
const commonsPackage = read('apps/sdkwork-birdcoder-pc/packages/sdkwork-birdcoder-pc-commons/package.json');

assert.match(app, /WebShellApp/);
assert.match(app, /createBrowserClipboardProvider/);
assert.match(app, /webRuntimeSessionIntent=\{webIntent\}/);
assert.match(app, /webRuntimeInitialSessionIntent=\{initialWebIntentRef\.current\}/);
assert.match(app, /if \(!webShellMountedRef\.current && waitsForInitialLaunch\) return null;/);
assert.doesNotMatch(app, /key=\{webIntent/);
assert.match(runtime, /createWebRuntimeBridgeClient/);
assert.match(runtime, /typeof host\.__TAURI__\?\.core\?\.invoke === 'function'/);
assert.match(runtime, /typeof host\.__TAURI_INTERNALS__\?\.invoke === 'function'/);
assert.match(runtime, /runtimeTarget && runtimeTarget !== 'desktop'/);
assert.match(runtime, /runtimeTarget === 'desktop' \|\| window\.location\.protocol === 'tauri:'/);
assert.doesNotMatch(runtime, /Boolean\(host\.__TAURI__ \|\| host\.__TAURI_INTERNALS__\)/);
assert.match(runtime, /createAuthorizedFetchEventSourceFactory/);
assert.match(runtime, /accessToken,/);
assert.match(runtime, /createAuthorizedFetchEventSourceFactory\(authToken, \{ accessToken \}\)/);
assert.match(runtime, /APP_SESSION_CHANGE_EVENT_NAME/);
assert.match(runtime, /useSyncExternalStore/);
assert.match(runtime, /if \(!authToken \|\| !accessToken\) return undefined;/);
assert.match(runtime, /cachedBirdcoderTerminalAuthTokens/);
assert.match(runtime, /VITE_SDKWORK_BIRDCODER_TERMINAL_RUNTIME_BASE_URL/);
assert.match(commandRuntime, /if \(!isBirdcoderTauriRuntime\(\)\)/);
assert.doesNotMatch(commandRuntime, /!window\.__TAURI__/);
assert.match(intent, /\['\/bin\/sh', '-lc', requestedCommand\]/);
assert.match(intent, /`cwd:\$\{workingDirectory\}`/);
assert.match(sessions, /readTaggedValue\(session\.tags, 'cwd:'\)/);
assert.match(sessions, /createWebRuntimeBridgeClient\(\{[\s\S]*accessToken,/);
assert.match(sessions, /if \(!authToken \|\| !accessToken\) \{[\s\S]*return \[\];/);
assert.match(sessions, /case 'starting':/);
assert.match(sessions, /case 'failed':/);
assert.match(sessions, /case 'exited':/);
assert.match(sessions, /if \(!isBirdcoderTauriRuntime\(\)\)/);
assert.doesNotMatch(sessions, /!window\.__TAURI__/);
assert.match(webIntegration, /<ShellApp mode="web" \{\.\.\.props\} \/>/);
assert.doesNotMatch(commonsIndex, /BirdcoderTerminalApp/);
assert.match(commonsPackage, /"\.\/terminal\/BirdcoderTerminalApp"/);
assert.match(shell, /export function applyWebRuntimeSessionIntent/);
assert.match(shell, /args\.mode !== "web"/);
assert.match(bridge, /applyWebRuntimeSessionIntentController/);

console.log('terminal browser runtime contract passed.');
