name: sdkwork_birdcoder_flutter_mobile_app_sdk_consumer
description: SDKWork BirdCoder Flutter mobile app SDK consumer assembly
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sdkwork_birdcoder_app_sdk:
    path: generated/server-openapi
