image:
  repository: ghcr.io/sdkwork-cloud/sdkwork-birdcoder-server
  tag: release-local
  digest: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 18989

ingress:
  enabled: false

persistence:
  enabled: true
  size: 5Gi

runtime:
  accelerator: cpu
