name: sdkwork_birdcoder_flutter_mobile_admin_core
description: SDKWork Birdcoder Flutter Mobile Admin Core
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sdkwork_birdcoder_flutter_mobile_core:
    path: ../sdkwork_birdcoder_flutter_mobile_core
  sdkwork_birdcoder_flutter_mobile_backend_sdk_consumer:
    path: ../../sdks/sdkwork_birdcoder_flutter_mobile_backend_sdk_consumer
