pub const BOOTSTRAP_WORKSPACE_OWNER_USER_ID: &str = "100000000000000001";
pub const SQLITE_AUTHORITY_DEFAULT_TENANT_ID: &str = "0";
pub const SQLITE_AUTHORITY_DEFAULT_ORGANIZATION_ID: &str = "0";
pub const SQLITE_DEFAULT_PRIVATE_DATA_SCOPE_VALUE: i64 = 1;
pub const DEFAULT_TREE_ROOT_ID: &str = "0";
pub const DEFAULT_TREE_ROOT_UUID: &str = "0";
